# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu Nov 22 17:42:42 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 800)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(550, 580, 381, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.txt_lastActions = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.txt_lastActions.setGeometry(QtCore.QRect(0, 0, 371, 151))
        self.txt_lastActions.setObjectName("txt_lastActions")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.optionsTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.optionsTabWidget.setGeometry(QtCore.QRect(550, 10, 381, 561))
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.iniTab = QtGui.QWidget()
        self.iniTab.setObjectName("iniTab")
        self.group_M = QtGui.QGroupBox(self.iniTab)
        self.group_M.setGeometry(QtCore.QRect(10, 230, 181, 301))
        self.group_M.setObjectName("group_M")
        self.lab_ZM = QtGui.QLabel(self.group_M)
        self.lab_ZM.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.lab_ZM.setObjectName("lab_ZM")
        self.lab_AM = QtGui.QLabel(self.group_M)
        self.lab_AM.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.lab_AM.setObjectName("lab_AM")
        self.lab_RM = QtGui.QLabel(self.group_M)
        self.lab_RM.setGeometry(QtCore.QRect(10, 90, 67, 31))
        self.lab_RM.setObjectName("lab_RM")
        self.lab_JM = QtGui.QLabel(self.group_M)
        self.lab_JM.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.lab_JM.setObjectName("lab_JM")
        self.lab_Beta2M = QtGui.QLabel(self.group_M)
        self.lab_Beta2M.setGeometry(QtCore.QRect(10, 180, 67, 31))
        self.lab_Beta2M.setObjectName("lab_Beta2M")
        self.lab_Beta4M = QtGui.QLabel(self.group_M)
        self.lab_Beta4M.setGeometry(QtCore.QRect(10, 210, 67, 31))
        self.lab_Beta4M.setObjectName("lab_Beta4M")
        self.lab_Beta6M = QtGui.QLabel(self.group_M)
        self.lab_Beta6M.setGeometry(QtCore.QRect(10, 236, 67, 31))
        self.lab_Beta6M.setObjectName("lab_Beta6M")
        self.lab_PiM = QtGui.QLabel(self.group_M)
        self.lab_PiM.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.lab_PiM.setObjectName("lab_PiM")
        self.sb_ZM = QtGui.QSpinBox(self.group_M)
        self.sb_ZM.setGeometry(QtCore.QRect(107, 30, 61, 27))
        self.sb_ZM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_ZM.setObjectName("sb_ZM")
        self.sb_AM = QtGui.QSpinBox(self.group_M)
        self.sb_AM.setGeometry(QtCore.QRect(107, 60, 61, 27))
        self.sb_AM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_AM.setMaximum(250)
        self.sb_AM.setObjectName("sb_AM")
        self.dsb_RM = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_RM.setGeometry(QtCore.QRect(90, 90, 81, 27))
        self.dsb_RM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_RM.setSingleStep(0.1)
        self.dsb_RM.setObjectName("dsb_RM")
        self.dsb_JM = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_JM.setGeometry(QtCore.QRect(100, 120, 71, 27))
        self.dsb_JM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_JM.setDecimals(1)
        self.dsb_JM.setSingleStep(0.5)
        self.dsb_JM.setObjectName("dsb_JM")
        self.cb_PiM = QtGui.QComboBox(self.group_M)
        self.cb_PiM.setGeometry(QtCore.QRect(110, 150, 61, 27))
        self.cb_PiM.setObjectName("cb_PiM")
        self.dsb_Beta2M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta2M.setGeometry(QtCore.QRect(100, 180, 69, 27))
        self.dsb_Beta2M.setDecimals(3)
        self.dsb_Beta2M.setMinimum(-1.0)
        self.dsb_Beta2M.setMaximum(1.0)
        self.dsb_Beta2M.setSingleStep(0.1)
        self.dsb_Beta2M.setObjectName("dsb_Beta2M")
        self.dsb_Beta4M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta4M.setGeometry(QtCore.QRect(100, 210, 69, 27))
        self.dsb_Beta4M.setDecimals(3)
        self.dsb_Beta4M.setMinimum(-1.0)
        self.dsb_Beta4M.setMaximum(1.0)
        self.dsb_Beta4M.setSingleStep(0.1)
        self.dsb_Beta4M.setObjectName("dsb_Beta4M")
        self.dsb_Beta6M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta6M.setGeometry(QtCore.QRect(100, 240, 69, 27))
        self.dsb_Beta6M.setDecimals(3)
        self.dsb_Beta6M.setMinimum(-1.0)
        self.dsb_Beta6M.setMaximum(1.0)
        self.dsb_Beta6M.setSingleStep(0.1)
        self.dsb_Beta6M.setObjectName("dsb_Beta6M")
        self.label_31 = QtGui.QLabel(self.group_M)
        self.label_31.setGeometry(QtCore.QRect(10, 270, 67, 21))
        self.label_31.setObjectName("label_31")
        self.dsb_motherEn = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_motherEn.setGeometry(QtCore.QRect(68, 270, 101, 27))
        self.dsb_motherEn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_motherEn.setMaximum(10000.0)
        self.dsb_motherEn.setSingleStep(1.0)
        self.dsb_motherEn.setProperty("value", 0.0)
        self.dsb_motherEn.setObjectName("dsb_motherEn")
        self.groupBox_3 = QtGui.QGroupBox(self.iniTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 361, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.label_11.setObjectName("label_11")
        self.l_iniFilename = QtGui.QLabel(self.groupBox_3)
        self.l_iniFilename.setGeometry(QtCore.QRect(100, 51, 261, 20))
        self.l_iniFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_iniFilename.setObjectName("l_iniFilename")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_6.setObjectName("label_6")
        self.l_transitionName = QtGui.QLabel(self.groupBox_3)
        self.l_transitionName.setGeometry(QtCore.QRect(90, 30, 271, 16))
        self.l_transitionName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_transitionName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_transitionName.setObjectName("l_transitionName")
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_16.setObjectName("label_16")
        self.b_chooseROBTDFile = QtGui.QPushButton(self.groupBox_3)
        self.b_chooseROBTDFile.setGeometry(QtCore.QRect(208, 80, 151, 27))
        self.b_chooseROBTDFile.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_chooseROBTDFile.setObjectName("b_chooseROBTDFile")
        self.group_M_2 = QtGui.QGroupBox(self.iniTab)
        self.group_M_2.setGeometry(QtCore.QRect(190, 230, 181, 301))
        self.group_M_2.setObjectName("group_M_2")
        self.lab_ZD = QtGui.QLabel(self.group_M_2)
        self.lab_ZD.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.lab_ZD.setObjectName("lab_ZD")
        self.lab_AD = QtGui.QLabel(self.group_M_2)
        self.lab_AD.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.lab_AD.setObjectName("lab_AD")
        self.lab_RD = QtGui.QLabel(self.group_M_2)
        self.lab_RD.setGeometry(QtCore.QRect(10, 90, 67, 31))
        self.lab_RD.setObjectName("lab_RD")
        self.lab_JD = QtGui.QLabel(self.group_M_2)
        self.lab_JD.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.lab_JD.setObjectName("lab_JD")
        self.lab_Beta2D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta2D.setGeometry(QtCore.QRect(10, 180, 67, 31))
        self.lab_Beta2D.setObjectName("lab_Beta2D")
        self.lab_Beta4D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta4D.setGeometry(QtCore.QRect(10, 210, 67, 31))
        self.lab_Beta4D.setObjectName("lab_Beta4D")
        self.lab_Beta6D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta6D.setGeometry(QtCore.QRect(10, 236, 67, 31))
        self.lab_Beta6D.setObjectName("lab_Beta6D")
        self.lab_PiD = QtGui.QLabel(self.group_M_2)
        self.lab_PiD.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.lab_PiD.setObjectName("lab_PiD")
        self.sb_ZD = QtGui.QSpinBox(self.group_M_2)
        self.sb_ZD.setGeometry(QtCore.QRect(117, 30, 61, 27))
        self.sb_ZD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_ZD.setObjectName("sb_ZD")
        self.sb_AD = QtGui.QSpinBox(self.group_M_2)
        self.sb_AD.setGeometry(QtCore.QRect(117, 60, 61, 27))
        self.sb_AD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_AD.setMaximum(250)
        self.sb_AD.setObjectName("sb_AD")
        self.dsb_RD = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_RD.setGeometry(QtCore.QRect(100, 90, 81, 27))
        self.dsb_RD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_RD.setSingleStep(0.1)
        self.dsb_RD.setObjectName("dsb_RD")
        self.dsb_JD = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_JD.setGeometry(QtCore.QRect(110, 120, 71, 27))
        self.dsb_JD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_JD.setDecimals(1)
        self.dsb_JD.setSingleStep(0.5)
        self.dsb_JD.setObjectName("dsb_JD")
        self.cb_PiD = QtGui.QComboBox(self.group_M_2)
        self.cb_PiD.setGeometry(QtCore.QRect(120, 150, 61, 27))
        self.cb_PiD.setObjectName("cb_PiD")
        self.dsb_Beta2D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta2D.setGeometry(QtCore.QRect(110, 180, 69, 27))
        self.dsb_Beta2D.setDecimals(3)
        self.dsb_Beta2D.setMinimum(-1.0)
        self.dsb_Beta2D.setMaximum(1.0)
        self.dsb_Beta2D.setSingleStep(0.1)
        self.dsb_Beta2D.setObjectName("dsb_Beta2D")
        self.dsb_Beta4D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta4D.setGeometry(QtCore.QRect(110, 210, 69, 27))
        self.dsb_Beta4D.setDecimals(3)
        self.dsb_Beta4D.setMinimum(-1.0)
        self.dsb_Beta4D.setMaximum(1.0)
        self.dsb_Beta4D.setSingleStep(0.1)
        self.dsb_Beta4D.setObjectName("dsb_Beta4D")
        self.dsb_Beta6D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta6D.setGeometry(QtCore.QRect(110, 240, 69, 27))
        self.dsb_Beta6D.setDecimals(3)
        self.dsb_Beta6D.setMinimum(-1.0)
        self.dsb_Beta6D.setMaximum(1.0)
        self.dsb_Beta6D.setSingleStep(0.1)
        self.dsb_Beta6D.setObjectName("dsb_Beta6D")
        self.label_33 = QtGui.QLabel(self.group_M_2)
        self.label_33.setGeometry(QtCore.QRect(10, 270, 67, 21))
        self.label_33.setObjectName("label_33")
        self.dsb_daughterEn = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_daughterEn.setGeometry(QtCore.QRect(70, 270, 111, 27))
        self.dsb_daughterEn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_daughterEn.setMaximum(10000.0)
        self.dsb_daughterEn.setObjectName("dsb_daughterEn")
        self.groupBox = QtGui.QGroupBox(self.iniTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 371, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 21, 21))
        self.label_4.setObjectName("label_4")
        self.cb_type = QtGui.QComboBox(self.groupBox)
        self.cb_type.setGeometry(QtCore.QRect(60, 60, 111, 27))
        self.cb_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_type.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cb_type.setFrame(True)
        self.cb_type.setObjectName("cb_type")
        self.cb_process = QtGui.QComboBox(self.groupBox)
        self.cb_process.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_process.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_process.setObjectName("cb_process")
        self.dsb_MixingRatio = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_MixingRatio.setGeometry(QtCore.QRect(280, 30, 81, 27))
        self.dsb_MixingRatio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_MixingRatio.setMaximum(100.0)
        self.dsb_MixingRatio.setObjectName("dsb_MixingRatio")
        self.dsb_Q = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_Q.setGeometry(QtCore.QRect(30, 90, 141, 27))
        self.dsb_Q.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_Q.setMaximum(20000.0)
        self.dsb_Q.setObjectName("dsb_Q")
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(180, 60, 61, 31))
        self.label_30.setObjectName("label_30")
        self.dsb_halflife = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_halflife.setGeometry(QtCore.QRect(240, 64, 121, 27))
        self.dsb_halflife.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_halflife.setDecimals(4)
        self.dsb_halflife.setMaximum(1000000000.0)
        self.dsb_halflife.setObjectName("dsb_halflife")
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(180, 90, 67, 31))
        self.label_25.setObjectName("label_25")
        self.dsb_logft = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_logft.setGeometry(QtCore.QRect(270, 100, 91, 27))
        self.dsb_logft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_logft.setDecimals(4)
        self.dsb_logft.setMaximum(20.0)
        self.dsb_logft.setObjectName("dsb_logft")
        self.optionsTabWidget.addTab(self.iniTab, "")
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName("configTab")
        self.groupBox_4 = QtGui.QGroupBox(self.configTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 67, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 67, 31))
        self.label_27.setObjectName("label_27")
        self.dsb_gA = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gA.setGeometry(QtCore.QRect(80, 30, 81, 27))
        self.dsb_gA.setDecimals(4)
        self.dsb_gA.setProperty("value", 1.2723)
        self.dsb_gA.setObjectName("dsb_gA")
        self.dsb_gAeff = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gAeff.setGeometry(QtCore.QRect(80, 70, 81, 27))
        self.dsb_gAeff.setProperty("value", 1.0)
        self.dsb_gAeff.setObjectName("dsb_gAeff")
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(180, 30, 31, 31))
        self.label_29.setObjectName("label_29")
        self.dsb_gM = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gM.setGeometry(QtCore.QRect(220, 30, 71, 27))
        self.dsb_gM.setDecimals(3)
        self.dsb_gM.setProperty("value", 4.706)
        self.dsb_gM.setObjectName("dsb_gM")
        self.dsb_gP = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gP.setGeometry(QtCore.QRect(220, 70, 71, 27))
        self.dsb_gP.setMinimum(-1000.0)
        self.dsb_gP.setMaximum(1000.0)
        self.dsb_gP.setProperty("value", 0.0)
        self.dsb_gP.setObjectName("dsb_gP")
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(180, 70, 31, 31))
        self.label_28.setObjectName("label_28")
        self.b_resetNSO = QtGui.QPushButton(self.configTab)
        self.b_resetNSO.setGeometry(QtCore.QRect(20, 480, 141, 31))
        self.b_resetNSO.setObjectName("b_resetNSO")
        self.gb_ESP = QtGui.QGroupBox(self.configTab)
        self.gb_ESP.setEnabled(False)
        self.gb_ESP.setGeometry(QtCore.QRect(10, 170, 351, 311))
        self.gb_ESP.setObjectName("gb_ESP")
        self.cb_potential = QtGui.QComboBox(self.gb_ESP)
        self.cb_potential.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_potential.setObjectName("cb_potential")
        self.dsb_Xp = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_Xp.setGeometry(QtCore.QRect(280, 260, 69, 27))
        self.dsb_Xp.setProperty("value", 0.86)
        self.dsb_Xp.setObjectName("dsb_Xp")
        self.label_32 = QtGui.QLabel(self.gb_ESP)
        self.label_32.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_32.setObjectName("label_32")
        self.cb_reverseGhallagher = QtGui.QCheckBox(self.gb_ESP)
        self.cb_reverseGhallagher.setGeometry(QtCore.QRect(130, 70, 181, 22))
        self.cb_reverseGhallagher.setObjectName("cb_reverseGhallagher")
        self.dsb_V0Sn = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0Sn.setGeometry(QtCore.QRect(280, 180, 69, 27))
        self.dsb_V0Sn.setProperty("value", 7.2)
        self.dsb_V0Sn.setObjectName("dsb_V0Sn")
        self.label_37 = QtGui.QLabel(self.gb_ESP)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label_37.setObjectName("label_37")
        self.label_41 = QtGui.QLabel(self.gb_ESP)
        self.label_41.setGeometry(QtCore.QRect(180, 210, 101, 41))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtGui.QLabel(self.gb_ESP)
        self.label_42.setGeometry(QtCore.QRect(10, 210, 91, 41))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtGui.QLabel(self.gb_ESP)
        self.label_43.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.label_43.setObjectName("label_43")
        self.dsb_Xn = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_Xn.setGeometry(QtCore.QRect(100, 260, 69, 27))
        self.dsb_Xn.setProperty("value", 0.86)
        self.dsb_Xn.setObjectName("dsb_Xn")
        self.dsb_V0n = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0n.setGeometry(QtCore.QRect(100, 180, 69, 27))
        self.dsb_V0n.setProperty("value", 49.6)
        self.dsb_V0n.setObjectName("dsb_V0n")
        self.dsb_V0p = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0p.setGeometry(QtCore.QRect(100, 216, 69, 31))
        self.dsb_V0p.setProperty("value", 49.6)
        self.dsb_V0p.setObjectName("dsb_V0p")
        self.label_44 = QtGui.QLabel(self.gb_ESP)
        self.label_44.setGeometry(QtCore.QRect(10, 260, 81, 31))
        self.label_44.setObjectName("label_44")
        self.cb_overrideCoupling = QtGui.QCheckBox(self.gb_ESP)
        self.cb_overrideCoupling.setGeometry(QtCore.QRect(10, 100, 181, 22))
        self.cb_overrideCoupling.setObjectName("cb_overrideCoupling")
        self.dsb_V0Sp = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0Sp.setGeometry(QtCore.QRect(280, 220, 69, 27))
        self.dsb_V0Sp.setProperty("value", 7.2)
        self.dsb_V0Sp.setObjectName("dsb_V0Sp")
        self.cb_forceSpin = QtGui.QCheckBox(self.gb_ESP)
        self.cb_forceSpin.setGeometry(QtCore.QRect(10, 70, 121, 22))
        self.cb_forceSpin.setChecked(True)
        self.cb_forceSpin.setObjectName("cb_forceSpin")
        self.label_45 = QtGui.QLabel(self.gb_ESP)
        self.label_45.setGeometry(QtCore.QRect(180, 260, 71, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtGui.QLabel(self.gb_ESP)
        self.label_46.setGeometry(QtCore.QRect(180, 180, 101, 31))
        self.label_46.setObjectName("label_46")
        self.dsb_energyMargin = QtGui.QDoubleSpinBox(self.gb_ESP)
        self.dsb_energyMargin.setGeometry(QtCore.QRect(130, 130, 91, 27))
        self.dsb_energyMargin.setDecimals(1)
        self.dsb_energyMargin.setMaximum(20.0)
        self.dsb_energyMargin.setProperty("value", 1.0)
        self.dsb_energyMargin.setObjectName("dsb_energyMargin")
        self.label_7 = QtGui.QLabel(self.configTab)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 67, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cb_nmeMethod = QtGui.QComboBox(self.configTab)
        self.cb_nmeMethod.setGeometry(QtCore.QRect(90, 120, 101, 27))
        self.cb_nmeMethod.setObjectName("cb_nmeMethod")
        self.optionsTabWidget.addTab(self.configTab, "")
        self.lab_logo = QtGui.QLabel(self.centralwidget)
        self.lab_logo.setGeometry(QtCore.QRect(10, 10, 331, 111))
        self.lab_logo.setAutoFillBackground(False)
        self.lab_logo.setFrameShadow(QtGui.QFrame.Raised)
        self.lab_logo.setText("")
        self.lab_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.lab_logo.setObjectName("lab_logo")
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 130, 531, 611))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.bsgMainTab = QtGui.QWidget()
        self.bsgMainTab.setObjectName("bsgMainTab")
        self.horizontalLayoutWidget = QtGui.QWidget(self.bsgMainTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 511, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gv_plotSpectrum = PlotWidget(self.horizontalLayoutWidget)
        self.gv_plotSpectrum.setObjectName("gv_plotSpectrum")
        self.horizontalLayout.addWidget(self.gv_plotSpectrum)
        self.b_runBSG = QtGui.QPushButton(self.bsgMainTab)
        self.b_runBSG.setGeometry(QtCore.QRect(420, 10, 101, 51))
        self.b_runBSG.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_runBSG.setCheckable(False)
        self.b_runBSG.setChecked(False)
        self.b_runBSG.setDefault(False)
        self.b_runBSG.setFlat(False)
        self.b_runBSG.setObjectName("b_runBSG")
        self.le_outputName = QtGui.QLineEdit(self.bsgMainTab)
        self.le_outputName.setGeometry(QtCore.QRect(10, 30, 101, 27))
        self.le_outputName.setObjectName("le_outputName")
        self.label_10 = QtGui.QLabel(self.bsgMainTab)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 111, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.rb_currentSettings = QtGui.QRadioButton(self.bsgMainTab)
        self.rb_currentSettings.setGeometry(QtCore.QRect(240, 0, 141, 22))
        self.rb_currentSettings.setChecked(True)
        self.rb_currentSettings.setObjectName("rb_currentSettings")
        self.rb_configFile = QtGui.QRadioButton(self.bsgMainTab)
        self.rb_configFile.setGeometry(QtCore.QRect(240, 30, 61, 22))
        self.rb_configFile.setObjectName("rb_configFile")
        self.label_5 = QtGui.QLabel(self.bsgMainTab)
        self.label_5.setGeometry(QtCore.QRect(130, 0, 111, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.b_chooseConfigFile = QtGui.QPushButton(self.bsgMainTab)
        self.b_chooseConfigFile.setGeometry(QtCore.QRect(300, 30, 91, 27))
        self.b_chooseConfigFile.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_chooseConfigFile.setObjectName("b_chooseConfigFile")
        self.mainTabWidget.addTab(self.bsgMainTab, "")
        self.bsgOptionsTab = QtGui.QWidget()
        self.bsgOptionsTab.setObjectName("bsgOptionsTab")
        self.groupBox_2 = QtGui.QGroupBox(self.bsgOptionsTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 511, 551))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.b_enable_all = QtGui.QPushButton(self.groupBox_2)
        self.b_enable_all.setGeometry(QtCore.QRect(10, 520, 101, 31))
        self.b_enable_all.setObjectName("b_enable_all")
        self.b_disable_all = QtGui.QPushButton(self.groupBox_2)
        self.b_disable_all.setGeometry(QtCore.QRect(120, 520, 101, 31))
        self.b_disable_all.setObjectName("b_disable_all")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 420, 151, 80))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 290, 191, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.cb_relativistic = QtGui.QCheckBox(self.groupBox_6)
        self.cb_relativistic.setGeometry(QtCore.QRect(20, 170, 111, 22))
        self.cb_relativistic.setChecked(True)
        self.cb_relativistic.setObjectName("cb_relativistic")
        self.cb_isovector = QtGui.QCheckBox(self.groupBox_6)
        self.cb_isovector.setGeometry(QtCore.QRect(20, 90, 181, 22))
        self.cb_isovector.setChecked(True)
        self.cb_isovector.setObjectName("cb_isovector")
        self.cb_C_shape = QtGui.QComboBox(self.groupBox_6)
        self.cb_C_shape.setGeometry(QtCore.QRect(40, 60, 121, 27))
        self.cb_C_shape.setObjectName("cb_C_shape")
        self.cb_C = QtGui.QCheckBox(self.groupBox_6)
        self.cb_C.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.cb_C.setChecked(True)
        self.cb_C.setObjectName("cb_C")
        self.cb_coupled = QtGui.QCheckBox(self.groupBox_6)
        self.cb_coupled.setGeometry(QtCore.QRect(50, 110, 91, 31))
        self.cb_coupled.setObjectName("cb_coupled")
        self.cb_C_deformation = QtGui.QCheckBox(self.groupBox_6)
        self.cb_C_deformation.setGeometry(QtCore.QRect(20, 140, 121, 22))
        self.cb_C_deformation.setChecked(True)
        self.cb_C_deformation.setObjectName("cb_C_deformation")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 130, 191, 161))
        self.groupBox_7.setObjectName("groupBox_7")
        self.cb_efs_deformation = QtGui.QCheckBox(self.groupBox_7)
        self.cb_efs_deformation.setGeometry(QtCore.QRect(20, 120, 151, 31))
        self.cb_efs_deformation.setChecked(True)
        self.cb_efs_deformation.setObjectName("cb_efs_deformation")
        self.cb_efs = QtGui.QCheckBox(self.groupBox_7)
        self.cb_efs.setGeometry(QtCore.QRect(20, 30, 151, 22))
        self.cb_efs.setChecked(True)
        self.cb_efs.setObjectName("cb_efs")
        self.cb_shape = QtGui.QComboBox(self.groupBox_7)
        self.cb_shape.setGeometry(QtCore.QRect(40, 90, 121, 27))
        self.cb_shape.setObjectName("cb_shape")
        self.cb_ens = QtGui.QCheckBox(self.groupBox_7)
        self.cb_ens.setGeometry(QtCore.QRect(20, 60, 171, 22))
        self.cb_ens.setChecked(True)
        self.cb_ens.setObjectName("cb_ens")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 191, 131))
        self.groupBox_8.setObjectName("groupBox_8")
        self.cb_radiative = QtGui.QCheckBox(self.groupBox_8)
        self.cb_radiative.setGeometry(QtCore.QRect(20, 100, 181, 22))
        self.cb_radiative.setChecked(True)
        self.cb_radiative.setObjectName("cb_radiative")
        self.cb_fermi = QtGui.QCheckBox(self.groupBox_8)
        self.cb_fermi.setGeometry(QtCore.QRect(20, 61, 151, 31))
        self.cb_fermi.setChecked(True)
        self.cb_fermi.setObjectName("cb_fermi")
        self.cb_phasespace = QtGui.QCheckBox(self.groupBox_8)
        self.cb_phasespace.setGeometry(QtCore.QRect(20, 30, 131, 22))
        self.cb_phasespace.setChecked(True)
        self.cb_phasespace.setObjectName("cb_phasespace")
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_9.setGeometry(QtCore.QRect(240, 10, 201, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.cb_Q = QtGui.QCheckBox(self.groupBox_9)
        self.cb_Q.setGeometry(QtCore.QRect(20, 60, 141, 22))
        self.cb_Q.setChecked(True)
        self.cb_Q.setObjectName("cb_Q")
        self.cb_recoil = QtGui.QCheckBox(self.groupBox_9)
        self.cb_recoil.setGeometry(QtCore.QRect(20, 30, 141, 22))
        self.cb_recoil.setChecked(True)
        self.cb_recoil.setObjectName("cb_recoil")
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_10.setGeometry(QtCore.QRect(240, 100, 231, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.cb_mismatch = QtGui.QCheckBox(self.groupBox_10)
        self.cb_mismatch.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.cb_mismatch.setChecked(True)
        self.cb_mismatch.setObjectName("cb_mismatch")
        self.cb_screening = QtGui.QCheckBox(self.groupBox_10)
        self.cb_screening.setGeometry(QtCore.QRect(20, 30, 111, 22))
        self.cb_screening.setChecked(True)
        self.cb_screening.setObjectName("cb_screening")
        self.cb_exchange = QtGui.QCheckBox(self.groupBox_10)
        self.cb_exchange.setGeometry(QtCore.QRect(20, 60, 101, 22))
        self.cb_exchange.setChecked(True)
        self.cb_exchange.setObjectName("cb_exchange")
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_11.setGeometry(QtCore.QRect(240, 330, 231, 181))
        self.groupBox_11.setObjectName("groupBox_11")
        self.sb_steps = QtGui.QSpinBox(self.groupBox_11)
        self.sb_steps.setEnabled(False)
        self.sb_steps.setGeometry(QtCore.QRect(90, 150, 111, 27))
        self.sb_steps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_steps.setMaximum(100000)
        self.sb_steps.setProperty("value", 1000)
        self.sb_steps.setObjectName("sb_steps")
        self.dsb_stepSize = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.dsb_stepSize.setEnabled(True)
        self.dsb_stepSize.setGeometry(QtCore.QRect(90, 110, 111, 27))
        self.dsb_stepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_stepSize.setMaximum(10000.0)
        self.dsb_stepSize.setProperty("value", 0.1)
        self.dsb_stepSize.setObjectName("dsb_stepSize")
        self.label_40 = QtGui.QLabel(self.groupBox_11)
        self.label_40.setGeometry(QtCore.QRect(20, 100, 41, 41))
        self.label_40.setObjectName("label_40")
        self.rb_stepSize = QtGui.QRadioButton(self.groupBox_11)
        self.rb_stepSize.setGeometry(QtCore.QRect(60, 110, 31, 22))
        self.rb_stepSize.setText("")
        self.rb_stepSize.setChecked(True)
        self.rb_stepSize.setObjectName("rb_stepSize")
        self.rb_steps = QtGui.QRadioButton(self.groupBox_11)
        self.rb_steps.setEnabled(True)
        self.rb_steps.setGeometry(QtCore.QRect(60, 150, 31, 22))
        self.rb_steps.setText("")
        self.rb_steps.setObjectName("rb_steps")
        self.label_39 = QtGui.QLabel(self.groupBox_11)
        self.label_39.setGeometry(QtCore.QRect(20, 70, 41, 31))
        self.label_39.setObjectName("label_39")
        self.label_38 = QtGui.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.label_38.setObjectName("label_38")
        self.dsb_end = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.dsb_end.setGeometry(QtCore.QRect(80, 70, 121, 27))
        self.dsb_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_end.setMaximum(20000.0)
        self.dsb_end.setObjectName("dsb_end")
        self.dsb_begin = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.dsb_begin.setGeometry(QtCore.QRect(80, 30, 121, 27))
        self.dsb_begin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_begin.setMaximum(20000.0)
        self.dsb_begin.setProperty("value", 0.0)
        self.dsb_begin.setObjectName("dsb_begin")
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(240, 230, 281, 91))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_36 = QtGui.QLabel(self.groupBox_12)
        self.label_36.setGeometry(QtCore.QRect(20, 60, 41, 31))
        self.label_36.setObjectName("label_36")
        self.dsb_dAc = QtGui.QDoubleSpinBox(self.groupBox_12)
        self.dsb_dAc.setGeometry(QtCore.QRect(200, 30, 69, 27))
        self.dsb_dAc.setDecimals(3)
        self.dsb_dAc.setMinimum(-100.0)
        self.dsb_dAc.setMaximum(100.0)
        self.dsb_dAc.setObjectName("dsb_dAc")
        self.dsb_lambda = QtGui.QDoubleSpinBox(self.groupBox_12)
        self.dsb_lambda.setGeometry(QtCore.QRect(70, 60, 69, 27))
        self.dsb_lambda.setDecimals(3)
        self.dsb_lambda.setMinimum(-100.0)
        self.dsb_lambda.setMaximum(100.0)
        self.dsb_lambda.setObjectName("dsb_lambda")
        self.dsb_bAc = QtGui.QDoubleSpinBox(self.groupBox_12)
        self.dsb_bAc.setGeometry(QtCore.QRect(70, 30, 69, 27))
        self.dsb_bAc.setDecimals(3)
        self.dsb_bAc.setMinimum(-100.0)
        self.dsb_bAc.setMaximum(100.0)
        self.dsb_bAc.setObjectName("dsb_bAc")
        self.label_34 = QtGui.QLabel(self.groupBox_12)
        self.label_34.setGeometry(QtCore.QRect(20, 30, 41, 21))
        self.label_34.setObjectName("label_34")
        self.cb_enforceNME = QtGui.QCheckBox(self.groupBox_12)
        self.cb_enforceNME.setGeometry(QtCore.QRect(150, 60, 121, 22))
        self.cb_enforceNME.setObjectName("cb_enforceNME")
        self.label_35 = QtGui.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(150, 20, 41, 41))
        self.label_35.setObjectName("label_35")
        self.b_resetSSO = QtGui.QPushButton(self.groupBox_2)
        self.b_resetSSO.setGeometry(QtCore.QRect(230, 520, 131, 31))
        self.b_resetSSO.setObjectName("b_resetSSO")
        self.mainTabWidget.addTab(self.bsgOptionsTab, "")
        self.l_RMP = QtGui.QLabel(self.centralwidget)
        self.l_RMP.setGeometry(QtCore.QRect(350, 10, 171, 31))
        self.l_RMP.setLineWidth(0)
        self.l_RMP.setOpenExternalLinks(True)
        self.l_RMP.setObjectName("l_RMP")
        self.l_RMP_2 = QtGui.QLabel(self.centralwidget)
        self.l_RMP_2.setGeometry(QtCore.QRect(350, 40, 171, 41))
        self.l_RMP_2.setOpenExternalLinks(True)
        self.l_RMP_2.setObjectName("l_RMP_2")
        self.l_RMP_3 = QtGui.QLabel(self.centralwidget)
        self.l_RMP_3.setGeometry(QtCore.QRect(350, 80, 171, 31))
        self.l_RMP_3.setOpenExternalLinks(True)
        self.l_RMP_3.setObjectName("l_RMP_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuOpen = QtGui.QMenu(self.menu_File)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtGui.QMenu(self.menu_File)
        self.menuSave.setObjectName("menuSave")
        self.menuComponent_paths = QtGui.QMenu(self.menu_File)
        self.menuComponent_paths.setObjectName("menuComponent_paths")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlotting = QtGui.QMenu(self.menuBar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuDatabase = QtGui.QMenu(self.menuBar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menuBar)
        self.a_exit = QtGui.QAction(MainWindow)
        self.a_exit.setObjectName("a_exit")
        self.a_loadIni = QtGui.QAction(MainWindow)
        self.a_loadIni.setObjectName("a_loadIni")
        self.a_loadConfig = QtGui.QAction(MainWindow)
        self.a_loadConfig.setObjectName("a_loadConfig")
        self.a_about = QtGui.QAction(MainWindow)
        self.a_about.setObjectName("a_about")
        self.a_feedback = QtGui.QAction(MainWindow)
        self.a_feedback.setObjectName("a_feedback")
        self.a_saveIni = QtGui.QAction(MainWindow)
        self.a_saveIni.setObjectName("a_saveIni")
        self.a_saveConfig = QtGui.QAction(MainWindow)
        self.a_saveConfig.setObjectName("a_saveConfig")
        self.a_new = QtGui.QAction(MainWindow)
        self.a_new.setObjectName("a_new")
        self.a_bsgExec = QtGui.QAction(MainWindow)
        self.a_bsgExec.setObjectName("a_bsgExec")
        self.a_exchangeData = QtGui.QAction(MainWindow)
        self.a_exchangeData.setObjectName("a_exchangeData")
        self.a_clearPlots = QtGui.QAction(MainWindow)
        self.a_clearPlots.setObjectName("a_clearPlots")
        self.a_exportPlot = QtGui.QAction(MainWindow)
        self.a_exportPlot.setObjectName("a_exportPlot")
        self.a_plotColorSettings = QtGui.QAction(MainWindow)
        self.a_plotColorSettings.setObjectName("a_plotColorSettings")
        self.a_loadDeformation = QtGui.QAction(MainWindow)
        self.a_loadDeformation.setObjectName("a_loadDeformation")
        self.a_loadRadii = QtGui.QAction(MainWindow)
        self.a_loadRadii.setObjectName("a_loadRadii")
        self.a_findTransition = QtGui.QAction(MainWindow)
        self.a_findTransition.setObjectName("a_findTransition")
        self.actionNME_executable = QtGui.QAction(MainWindow)
        self.actionNME_executable.setObjectName("actionNME_executable")
        self.menuOpen.addAction(self.a_loadIni)
        self.menuOpen.addAction(self.a_loadConfig)
        self.menuSave.addAction(self.a_saveIni)
        self.menuSave.addAction(self.a_saveConfig)
        self.menuComponent_paths.addAction(self.a_bsgExec)
        self.menuComponent_paths.addAction(self.a_exchangeData)
        self.menu_File.addAction(self.a_new)
        self.menu_File.addAction(self.menuComponent_paths.menuAction())
        self.menu_File.addAction(self.menuOpen.menuAction())
        self.menu_File.addAction(self.menuSave.menuAction())
        self.menu_File.addAction(self.a_exit)
        self.menuHelp.addAction(self.a_feedback)
        self.menuHelp.addAction(self.a_about)
        self.menuPlotting.addAction(self.a_clearPlots)
        self.menuPlotting.addAction(self.a_exportPlot)
        self.menuDatabase.addAction(self.a_loadDeformation)
        self.menuDatabase.addAction(self.a_loadRadii)
        self.menuDatabase.addAction(self.a_findTransition)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())
        self.menuBar.addAction(self.menuPlotting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.optionsTabWidget.setCurrentIndex(0)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.group_M.setTitle(QtGui.QApplication.translate("MainWindow", "Mother", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZM.setToolTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZM.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AM.setToolTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AM.setText(QtGui.QApplication.translate("MainWindow", "A:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RM.setToolTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RM.setText(QtGui.QApplication.translate("MainWindow", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JM.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JM.setText(QtGui.QApplication.translate("MainWindow", "Spin:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2M.setText(QtGui.QApplication.translate("MainWindow", "Beta2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4M.setText(QtGui.QApplication.translate("MainWindow", "Beta4:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6M.setText(QtGui.QApplication.translate("MainWindow", "Beta6:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiM.setToolTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiM.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZM.setToolTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AM.setToolTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setToolTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setSuffix(QtGui.QApplication.translate("MainWindow", " fm", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JM.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PiM.setToolTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PiM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta2M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta4M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta6M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the parent level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_motherEn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the parent level", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_motherEn.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setToolTip(QtGui.QApplication.translate("MainWindow", "Current ini file used for the transition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setStatusTip(QtGui.QApplication.translate("MainWindow", "Current ini file used for the transition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current file:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_iniFilename.setToolTip(QtGui.QApplication.translate("MainWindow", "Current ini file used for the transition", None, QtGui.QApplication.UnicodeUTF8))
        self.l_iniFilename.setStatusTip(QtGui.QApplication.translate("MainWindow", "Current ini file used for the transition", None, QtGui.QApplication.UnicodeUTF8))
        self.l_iniFilename.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Transition:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_transitionName.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "ROBTD File:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chooseROBTDFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chooseROBTDFile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chooseROBTDFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.group_M_2.setTitle(QtGui.QApplication.translate("MainWindow", "Daughter", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZD.setToolTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZD.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AD.setToolTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AD.setText(QtGui.QApplication.translate("MainWindow", "A:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RD.setToolTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RD.setText(QtGui.QApplication.translate("MainWindow", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JD.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JD.setText(QtGui.QApplication.translate("MainWindow", "Spin:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2D.setText(QtGui.QApplication.translate("MainWindow", "Beta2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4D.setText(QtGui.QApplication.translate("MainWindow", "Beta4:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6D.setText(QtGui.QApplication.translate("MainWindow", "Beta6:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiD.setToolTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiD.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZD.setToolTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AD.setToolTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setToolTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setSuffix(QtGui.QApplication.translate("MainWindow", " fm", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JD.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PiD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta2D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta4D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta6D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the child level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_daughterEn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the child level", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_daughterEn.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Transition", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("MainWindow", "Decay process", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setStatusTip(QtGui.QApplication.translate("MainWindow", "Decay process", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Decay type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Decay type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Mixing Ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("MainWindow", "Q Value in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setStatusTip(QtGui.QApplication.translate("MainWindow", "Q Value in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Q: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setToolTip(QtGui.QApplication.translate("MainWindow", "Decay type", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setStatusTip(QtGui.QApplication.translate("MainWindow", "Decay type", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_process.setToolTip(QtGui.QApplication.translate("MainWindow", "Decay process", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_process.setStatusTip(QtGui.QApplication.translate("MainWindow", "Decay process", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_MixingRatio.setToolTip(QtGui.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_MixingRatio.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Q.setToolTip(QtGui.QApplication.translate("MainWindow", "Q Value in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Q.setStatusTip(QtGui.QApplication.translate("MainWindow", "Q Value in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Q.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setToolTip(QtGui.QApplication.translate("MainWindow", "Partial Halflife", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setStatusTip(QtGui.QApplication.translate("MainWindow", "Partial Halflife", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Halflife:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_halflife.setToolTip(QtGui.QApplication.translate("MainWindow", "Partial Halflife", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_halflife.setStatusTip(QtGui.QApplication.translate("MainWindow", "Partial Halflife", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_halflife.setSuffix(QtGui.QApplication.translate("MainWindow", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setToolTip(QtGui.QApplication.translate("MainWindow", "Log ft value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setStatusTip(QtGui.QApplication.translate("MainWindow", "Log ft value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Log ft:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_logft.setToolTip(QtGui.QApplication.translate("MainWindow", "Log ft value", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_logft.setStatusTip(QtGui.QApplication.translate("MainWindow", "Log ft value", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.iniTab), QtGui.QApplication.translate("MainWindow", "Transition Info", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Constants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setToolTip(QtGui.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setStatusTip(QtGui.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "gA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setToolTip(QtGui.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setStatusTip(QtGui.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "gA_eff:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gA.setToolTip(QtGui.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gA.setStatusTip(QtGui.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gAeff.setToolTip(QtGui.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gAeff.setStatusTip(QtGui.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setToolTip(QtGui.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setStatusTip(QtGui.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "gM:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gM.setToolTip(QtGui.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gP.setToolTip(QtGui.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_gP.setStatusTip(QtGui.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setToolTip(QtGui.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setStatusTip(QtGui.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "gP:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_resetNSO.setText(QtGui.QApplication.translate("MainWindow", "Reset to ...", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_ESP.setTitle(QtGui.QApplication.translate("MainWindow", "Extreme Single Particle", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_potential.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose the mean-field potential", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_potential.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the mean-field potential", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setToolTip(QtGui.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setStatusTip(QtGui.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Energy Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_reverseGhallagher.setText(QtGui.QApplication.translate("MainWindow", "Reversed Ghallagher", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0Sn.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0Sn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose the mean-field potential", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the mean-field potential", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Potential:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "V0S protons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setToolTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setStatusTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "V0 protons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setToolTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setStatusTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "V0 neutrons:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Xn.setToolTip(QtGui.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Xn.setStatusTip(QtGui.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0n.setToolTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0n.setStatusTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0p.setToolTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0p.setStatusTip(QtGui.QApplication.translate("MainWindow", "Potential depth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setToolTip(QtGui.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setStatusTip(QtGui.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "X neutron:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_overrideCoupling.setText(QtGui.QApplication.translate("MainWindow", "Override SP coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0Sp.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_V0Sp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_forceSpin.setText(QtGui.QApplication.translate("MainWindow", "Force Spin", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setToolTip(QtGui.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setStatusTip(QtGui.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "X proton:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setToolTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin-orbit strength", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "V0S neutrons:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_energyMargin.setToolTip(QtGui.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_energyMargin.setStatusTip(QtGui.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_energyMargin.setSuffix(QtGui.QApplication.translate("MainWindow", " MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Nuclear Structure Options", None, QtGui.QApplication.UnicodeUTF8))
        self.b_runBSG.setToolTip(QtGui.QApplication.translate("MainWindow", "Run the spectrum shape generator", None, QtGui.QApplication.UnicodeUTF8))
        self.b_runBSG.setStatusTip(QtGui.QApplication.translate("MainWindow", "Run the spectrum shape generator", None, QtGui.QApplication.UnicodeUTF8))
        self.b_runBSG.setText(QtGui.QApplication.translate("MainWindow", "Run!", None, QtGui.QApplication.UnicodeUTF8))
        self.le_outputName.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the output name of all files generated (omit extension)", None, QtGui.QApplication.UnicodeUTF8))
        self.le_outputName.setText(QtGui.QApplication.translate("MainWindow", "output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the output name of all files generated (omit extension)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Output name:", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_currentSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Use the Spectral Shape & Nuclear Structure options as currently specified in the GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_currentSettings.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use the Spectral Shape & Nuclear Structure options as currently specified in the GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_currentSettings.setText(QtGui.QApplication.translate("MainWindow", "Current settings", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_configFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Use the Spectrum Shape and Nuclear Structure Options as specified in an external config file", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_configFile.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use the Spectrum Shape and Nuclear Structure Options as specified in an external config file", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_configFile.setText(QtGui.QApplication.translate("MainWindow", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Configuration:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chooseConfigFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgMainTab), QtGui.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.b_enable_all.setToolTip(QtGui.QApplication.translate("MainWindow", "Enable all corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.b_enable_all.setStatusTip(QtGui.QApplication.translate("MainWindow", "Enable all corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.b_enable_all.setText(QtGui.QApplication.translate("MainWindow", "Enable All", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disable_all.setToolTip(QtGui.QApplication.translate("MainWindow", "Disable all corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disable_all.setStatusTip(QtGui.QApplication.translate("MainWindow", "Disable all corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disable_all.setText(QtGui.QApplication.translate("MainWindow", "Disable All", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Nuclear Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_relativistic.setToolTip(QtGui.QApplication.translate("MainWindow", "Take into account relativistic (O(v/c) ~ 1/(MR)) terms in the Shape factor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_relativistic.setStatusTip(QtGui.QApplication.translate("MainWindow", "Take into account relativistic (O(v/c) ~ 1/(MR)) terms in the Shape factor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_relativistic.setText(QtGui.QApplication.translate("MainWindow", "Relativistic", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isovector.setToolTip(QtGui.QApplication.translate("MainWindow", "Correction due to CVC breakdown due to isospin symmetry breaking", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isovector.setStatusTip(QtGui.QApplication.translate("MainWindow", "Correction due to CVC breakdown due to isospin symmetry breaking", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isovector.setText(QtGui.QApplication.translate("MainWindow", "Isovector Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_shape.setToolTip(QtGui.QApplication.translate("MainWindow", "Shape of the nuclear charge distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_shape.setStatusTip(QtGui.QApplication.translate("MainWindow", "Shape of the nuclear charge distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C.setToolTip(QtGui.QApplication.translate("MainWindow", "Nuclear shape factor, taking into account the convolution of leptonic and nuclear wave functions and induced currents", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C.setStatusTip(QtGui.QApplication.translate("MainWindow", "Nuclear shape factor, taking into account the convolution of leptonic and nuclear wave functions and induced currents", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C.setText(QtGui.QApplication.translate("MainWindow", "Shape factor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setToolTip(QtGui.QApplication.translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setStatusTip(QtGui.QApplication.translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setText(QtGui.QApplication.translate("MainWindow", "Coupled", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_deformation.setToolTip(QtGui.QApplication.translate("MainWindow", "Take into account nuclear deformation in the convolution of lepton and nuclear wave functions", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_deformation.setStatusTip(QtGui.QApplication.translate("MainWindow", "Take into account nuclear deformation in the convolution of lepton and nuclear wave functions", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_deformation.setText(QtGui.QApplication.translate("MainWindow", "Deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Electrostatic", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs_deformation.setToolTip(QtGui.QApplication.translate("MainWindow", "Additional correction factor to take into account nuclear deformation on the final state electric interaction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs_deformation.setStatusTip(QtGui.QApplication.translate("MainWindow", "Additional correction factor to take into account nuclear deformation on the final state electric interaction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs_deformation.setText(QtGui.QApplication.translate("MainWindow", "ES Deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs.setToolTip(QtGui.QApplication.translate("MainWindow", "Correction factor to the Fermi function to take into account the finite size of the nuclear charge distribution. Approximated as a uniformly charged sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs.setStatusTip(QtGui.QApplication.translate("MainWindow", "Correction factor to the Fermi function to take into account the finite size of the nuclear charge distribution. Approximated as a uniformly charged sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs.setText(QtGui.QApplication.translate("MainWindow", "ES Finite Size", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_shape.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose nuclear shape for higher-order correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_shape.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose nuclear shape for higher-order correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ens.setToolTip(QtGui.QApplication.translate("MainWindow", "Higher-order correction to the ES Finite size above, by going beyond a uniformly charged sphere to a Fermi or Modified Gaussian shape.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ens.setStatusTip(QtGui.QApplication.translate("MainWindow", "Higher-order correction to the ES Finite size above, by going beyond a uniformly charged sphere to a Fermi or Modified Gaussian shape.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ens.setText(QtGui.QApplication.translate("MainWindow", "ES Nuclear Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_radiative.setToolTip(QtGui.QApplication.translate("MainWindow", "Additional QED & Weak interaction radiative corrections, through (virtual) photon, gamma and W exchange", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_radiative.setStatusTip(QtGui.QApplication.translate("MainWindow", "Additional QED & Weak interaction radiative corrections, through (virtual) photon, gamma and W exchange", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_radiative.setText(QtGui.QApplication.translate("MainWindow", "Radiative corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fermi.setToolTip(QtGui.QApplication.translate("MainWindow", "Final state interaction between outgoing lepton and final nuclear charge density, approximated as a point charge", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fermi.setStatusTip(QtGui.QApplication.translate("MainWindow", "Final state interaction between outgoing lepton and final nuclear charge density, approximated as a point charge", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fermi.setText(QtGui.QApplication.translate("MainWindow", "Fermi Function", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_phasespace.setToolTip(QtGui.QApplication.translate("MainWindow", "The kinematical phase space factor, pW(W0-W)^2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_phasespace.setStatusTip(QtGui.QApplication.translate("MainWindow", "The kinematical phase space factor, pW(W0-W)^2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_phasespace.setText(QtGui.QApplication.translate("MainWindow", "Phase Space", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Kinematic", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Q.setToolTip(QtGui.QApplication.translate("MainWindow", "Correction term due to the movement of the Coulomb potential in case the nucleus is not infinitely massive", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Q.setStatusTip(QtGui.QApplication.translate("MainWindow", "Correction term due to the movement of the Coulomb potential in case the nucleus is not infinitely massive", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Q.setText(QtGui.QApplication.translate("MainWindow", "Coulomb Recoil", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_recoil.setToolTip(QtGui.QApplication.translate("MainWindow", "Kinematical correction factor to take into account the finite nuclear mass.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_recoil.setStatusTip(QtGui.QApplication.translate("MainWindow", "Kinematical correction factor to take into account the finite nuclear mass.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_recoil.setText(QtGui.QApplication.translate("MainWindow", "Nuclear Recoil", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Atomic", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_mismatch.setToolTip(QtGui.QApplication.translate("MainWindow", "Average treatment of the decrease in phase space due to atomic excitations.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_mismatch.setStatusTip(QtGui.QApplication.translate("MainWindow", "Average treatment of the decrease in phase space due to atomic excitations.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_mismatch.setText(QtGui.QApplication.translate("MainWindow", "Mismatch", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_screening.setToolTip(QtGui.QApplication.translate("MainWindow", "Screening of the nuclear charge by atomic electrons", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_screening.setStatusTip(QtGui.QApplication.translate("MainWindow", "Screening of the nuclear charge by atomic electrons", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_screening.setText(QtGui.QApplication.translate("MainWindow", "Screening", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_exchange.setToolTip(QtGui.QApplication.translate("MainWindow", "Atomic exchange process, decay directly into bound state.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_exchange.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic exchange process, decay directly into bound state.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_exchange.setText(QtGui.QApplication.translate("MainWindow", "Exchange", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_steps.setToolTip(QtGui.QApplication.translate("MainWindow", "Number of steps", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_steps.setStatusTip(QtGui.QApplication.translate("MainWindow", "Number of steps", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_steps.setSuffix(QtGui.QApplication.translate("MainWindow", " steps", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_stepSize.setToolTip(QtGui.QApplication.translate("MainWindow", "Step size in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_stepSize.setStatusTip(QtGui.QApplication.translate("MainWindow", "Step size in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_stepSize.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setToolTip(QtGui.QApplication.translate("MainWindow", "Step size or number of steps for which to calculate the spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setStatusTip(QtGui.QApplication.translate("MainWindow", "Step size or number of steps for which to calculate the spectrum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setToolTip(QtGui.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setStatusTip(QtGui.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setToolTip(QtGui.QApplication.translate("MainWindow", "Starting energy from where to calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setStatusTip(QtGui.QApplication.translate("MainWindow", "Starting energy from where to calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Begin:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_end.setToolTip(QtGui.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_end.setStatusTip(QtGui.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_end.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_begin.setStatusTip(QtGui.QApplication.translate("MainWindow", "Starting energy from where to calculate", "Starting energy from where to calculate", QtGui.QApplication.UnicodeUTF8))
        self.dsb_begin.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Matrix Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setToolTip(QtGui.QApplication.translate("MainWindow", "Related to induced pseudoscalar in Holstein\'s formalism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setStatusTip(QtGui.QApplication.translate("MainWindow", "Related to induced pseudoscalar in Holstein\'s formalism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Λ:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setToolTip(QtGui.QApplication.translate("MainWindow", "Weak magnetism, in Holstein\'s formalism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setStatusTip(QtGui.QApplication.translate("MainWindow", "Weak magnetism, in Holstein\'s formalism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "b/Ac:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enforceNME.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose whether to enforce the values for b/Ac, d/Ac and Lambda written here, or leave it to the program", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enforceNME.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose whether to enforce the values for b/Ac, d/Ac and Lambda written here, or leave it to the program", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enforceNME.setText(QtGui.QApplication.translate("MainWindow", "Enforce", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setToolTip(QtGui.QApplication.translate("MainWindow", "Induced tensor, as in Holstein\'s formalism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setStatusTip(QtGui.QApplication.translate("MainWindow", "Induced tensor, as in Holstein\'s formalism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "d/Ac:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_resetSSO.setText(QtGui.QApplication.translate("MainWindow", "Reset to ...", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgOptionsTab), QtGui.QApplication.translate("MainWindow", "Spectral Shape Options", None, QtGui.QApplication.UnicodeUTF8))
        self.l_RMP.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.90.015008\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to Rev. Mod. Phys.</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_RMP_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://arxiv.org/abs/1803.00525\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to BSG paper</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.l_RMP_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/leenderthayen/BSG\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to Github</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen.setTitle(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponent_paths.setTitle(QtGui.QApplication.translate("MainWindow", "Component paths", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlotting.setTitle(QtGui.QApplication.translate("MainWindow", "&Plotting", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "&Database", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadIni.setText(QtGui.QApplication.translate("MainWindow", "Ini file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadIni.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadConfig.setText(QtGui.QApplication.translate("MainWindow", "Config file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.a_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.a_feedback.setText(QtGui.QApplication.translate("MainWindow", "Submit feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveIni.setText(QtGui.QApplication.translate("MainWindow", "Ini file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveIni.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveConfig.setText(QtGui.QApplication.translate("MainWindow", "Config file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))
        self.a_new.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.a_new.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.a_bsgExec.setText(QtGui.QApplication.translate("MainWindow", "BSG executable", None, QtGui.QApplication.UnicodeUTF8))
        self.a_bsgExec.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exchangeData.setText(QtGui.QApplication.translate("MainWindow", "Exchange data", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exchangeData.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.a_clearPlots.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exportPlot.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.a_plotColorSettings.setText(QtGui.QApplication.translate("MainWindow", "Color settings", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadDeformation.setText(QtGui.QApplication.translate("MainWindow", "Load deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadDeformation.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadRadii.setText(QtGui.QApplication.translate("MainWindow", "Load radii", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadRadii.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.a_findTransition.setText(QtGui.QApplication.translate("MainWindow", "Find transition (ENSDF)", None, QtGui.QApplication.UnicodeUTF8))
        self.a_findTransition.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNME_executable.setText(QtGui.QApplication.translate("MainWindow", "NME executable", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNME_executable.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+M", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
