# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Wed Sep  4 17:06:34 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(550, 580, 381, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.txt_lastActions = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.txt_lastActions.setGeometry(QtCore.QRect(0, 0, 371, 151))
        self.txt_lastActions.setObjectName("txt_lastActions")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.optionsTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.optionsTabWidget.setGeometry(QtCore.QRect(550, 10, 381, 561))
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.iniTab = QtWidgets.QWidget()
        self.iniTab.setObjectName("iniTab")
        self.group_M = QtWidgets.QGroupBox(self.iniTab)
        self.group_M.setGeometry(QtCore.QRect(10, 230, 181, 301))
        self.group_M.setObjectName("group_M")
        self.lab_ZM = QtWidgets.QLabel(self.group_M)
        self.lab_ZM.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.lab_ZM.setObjectName("lab_ZM")
        self.lab_AM = QtWidgets.QLabel(self.group_M)
        self.lab_AM.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.lab_AM.setObjectName("lab_AM")
        self.lab_RM = QtWidgets.QLabel(self.group_M)
        self.lab_RM.setGeometry(QtCore.QRect(10, 90, 67, 31))
        self.lab_RM.setObjectName("lab_RM")
        self.lab_JM = QtWidgets.QLabel(self.group_M)
        self.lab_JM.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.lab_JM.setObjectName("lab_JM")
        self.lab_Beta2M = QtWidgets.QLabel(self.group_M)
        self.lab_Beta2M.setGeometry(QtCore.QRect(10, 180, 67, 31))
        self.lab_Beta2M.setObjectName("lab_Beta2M")
        self.lab_Beta4M = QtWidgets.QLabel(self.group_M)
        self.lab_Beta4M.setGeometry(QtCore.QRect(10, 210, 67, 31))
        self.lab_Beta4M.setObjectName("lab_Beta4M")
        self.lab_Beta6M = QtWidgets.QLabel(self.group_M)
        self.lab_Beta6M.setGeometry(QtCore.QRect(10, 236, 67, 31))
        self.lab_Beta6M.setObjectName("lab_Beta6M")
        self.lab_PiM = QtWidgets.QLabel(self.group_M)
        self.lab_PiM.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.lab_PiM.setObjectName("lab_PiM")
        self.sb_ZM = QtWidgets.QSpinBox(self.group_M)
        self.sb_ZM.setGeometry(QtCore.QRect(107, 30, 61, 27))
        self.sb_ZM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_ZM.setObjectName("sb_ZM")
        self.sb_AM = QtWidgets.QSpinBox(self.group_M)
        self.sb_AM.setGeometry(QtCore.QRect(107, 60, 61, 27))
        self.sb_AM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_AM.setMaximum(250)
        self.sb_AM.setObjectName("sb_AM")
        self.dsb_RM = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_RM.setGeometry(QtCore.QRect(90, 90, 81, 27))
        self.dsb_RM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_RM.setSingleStep(0.1)
        self.dsb_RM.setObjectName("dsb_RM")
        self.dsb_JM = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_JM.setGeometry(QtCore.QRect(100, 120, 71, 27))
        self.dsb_JM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_JM.setDecimals(1)
        self.dsb_JM.setSingleStep(0.5)
        self.dsb_JM.setObjectName("dsb_JM")
        self.cb_PiM = QtWidgets.QComboBox(self.group_M)
        self.cb_PiM.setGeometry(QtCore.QRect(110, 150, 61, 27))
        self.cb_PiM.setObjectName("cb_PiM")
        self.dsb_Beta2M = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_Beta2M.setGeometry(QtCore.QRect(100, 180, 69, 27))
        self.dsb_Beta2M.setDecimals(3)
        self.dsb_Beta2M.setMinimum(-1.0)
        self.dsb_Beta2M.setMaximum(1.0)
        self.dsb_Beta2M.setSingleStep(0.1)
        self.dsb_Beta2M.setObjectName("dsb_Beta2M")
        self.dsb_Beta4M = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_Beta4M.setGeometry(QtCore.QRect(100, 210, 69, 27))
        self.dsb_Beta4M.setDecimals(3)
        self.dsb_Beta4M.setMinimum(-1.0)
        self.dsb_Beta4M.setMaximum(1.0)
        self.dsb_Beta4M.setSingleStep(0.1)
        self.dsb_Beta4M.setObjectName("dsb_Beta4M")
        self.dsb_Beta6M = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_Beta6M.setGeometry(QtCore.QRect(100, 240, 69, 27))
        self.dsb_Beta6M.setDecimals(3)
        self.dsb_Beta6M.setMinimum(-1.0)
        self.dsb_Beta6M.setMaximum(1.0)
        self.dsb_Beta6M.setSingleStep(0.1)
        self.dsb_Beta6M.setObjectName("dsb_Beta6M")
        self.label_31 = QtWidgets.QLabel(self.group_M)
        self.label_31.setGeometry(QtCore.QRect(10, 270, 67, 21))
        self.label_31.setObjectName("label_31")
        self.dsb_motherEn = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_motherEn.setGeometry(QtCore.QRect(68, 270, 101, 27))
        self.dsb_motherEn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_motherEn.setMaximum(10000.0)
        self.dsb_motherEn.setSingleStep(1.0)
        self.dsb_motherEn.setProperty("value", 0.0)
        self.dsb_motherEn.setObjectName("dsb_motherEn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.iniTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 361, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.label_11.setObjectName("label_11")
        self.l_iniFilename = QtWidgets.QLabel(self.groupBox_3)
        self.l_iniFilename.setGeometry(QtCore.QRect(100, 51, 261, 20))
        self.l_iniFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_iniFilename.setObjectName("l_iniFilename")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_6.setObjectName("label_6")
        self.l_transitionName = QtWidgets.QLabel(self.groupBox_3)
        self.l_transitionName.setGeometry(QtCore.QRect(90, 30, 271, 16))
        self.l_transitionName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_transitionName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_transitionName.setObjectName("l_transitionName")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_16.setObjectName("label_16")
        self.b_chooseROBTDFile = QtWidgets.QPushButton(self.groupBox_3)
        self.b_chooseROBTDFile.setGeometry(QtCore.QRect(208, 80, 151, 27))
        self.b_chooseROBTDFile.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_chooseROBTDFile.setObjectName("b_chooseROBTDFile")
        self.group_M_2 = QtWidgets.QGroupBox(self.iniTab)
        self.group_M_2.setGeometry(QtCore.QRect(190, 230, 181, 301))
        self.group_M_2.setObjectName("group_M_2")
        self.lab_ZD = QtWidgets.QLabel(self.group_M_2)
        self.lab_ZD.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.lab_ZD.setObjectName("lab_ZD")
        self.lab_AD = QtWidgets.QLabel(self.group_M_2)
        self.lab_AD.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.lab_AD.setObjectName("lab_AD")
        self.lab_RD = QtWidgets.QLabel(self.group_M_2)
        self.lab_RD.setGeometry(QtCore.QRect(10, 90, 67, 31))
        self.lab_RD.setObjectName("lab_RD")
        self.lab_JD = QtWidgets.QLabel(self.group_M_2)
        self.lab_JD.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.lab_JD.setObjectName("lab_JD")
        self.lab_Beta2D = QtWidgets.QLabel(self.group_M_2)
        self.lab_Beta2D.setGeometry(QtCore.QRect(10, 180, 67, 31))
        self.lab_Beta2D.setObjectName("lab_Beta2D")
        self.lab_Beta4D = QtWidgets.QLabel(self.group_M_2)
        self.lab_Beta4D.setGeometry(QtCore.QRect(10, 210, 67, 31))
        self.lab_Beta4D.setObjectName("lab_Beta4D")
        self.lab_Beta6D = QtWidgets.QLabel(self.group_M_2)
        self.lab_Beta6D.setGeometry(QtCore.QRect(10, 236, 67, 31))
        self.lab_Beta6D.setObjectName("lab_Beta6D")
        self.lab_PiD = QtWidgets.QLabel(self.group_M_2)
        self.lab_PiD.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.lab_PiD.setObjectName("lab_PiD")
        self.sb_ZD = QtWidgets.QSpinBox(self.group_M_2)
        self.sb_ZD.setGeometry(QtCore.QRect(117, 30, 61, 27))
        self.sb_ZD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_ZD.setObjectName("sb_ZD")
        self.sb_AD = QtWidgets.QSpinBox(self.group_M_2)
        self.sb_AD.setGeometry(QtCore.QRect(117, 60, 61, 27))
        self.sb_AD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_AD.setMaximum(250)
        self.sb_AD.setObjectName("sb_AD")
        self.dsb_RD = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_RD.setGeometry(QtCore.QRect(100, 90, 81, 27))
        self.dsb_RD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_RD.setSingleStep(0.1)
        self.dsb_RD.setObjectName("dsb_RD")
        self.dsb_JD = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_JD.setGeometry(QtCore.QRect(110, 120, 71, 27))
        self.dsb_JD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_JD.setDecimals(1)
        self.dsb_JD.setSingleStep(0.5)
        self.dsb_JD.setObjectName("dsb_JD")
        self.cb_PiD = QtWidgets.QComboBox(self.group_M_2)
        self.cb_PiD.setGeometry(QtCore.QRect(120, 150, 61, 27))
        self.cb_PiD.setObjectName("cb_PiD")
        self.dsb_Beta2D = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta2D.setGeometry(QtCore.QRect(110, 180, 69, 27))
        self.dsb_Beta2D.setDecimals(3)
        self.dsb_Beta2D.setMinimum(-1.0)
        self.dsb_Beta2D.setMaximum(1.0)
        self.dsb_Beta2D.setSingleStep(0.1)
        self.dsb_Beta2D.setObjectName("dsb_Beta2D")
        self.dsb_Beta4D = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta4D.setGeometry(QtCore.QRect(110, 210, 69, 27))
        self.dsb_Beta4D.setDecimals(3)
        self.dsb_Beta4D.setMinimum(-1.0)
        self.dsb_Beta4D.setMaximum(1.0)
        self.dsb_Beta4D.setSingleStep(0.1)
        self.dsb_Beta4D.setObjectName("dsb_Beta4D")
        self.dsb_Beta6D = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta6D.setGeometry(QtCore.QRect(110, 240, 69, 27))
        self.dsb_Beta6D.setDecimals(3)
        self.dsb_Beta6D.setMinimum(-1.0)
        self.dsb_Beta6D.setMaximum(1.0)
        self.dsb_Beta6D.setSingleStep(0.1)
        self.dsb_Beta6D.setObjectName("dsb_Beta6D")
        self.label_33 = QtWidgets.QLabel(self.group_M_2)
        self.label_33.setGeometry(QtCore.QRect(10, 270, 67, 21))
        self.label_33.setObjectName("label_33")
        self.dsb_daughterEn = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_daughterEn.setGeometry(QtCore.QRect(70, 270, 111, 27))
        self.dsb_daughterEn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_daughterEn.setMaximum(10000.0)
        self.dsb_daughterEn.setObjectName("dsb_daughterEn")
        self.groupBox = QtWidgets.QGroupBox(self.iniTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 371, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 21, 21))
        self.label_4.setObjectName("label_4")
        self.cb_type = QtWidgets.QComboBox(self.groupBox)
        self.cb_type.setGeometry(QtCore.QRect(60, 60, 111, 27))
        self.cb_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cb_type.setFrame(True)
        self.cb_type.setObjectName("cb_type")
        self.cb_process = QtWidgets.QComboBox(self.groupBox)
        self.cb_process.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_process.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_process.setObjectName("cb_process")
        self.dsb_MixingRatio = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_MixingRatio.setGeometry(QtCore.QRect(280, 30, 81, 27))
        self.dsb_MixingRatio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_MixingRatio.setMaximum(100.0)
        self.dsb_MixingRatio.setObjectName("dsb_MixingRatio")
        self.dsb_Q = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_Q.setGeometry(QtCore.QRect(30, 90, 141, 27))
        self.dsb_Q.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_Q.setDecimals(4)
        self.dsb_Q.setMaximum(20000.0)
        self.dsb_Q.setObjectName("dsb_Q")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(180, 60, 61, 31))
        self.label_30.setObjectName("label_30")
        self.dsb_halflife = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_halflife.setGeometry(QtCore.QRect(240, 64, 121, 27))
        self.dsb_halflife.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_halflife.setDecimals(4)
        self.dsb_halflife.setMaximum(1000000000.0)
        self.dsb_halflife.setObjectName("dsb_halflife")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(180, 90, 67, 31))
        self.label_25.setObjectName("label_25")
        self.dsb_logft = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_logft.setGeometry(QtCore.QRect(270, 100, 91, 27))
        self.dsb_logft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_logft.setDecimals(4)
        self.dsb_logft.setMaximum(20.0)
        self.dsb_logft.setObjectName("dsb_logft")
        self.optionsTabWidget.addTab(self.iniTab, "")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.configTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 67, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 67, 31))
        self.label_27.setObjectName("label_27")
        self.dsb_gA = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gA.setGeometry(QtCore.QRect(80, 30, 81, 27))
        self.dsb_gA.setDecimals(4)
        self.dsb_gA.setProperty("value", 1.2723)
        self.dsb_gA.setObjectName("dsb_gA")
        self.dsb_gAeff = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gAeff.setGeometry(QtCore.QRect(80, 70, 81, 27))
        self.dsb_gAeff.setProperty("value", 1.0)
        self.dsb_gAeff.setObjectName("dsb_gAeff")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(180, 30, 31, 31))
        self.label_29.setObjectName("label_29")
        self.dsb_gM = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gM.setGeometry(QtCore.QRect(220, 30, 71, 27))
        self.dsb_gM.setDecimals(3)
        self.dsb_gM.setProperty("value", 4.706)
        self.dsb_gM.setObjectName("dsb_gM")
        self.dsb_gP = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gP.setGeometry(QtCore.QRect(220, 70, 71, 27))
        self.dsb_gP.setMinimum(-1000.0)
        self.dsb_gP.setMaximum(1000.0)
        self.dsb_gP.setProperty("value", 0.0)
        self.dsb_gP.setObjectName("dsb_gP")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(180, 70, 31, 31))
        self.label_28.setObjectName("label_28")
        self.b_resetNSO = QtWidgets.QPushButton(self.configTab)
        self.b_resetNSO.setGeometry(QtCore.QRect(20, 480, 141, 31))
        self.b_resetNSO.setObjectName("b_resetNSO")
        self.gb_ESP = QtWidgets.QGroupBox(self.configTab)
        self.gb_ESP.setEnabled(False)
        self.gb_ESP.setGeometry(QtCore.QRect(10, 170, 361, 311))
        self.gb_ESP.setObjectName("gb_ESP")
        self.cb_potential = QtWidgets.QComboBox(self.gb_ESP)
        self.cb_potential.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_potential.setObjectName("cb_potential")
        self.dsb_Xp = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_Xp.setGeometry(QtCore.QRect(280, 260, 69, 27))
        self.dsb_Xp.setProperty("value", 0.86)
        self.dsb_Xp.setObjectName("dsb_Xp")
        self.label_32 = QtWidgets.QLabel(self.gb_ESP)
        self.label_32.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_32.setObjectName("label_32")
        self.cb_reverseGhallagher = QtWidgets.QCheckBox(self.gb_ESP)
        self.cb_reverseGhallagher.setGeometry(QtCore.QRect(190, 70, 181, 22))
        self.cb_reverseGhallagher.setObjectName("cb_reverseGhallagher")
        self.dsb_V0Sn = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0Sn.setGeometry(QtCore.QRect(280, 180, 69, 27))
        self.dsb_V0Sn.setProperty("value", 7.2)
        self.dsb_V0Sn.setObjectName("dsb_V0Sn")
        self.label_37 = QtWidgets.QLabel(self.gb_ESP)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label_37.setObjectName("label_37")
        self.label_41 = QtWidgets.QLabel(self.gb_ESP)
        self.label_41.setGeometry(QtCore.QRect(180, 210, 101, 41))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.gb_ESP)
        self.label_42.setGeometry(QtCore.QRect(10, 210, 91, 41))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.gb_ESP)
        self.label_43.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.label_43.setObjectName("label_43")
        self.dsb_Xn = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_Xn.setGeometry(QtCore.QRect(100, 260, 69, 27))
        self.dsb_Xn.setProperty("value", 0.86)
        self.dsb_Xn.setObjectName("dsb_Xn")
        self.dsb_V0n = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0n.setGeometry(QtCore.QRect(100, 180, 69, 27))
        self.dsb_V0n.setProperty("value", 49.6)
        self.dsb_V0n.setObjectName("dsb_V0n")
        self.dsb_V0p = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0p.setGeometry(QtCore.QRect(100, 216, 69, 31))
        self.dsb_V0p.setProperty("value", 49.6)
        self.dsb_V0p.setObjectName("dsb_V0p")
        self.label_44 = QtWidgets.QLabel(self.gb_ESP)
        self.label_44.setGeometry(QtCore.QRect(10, 260, 81, 31))
        self.label_44.setObjectName("label_44")
        self.cb_overrideCoupling = QtWidgets.QCheckBox(self.gb_ESP)
        self.cb_overrideCoupling.setGeometry(QtCore.QRect(10, 70, 181, 22))
        self.cb_overrideCoupling.setObjectName("cb_overrideCoupling")
        self.dsb_V0Sp = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0Sp.setGeometry(QtCore.QRect(280, 220, 69, 27))
        self.dsb_V0Sp.setProperty("value", 7.2)
        self.dsb_V0Sp.setObjectName("dsb_V0Sp")
        self.cb_forceSpin = QtWidgets.QCheckBox(self.gb_ESP)
        self.cb_forceSpin.setGeometry(QtCore.QRect(10, 100, 121, 22))
        self.cb_forceSpin.setChecked(True)
        self.cb_forceSpin.setObjectName("cb_forceSpin")
        self.label_45 = QtWidgets.QLabel(self.gb_ESP)
        self.label_45.setGeometry(QtCore.QRect(180, 260, 71, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.gb_ESP)
        self.label_46.setGeometry(QtCore.QRect(180, 180, 101, 31))
        self.label_46.setObjectName("label_46")
        self.dsb_energyMargin = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_energyMargin.setGeometry(QtCore.QRect(120, 130, 91, 27))
        self.dsb_energyMargin.setDecimals(1)
        self.dsb_energyMargin.setMaximum(20.0)
        self.dsb_energyMargin.setProperty("value", 1.0)
        self.dsb_energyMargin.setObjectName("dsb_energyMargin")
        self.label_8 = QtWidgets.QLabel(self.gb_ESP)
        self.label_8.setGeometry(QtCore.QRect(220, 130, 21, 21))
        self.label_8.setObjectName("label_8")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.doubleSpinBox.setGeometry(QtCore.QRect(248, 130, 101, 27))
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.65)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_7 = QtWidgets.QLabel(self.configTab)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 67, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cb_nmeMethod = QtWidgets.QComboBox(self.configTab)
        self.cb_nmeMethod.setGeometry(QtCore.QRect(90, 120, 101, 27))
        self.cb_nmeMethod.setObjectName("cb_nmeMethod")
        self.optionsTabWidget.addTab(self.configTab, "")
        self.lab_logo = QtWidgets.QLabel(self.centralwidget)
        self.lab_logo.setGeometry(QtCore.QRect(10, 10, 331, 111))
        self.lab_logo.setAutoFillBackground(False)
        self.lab_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_logo.setText("")
        self.lab_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.lab_logo.setObjectName("lab_logo")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 130, 531, 611))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.bsgMainTab = QtWidgets.QWidget()
        self.bsgMainTab.setObjectName("bsgMainTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bsgMainTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 511, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gv_plotSpectrum = PlotWidget(self.horizontalLayoutWidget)
        self.gv_plotSpectrum.setObjectName("gv_plotSpectrum")
        self.horizontalLayout.addWidget(self.gv_plotSpectrum)
        self.b_runBSG = QtWidgets.QPushButton(self.bsgMainTab)
        self.b_runBSG.setGeometry(QtCore.QRect(420, 10, 101, 51))
        self.b_runBSG.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_runBSG.setCheckable(False)
        self.b_runBSG.setChecked(False)
        self.b_runBSG.setDefault(False)
        self.b_runBSG.setFlat(False)
        self.b_runBSG.setObjectName("b_runBSG")
        self.le_outputName = QtWidgets.QLineEdit(self.bsgMainTab)
        self.le_outputName.setGeometry(QtCore.QRect(10, 30, 101, 27))
        self.le_outputName.setObjectName("le_outputName")
        self.label_10 = QtWidgets.QLabel(self.bsgMainTab)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 111, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.rb_currentSettings = QtWidgets.QRadioButton(self.bsgMainTab)
        self.rb_currentSettings.setGeometry(QtCore.QRect(240, 0, 141, 22))
        self.rb_currentSettings.setChecked(True)
        self.rb_currentSettings.setObjectName("rb_currentSettings")
        self.rb_configFile = QtWidgets.QRadioButton(self.bsgMainTab)
        self.rb_configFile.setGeometry(QtCore.QRect(240, 30, 61, 22))
        self.rb_configFile.setObjectName("rb_configFile")
        self.label_5 = QtWidgets.QLabel(self.bsgMainTab)
        self.label_5.setGeometry(QtCore.QRect(130, 0, 111, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.b_chooseConfigFile = QtWidgets.QPushButton(self.bsgMainTab)
        self.b_chooseConfigFile.setGeometry(QtCore.QRect(300, 30, 91, 27))
        self.b_chooseConfigFile.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_chooseConfigFile.setObjectName("b_chooseConfigFile")
        self.mainTabWidget.addTab(self.bsgMainTab, "")
        self.bsgOptionsTab = QtWidgets.QWidget()
        self.bsgOptionsTab.setObjectName("bsgOptionsTab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.bsgOptionsTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 511, 551))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.b_enable_all = QtWidgets.QPushButton(self.groupBox_2)
        self.b_enable_all.setGeometry(QtCore.QRect(10, 520, 101, 31))
        self.b_enable_all.setObjectName("b_enable_all")
        self.b_disable_all = QtWidgets.QPushButton(self.groupBox_2)
        self.b_disable_all.setGeometry(QtCore.QRect(120, 520, 101, 31))
        self.b_disable_all.setObjectName("b_disable_all")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 420, 151, 80))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 290, 191, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.cb_relativistic = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_relativistic.setGeometry(QtCore.QRect(20, 170, 111, 22))
        self.cb_relativistic.setChecked(True)
        self.cb_relativistic.setObjectName("cb_relativistic")
        self.cb_isovector = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_isovector.setGeometry(QtCore.QRect(20, 90, 181, 22))
        self.cb_isovector.setChecked(True)
        self.cb_isovector.setObjectName("cb_isovector")
        self.cb_C_shape = QtWidgets.QComboBox(self.groupBox_6)
        self.cb_C_shape.setGeometry(QtCore.QRect(40, 60, 121, 27))
        self.cb_C_shape.setObjectName("cb_C_shape")
        self.cb_C = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_C.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.cb_C.setChecked(True)
        self.cb_C.setObjectName("cb_C")
        self.cb_coupled = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_coupled.setGeometry(QtCore.QRect(50, 110, 91, 31))
        self.cb_coupled.setObjectName("cb_coupled")
        self.cb_C_deformation = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_C_deformation.setGeometry(QtCore.QRect(20, 140, 121, 22))
        self.cb_C_deformation.setChecked(True)
        self.cb_C_deformation.setObjectName("cb_C_deformation")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 130, 191, 161))
        self.groupBox_7.setObjectName("groupBox_7")
        self.cb_efs_deformation = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_efs_deformation.setGeometry(QtCore.QRect(20, 120, 151, 31))
        self.cb_efs_deformation.setChecked(True)
        self.cb_efs_deformation.setObjectName("cb_efs_deformation")
        self.cb_efs = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_efs.setGeometry(QtCore.QRect(20, 30, 151, 22))
        self.cb_efs.setChecked(True)
        self.cb_efs.setObjectName("cb_efs")
        self.cb_shape = QtWidgets.QComboBox(self.groupBox_7)
        self.cb_shape.setGeometry(QtCore.QRect(40, 90, 121, 27))
        self.cb_shape.setObjectName("cb_shape")
        self.cb_ens = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_ens.setGeometry(QtCore.QRect(20, 60, 171, 22))
        self.cb_ens.setChecked(True)
        self.cb_ens.setObjectName("cb_ens")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 191, 131))
        self.groupBox_8.setObjectName("groupBox_8")
        self.cb_radiative = QtWidgets.QCheckBox(self.groupBox_8)
        self.cb_radiative.setGeometry(QtCore.QRect(20, 100, 181, 22))
        self.cb_radiative.setChecked(True)
        self.cb_radiative.setObjectName("cb_radiative")
        self.cb_fermi = QtWidgets.QCheckBox(self.groupBox_8)
        self.cb_fermi.setGeometry(QtCore.QRect(20, 61, 151, 31))
        self.cb_fermi.setChecked(True)
        self.cb_fermi.setObjectName("cb_fermi")
        self.cb_phasespace = QtWidgets.QCheckBox(self.groupBox_8)
        self.cb_phasespace.setGeometry(QtCore.QRect(20, 30, 131, 22))
        self.cb_phasespace.setChecked(True)
        self.cb_phasespace.setObjectName("cb_phasespace")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setGeometry(QtCore.QRect(240, 10, 201, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.cb_Q = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_Q.setGeometry(QtCore.QRect(20, 60, 141, 22))
        self.cb_Q.setChecked(True)
        self.cb_Q.setObjectName("cb_Q")
        self.cb_recoil = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_recoil.setGeometry(QtCore.QRect(20, 30, 141, 22))
        self.cb_recoil.setChecked(True)
        self.cb_recoil.setObjectName("cb_recoil")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setGeometry(QtCore.QRect(240, 100, 231, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.cb_mismatch = QtWidgets.QCheckBox(self.groupBox_10)
        self.cb_mismatch.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.cb_mismatch.setChecked(True)
        self.cb_mismatch.setObjectName("cb_mismatch")
        self.cb_screening = QtWidgets.QCheckBox(self.groupBox_10)
        self.cb_screening.setGeometry(QtCore.QRect(20, 30, 111, 22))
        self.cb_screening.setChecked(True)
        self.cb_screening.setObjectName("cb_screening")
        self.cb_exchange = QtWidgets.QCheckBox(self.groupBox_10)
        self.cb_exchange.setGeometry(QtCore.QRect(20, 60, 101, 22))
        self.cb_exchange.setChecked(True)
        self.cb_exchange.setObjectName("cb_exchange")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_11.setGeometry(QtCore.QRect(240, 330, 231, 181))
        self.groupBox_11.setObjectName("groupBox_11")
        self.sb_steps = QtWidgets.QSpinBox(self.groupBox_11)
        self.sb_steps.setEnabled(False)
        self.sb_steps.setGeometry(QtCore.QRect(90, 150, 111, 27))
        self.sb_steps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_steps.setMaximum(100000)
        self.sb_steps.setProperty("value", 1000)
        self.sb_steps.setObjectName("sb_steps")
        self.dsb_stepSize = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.dsb_stepSize.setEnabled(True)
        self.dsb_stepSize.setGeometry(QtCore.QRect(90, 110, 111, 27))
        self.dsb_stepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_stepSize.setMaximum(10000.0)
        self.dsb_stepSize.setProperty("value", 0.1)
        self.dsb_stepSize.setObjectName("dsb_stepSize")
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setGeometry(QtCore.QRect(20, 100, 41, 41))
        self.label_40.setObjectName("label_40")
        self.rb_stepSize = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_stepSize.setGeometry(QtCore.QRect(60, 110, 31, 22))
        self.rb_stepSize.setText("")
        self.rb_stepSize.setChecked(True)
        self.rb_stepSize.setObjectName("rb_stepSize")
        self.rb_steps = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_steps.setEnabled(True)
        self.rb_steps.setGeometry(QtCore.QRect(60, 150, 31, 22))
        self.rb_steps.setText("")
        self.rb_steps.setObjectName("rb_steps")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setGeometry(QtCore.QRect(20, 70, 41, 31))
        self.label_39.setObjectName("label_39")
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.label_38.setObjectName("label_38")
        self.dsb_end = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.dsb_end.setGeometry(QtCore.QRect(80, 70, 121, 27))
        self.dsb_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_end.setMaximum(20000.0)
        self.dsb_end.setObjectName("dsb_end")
        self.dsb_begin = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.dsb_begin.setGeometry(QtCore.QRect(80, 30, 121, 27))
        self.dsb_begin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_begin.setMaximum(20000.0)
        self.dsb_begin.setProperty("value", 0.0)
        self.dsb_begin.setObjectName("dsb_begin")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(240, 230, 281, 91))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_36 = QtWidgets.QLabel(self.groupBox_12)
        self.label_36.setGeometry(QtCore.QRect(20, 60, 41, 31))
        self.label_36.setObjectName("label_36")
        self.dsb_dAc = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.dsb_dAc.setGeometry(QtCore.QRect(200, 30, 69, 27))
        self.dsb_dAc.setDecimals(3)
        self.dsb_dAc.setMinimum(-100.0)
        self.dsb_dAc.setMaximum(100.0)
        self.dsb_dAc.setObjectName("dsb_dAc")
        self.dsb_lambda = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.dsb_lambda.setGeometry(QtCore.QRect(70, 60, 69, 27))
        self.dsb_lambda.setDecimals(3)
        self.dsb_lambda.setMinimum(-100.0)
        self.dsb_lambda.setMaximum(100.0)
        self.dsb_lambda.setObjectName("dsb_lambda")
        self.dsb_bAc = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.dsb_bAc.setGeometry(QtCore.QRect(70, 30, 69, 27))
        self.dsb_bAc.setDecimals(3)
        self.dsb_bAc.setMinimum(-100.0)
        self.dsb_bAc.setMaximum(100.0)
        self.dsb_bAc.setObjectName("dsb_bAc")
        self.label_34 = QtWidgets.QLabel(self.groupBox_12)
        self.label_34.setGeometry(QtCore.QRect(20, 30, 41, 21))
        self.label_34.setObjectName("label_34")
        self.cb_enforceNME = QtWidgets.QCheckBox(self.groupBox_12)
        self.cb_enforceNME.setGeometry(QtCore.QRect(150, 60, 121, 22))
        self.cb_enforceNME.setObjectName("cb_enforceNME")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(150, 20, 41, 41))
        self.label_35.setObjectName("label_35")
        self.b_resetSSO = QtWidgets.QPushButton(self.groupBox_2)
        self.b_resetSSO.setGeometry(QtCore.QRect(230, 520, 131, 31))
        self.b_resetSSO.setObjectName("b_resetSSO")
        self.mainTabWidget.addTab(self.bsgOptionsTab, "")
        self.l_RMP = QtWidgets.QLabel(self.centralwidget)
        self.l_RMP.setGeometry(QtCore.QRect(350, 10, 171, 31))
        self.l_RMP.setLineWidth(0)
        self.l_RMP.setOpenExternalLinks(True)
        self.l_RMP.setObjectName("l_RMP")
        self.l_RMP_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_RMP_2.setGeometry(QtCore.QRect(350, 40, 171, 41))
        self.l_RMP_2.setOpenExternalLinks(True)
        self.l_RMP_2.setObjectName("l_RMP_2")
        self.l_RMP_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_RMP_3.setGeometry(QtCore.QRect(350, 80, 171, 31))
        self.l_RMP_3.setOpenExternalLinks(True)
        self.l_RMP_3.setObjectName("l_RMP_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuOpen = QtWidgets.QMenu(self.menu_File)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menu_File)
        self.menuSave.setObjectName("menuSave")
        self.menuComponent_paths = QtWidgets.QMenu(self.menu_File)
        self.menuComponent_paths.setObjectName("menuComponent_paths")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlotting = QtWidgets.QMenu(self.menuBar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuDatabase = QtWidgets.QMenu(self.menuBar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuLinks = QtWidgets.QMenu(self.menuDatabase)
        self.menuLinks.setObjectName("menuLinks")
        MainWindow.setMenuBar(self.menuBar)
        self.a_exit = QtWidgets.QAction(MainWindow)
        self.a_exit.setObjectName("a_exit")
        self.a_loadIni = QtWidgets.QAction(MainWindow)
        self.a_loadIni.setObjectName("a_loadIni")
        self.a_loadConfig = QtWidgets.QAction(MainWindow)
        self.a_loadConfig.setObjectName("a_loadConfig")
        self.a_about = QtWidgets.QAction(MainWindow)
        self.a_about.setObjectName("a_about")
        self.a_feedback = QtWidgets.QAction(MainWindow)
        self.a_feedback.setObjectName("a_feedback")
        self.a_saveIni = QtWidgets.QAction(MainWindow)
        self.a_saveIni.setObjectName("a_saveIni")
        self.a_saveConfig = QtWidgets.QAction(MainWindow)
        self.a_saveConfig.setObjectName("a_saveConfig")
        self.a_new = QtWidgets.QAction(MainWindow)
        self.a_new.setObjectName("a_new")
        self.a_bsgExec = QtWidgets.QAction(MainWindow)
        self.a_bsgExec.setObjectName("a_bsgExec")
        self.a_exchangeData = QtWidgets.QAction(MainWindow)
        self.a_exchangeData.setObjectName("a_exchangeData")
        self.a_clearPlots = QtWidgets.QAction(MainWindow)
        self.a_clearPlots.setObjectName("a_clearPlots")
        self.a_exportPlot = QtWidgets.QAction(MainWindow)
        self.a_exportPlot.setObjectName("a_exportPlot")
        self.a_plotColorSettings = QtWidgets.QAction(MainWindow)
        self.a_plotColorSettings.setObjectName("a_plotColorSettings")
        self.a_loadDeformation = QtWidgets.QAction(MainWindow)
        self.a_loadDeformation.setObjectName("a_loadDeformation")
        self.a_loadRadii = QtWidgets.QAction(MainWindow)
        self.a_loadRadii.setObjectName("a_loadRadii")
        self.a_findTransition = QtWidgets.QAction(MainWindow)
        self.a_findTransition.setObjectName("a_findTransition")
        self.actionNME_executable = QtWidgets.QAction(MainWindow)
        self.actionNME_executable.setObjectName("actionNME_executable")
        self.actionENSDF = QtWidgets.QAction(MainWindow)
        self.actionENSDF.setObjectName("actionENSDF")
        self.a_FRDM2012 = QtWidgets.QAction(MainWindow)
        self.a_FRDM2012.setObjectName("a_FRDM2012")
        self.a_ChargeRadii = QtWidgets.QAction(MainWindow)
        self.a_ChargeRadii.setObjectName("a_ChargeRadii")
        self.a_ENSDF = QtWidgets.QAction(MainWindow)
        self.a_ENSDF.setObjectName("a_ENSDF")
        self.menuOpen.addAction(self.a_loadIni)
        self.menuOpen.addAction(self.a_loadConfig)
        self.menuSave.addAction(self.a_saveIni)
        self.menuSave.addAction(self.a_saveConfig)
        self.menuComponent_paths.addAction(self.a_bsgExec)
        self.menuComponent_paths.addAction(self.a_exchangeData)
        self.menu_File.addAction(self.a_new)
        self.menu_File.addAction(self.menuComponent_paths.menuAction())
        self.menu_File.addAction(self.menuOpen.menuAction())
        self.menu_File.addAction(self.menuSave.menuAction())
        self.menu_File.addAction(self.a_exit)
        self.menuHelp.addAction(self.a_feedback)
        self.menuHelp.addAction(self.a_about)
        self.menuPlotting.addAction(self.a_clearPlots)
        self.menuPlotting.addAction(self.a_exportPlot)
        self.menuLinks.addAction(self.a_ENSDF)
        self.menuLinks.addAction(self.a_FRDM2012)
        self.menuLinks.addAction(self.a_ChargeRadii)
        self.menuDatabase.addAction(self.a_loadDeformation)
        self.menuDatabase.addAction(self.a_loadRadii)
        self.menuDatabase.addAction(self.a_findTransition)
        self.menuDatabase.addAction(self.menuLinks.menuAction())
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())
        self.menuBar.addAction(self.menuPlotting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.optionsTabWidget.setCurrentIndex(0)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, -1))
        self.group_M.setTitle(QtWidgets.QApplication.translate("MainWindow", "Mother", None, -1))
        self.lab_ZM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.lab_ZM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.lab_ZM.setText(QtWidgets.QApplication.translate("MainWindow", "Z:", None, -1))
        self.lab_AM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.lab_AM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.lab_AM.setText(QtWidgets.QApplication.translate("MainWindow", "A:", None, -1))
        self.lab_RM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.lab_RM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.lab_RM.setText(QtWidgets.QApplication.translate("MainWindow", "Radius:", None, -1))
        self.lab_JM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.lab_JM.setText(QtWidgets.QApplication.translate("MainWindow", "Spin:", None, -1))
        self.lab_Beta2M.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Quadrupole deformation", None, -1))
        self.lab_Beta2M.setText(QtWidgets.QApplication.translate("MainWindow", "Beta2:", None, -1))
        self.lab_Beta4M.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Hexadecupole deformation", None, -1))
        self.lab_Beta4M.setText(QtWidgets.QApplication.translate("MainWindow", "Beta4:", None, -1))
        self.lab_Beta6M.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Beta6 deformation", None, -1))
        self.lab_Beta6M.setText(QtWidgets.QApplication.translate("MainWindow", "Beta6:", None, -1))
        self.lab_PiM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.lab_PiM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.lab_PiM.setText(QtWidgets.QApplication.translate("MainWindow", "Parity:", None, -1))
        self.sb_ZM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.sb_ZM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.sb_AM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.sb_AM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.dsb_RM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.dsb_RM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.dsb_RM.setSuffix(QtWidgets.QApplication.translate("MainWindow", " fm", None, -1))
        self.dsb_JM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.dsb_JM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.cb_PiM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.cb_PiM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.dsb_Beta2M.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Quadrupole deformation", None, -1))
        self.dsb_Beta4M.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Hexadecupole deformation", None, -1))
        self.dsb_Beta6M.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Beta6 deformation", None, -1))
        self.label_31.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Excitation energy of the parent level", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Energy:", None, -1))
        self.dsb_motherEn.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Excitation energy of the parent level", None, -1))
        self.dsb_motherEn.setSuffix(QtWidgets.QApplication.translate("MainWindow", " keV", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "General", None, -1))
        self.label_11.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Current ini file used for the transition", None, -1))
        self.label_11.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Current ini file used for the transition", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Current file:", None, -1))
        self.l_iniFilename.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Current ini file used for the transition", None, -1))
        self.l_iniFilename.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Current ini file used for the transition", None, -1))
        self.l_iniFilename.setText(QtWidgets.QApplication.translate("MainWindow", "(blank)", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Transition:", None, -1))
        self.l_transitionName.setText(QtWidgets.QApplication.translate("MainWindow", "(blank)", None, -1))
        self.label_16.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, -1))
        self.label_16.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "ROBTD File:", None, -1))
        self.b_chooseROBTDFile.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, -1))
        self.b_chooseROBTDFile.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space", None, -1))
        self.b_chooseROBTDFile.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.group_M_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Daughter", None, -1))
        self.lab_ZD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.lab_ZD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.lab_ZD.setText(QtWidgets.QApplication.translate("MainWindow", "Z:", None, -1))
        self.lab_AD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.lab_AD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.lab_AD.setText(QtWidgets.QApplication.translate("MainWindow", "A:", None, -1))
        self.lab_RD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.lab_RD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.lab_RD.setText(QtWidgets.QApplication.translate("MainWindow", "Radius:", None, -1))
        self.lab_JD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.lab_JD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.lab_JD.setText(QtWidgets.QApplication.translate("MainWindow", "Spin:", None, -1))
        self.lab_Beta2D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Quadrupole deformation", None, -1))
        self.lab_Beta2D.setText(QtWidgets.QApplication.translate("MainWindow", "Beta2:", None, -1))
        self.lab_Beta4D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Hexadecupole deformation", None, -1))
        self.lab_Beta4D.setText(QtWidgets.QApplication.translate("MainWindow", "Beta4:", None, -1))
        self.lab_Beta6D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Beta6 deformation", None, -1))
        self.lab_Beta6D.setText(QtWidgets.QApplication.translate("MainWindow", "Beta6:", None, -1))
        self.lab_PiD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.lab_PiD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.lab_PiD.setText(QtWidgets.QApplication.translate("MainWindow", "Parity:", None, -1))
        self.sb_ZD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.sb_ZD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Atomic number", None, -1))
        self.sb_AD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.sb_AD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Mass number", None, -1))
        self.dsb_RD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.dsb_RD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Charge radius", None, -1))
        self.dsb_RD.setSuffix(QtWidgets.QApplication.translate("MainWindow", " fm", None, -1))
        self.dsb_JD.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.dsb_JD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin in units of HBAR", None, -1))
        self.cb_PiD.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Parity of nuclear level", None, -1))
        self.dsb_Beta2D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Quadrupole deformation", None, -1))
        self.dsb_Beta4D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Hexadecupole deformation", None, -1))
        self.dsb_Beta6D.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Beta6 deformation", None, -1))
        self.label_33.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Excitation energy of the child level", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Energy:", None, -1))
        self.dsb_daughterEn.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Excitation energy of the child level", None, -1))
        self.dsb_daughterEn.setSuffix(QtWidgets.QApplication.translate("MainWindow", " keV", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Transition", None, -1))
        self.label.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Decay process", None, -1))
        self.label.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Decay process", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Process:", None, -1))
        self.label_2.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Decay type", None, -1))
        self.label_2.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Decay type", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Type:", None, -1))
        self.label_3.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, -1))
        self.label_3.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Mixing Ratio:", None, -1))
        self.label_4.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Q Value in keV", None, -1))
        self.label_4.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Q Value in keV", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Q: ", None, -1))
        self.cb_type.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Decay type", None, -1))
        self.cb_type.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Decay type", None, -1))
        self.cb_process.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Decay process", None, -1))
        self.cb_process.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Decay process", None, -1))
        self.dsb_MixingRatio.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, -1))
        self.dsb_MixingRatio.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Mixing ratio as gAM_GT/M_F", None, -1))
        self.dsb_Q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Q Value in keV", None, -1))
        self.dsb_Q.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Q Value in keV", None, -1))
        self.dsb_Q.setSuffix(QtWidgets.QApplication.translate("MainWindow", " keV", None, -1))
        self.label_30.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Partial Halflife", None, -1))
        self.label_30.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Partial Halflife", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Halflife:", None, -1))
        self.dsb_halflife.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Partial Halflife", None, -1))
        self.dsb_halflife.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Partial Halflife", None, -1))
        self.dsb_halflife.setSuffix(QtWidgets.QApplication.translate("MainWindow", " s", None, -1))
        self.label_25.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Log ft value", None, -1))
        self.label_25.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Log ft value", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Log ft:", None, -1))
        self.dsb_logft.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Log ft value", None, -1))
        self.dsb_logft.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Log ft value", None, -1))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.iniTab), QtWidgets.QApplication.translate("MainWindow", "Transition Info", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Constants", None, -1))
        self.label_26.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, -1))
        self.label_26.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "gA:", None, -1))
        self.label_27.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, -1))
        self.label_27.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "gA_eff:", None, -1))
        self.dsb_gA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, -1))
        self.dsb_gA.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Axial vector constant of the neutron", None, -1))
        self.dsb_gAeff.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, -1))
        self.dsb_gAeff.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Effective (quenched) value of gA", None, -1))
        self.label_29.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, -1))
        self.label_29.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "gM:", None, -1))
        self.dsb_gM.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, -1))
        self.dsb_gM.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)", None, -1))
        self.dsb_gP.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, -1))
        self.dsb_gP.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, -1))
        self.label_28.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, -1))
        self.label_28.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Induced pseudoscalar coupling", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "gP:", None, -1))
        self.b_resetNSO.setText(QtWidgets.QApplication.translate("MainWindow", "Reset to ...", None, -1))
        self.gb_ESP.setTitle(QtWidgets.QApplication.translate("MainWindow", "Extreme Single Particle", None, -1))
        self.cb_potential.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Choose the mean-field potential", None, -1))
        self.cb_potential.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose the mean-field potential", None, -1))
        self.label_32.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, -1))
        self.label_32.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "Energy Margin:", None, -1))
        self.cb_reverseGhallagher.setText(QtWidgets.QApplication.translate("MainWindow", "Reversed Ghallagher", None, -1))
        self.dsb_V0Sn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.dsb_V0Sn.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.label_37.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Choose the mean-field potential", None, -1))
        self.label_37.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose the mean-field potential", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Potential:", None, -1))
        self.label_41.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.label_41.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.label_41.setText(QtWidgets.QApplication.translate("MainWindow", "V0S protons:", None, -1))
        self.label_42.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.label_42.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.label_42.setText(QtWidgets.QApplication.translate("MainWindow", "V0 protons:", None, -1))
        self.label_43.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.label_43.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.label_43.setText(QtWidgets.QApplication.translate("MainWindow", "V0 neutrons:", None, -1))
        self.dsb_Xn.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, -1))
        self.dsb_Xn.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, -1))
        self.dsb_V0n.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.dsb_V0n.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.dsb_V0p.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.dsb_V0p.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Potential depth", None, -1))
        self.label_44.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, -1))
        self.label_44.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, -1))
        self.label_44.setText(QtWidgets.QApplication.translate("MainWindow", "X neutron:", None, -1))
        self.cb_overrideCoupling.setText(QtWidgets.QApplication.translate("MainWindow", "Override SP coupling", None, -1))
        self.dsb_V0Sp.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.dsb_V0Sp.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.cb_forceSpin.setText(QtWidgets.QApplication.translate("MainWindow", "Force Spin", None, -1))
        self.label_45.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, -1))
        self.label_45.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Proton-neutron asymmetry", None, -1))
        self.label_45.setText(QtWidgets.QApplication.translate("MainWindow", "X proton:", None, -1))
        self.label_46.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.label_46.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Spin-orbit strength", None, -1))
        self.label_46.setText(QtWidgets.QApplication.translate("MainWindow", "V0S neutrons:", None, -1))
        self.dsb_energyMargin.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, -1))
        self.dsb_energyMargin.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity", None, -1))
        self.dsb_energyMargin.setSuffix(QtWidgets.QApplication.translate("MainWindow", " MeV", None, -1))
        self.label_8.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Surface thickness of the Woods-Saxon potential", None, -1))
        self.label_8.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Surface thickness of the Woods-Saxon potential", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "a:", None, -1))
        self.doubleSpinBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Surface thickness of the Woods-Saxon potential", None, -1))
        self.doubleSpinBox.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Surface thickness of the Woods-Saxon potential", None, -1))
        self.doubleSpinBox.setSuffix(QtWidgets.QApplication.translate("MainWindow", " fm", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Method:", None, -1))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.configTab), QtWidgets.QApplication.translate("MainWindow", "Nuclear Structure Options", None, -1))
        self.b_runBSG.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Run the spectrum shape generator", None, -1))
        self.b_runBSG.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Run the spectrum shape generator", None, -1))
        self.b_runBSG.setText(QtWidgets.QApplication.translate("MainWindow", "Run!", None, -1))
        self.le_outputName.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose the output name of all files generated (omit extension)", None, -1))
        self.le_outputName.setText(QtWidgets.QApplication.translate("MainWindow", "output", None, -1))
        self.label_10.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose the output name of all files generated (omit extension)", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Output name:", None, -1))
        self.rb_currentSettings.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use the Spectral Shape & Nuclear Structure options as currently specified in the GUI", None, -1))
        self.rb_currentSettings.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Use the Spectral Shape & Nuclear Structure options as currently specified in the GUI", None, -1))
        self.rb_currentSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Current settings", None, -1))
        self.rb_configFile.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use the Spectrum Shape and Nuclear Structure Options as specified in an external config file", None, -1))
        self.rb_configFile.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Use the Spectrum Shape and Nuclear Structure Options as specified in an external config file", None, -1))
        self.rb_configFile.setText(QtWidgets.QApplication.translate("MainWindow", "File:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Configuration:", None, -1))
        self.b_chooseConfigFile.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgMainTab), QtWidgets.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, -1))
        self.b_enable_all.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Enable all corrections", None, -1))
        self.b_enable_all.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Enable all corrections", None, -1))
        self.b_enable_all.setText(QtWidgets.QApplication.translate("MainWindow", "Enable All", None, -1))
        self.b_disable_all.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Disable all corrections", None, -1))
        self.b_disable_all.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Disable all corrections", None, -1))
        self.b_disable_all.setText(QtWidgets.QApplication.translate("MainWindow", "Disable All", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Nuclear Structure", None, -1))
        self.cb_relativistic.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Take into account relativistic (O(v/c) ~ 1/(MR)) terms in the Shape factor", None, -1))
        self.cb_relativistic.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Take into account relativistic (O(v/c) ~ 1/(MR)) terms in the Shape factor", None, -1))
        self.cb_relativistic.setText(QtWidgets.QApplication.translate("MainWindow", "Relativistic", None, -1))
        self.cb_isovector.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Correction due to CVC breakdown due to isospin symmetry breaking", None, -1))
        self.cb_isovector.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Correction due to CVC breakdown due to isospin symmetry breaking", None, -1))
        self.cb_isovector.setText(QtWidgets.QApplication.translate("MainWindow", "Isovector Correction", None, -1))
        self.cb_C_shape.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Shape of the nuclear charge distribution", None, -1))
        self.cb_C_shape.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Shape of the nuclear charge distribution", None, -1))
        self.cb_C.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Nuclear shape factor, taking into account the convolution of leptonic and nuclear wave functions and induced currents", None, -1))
        self.cb_C.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Nuclear shape factor, taking into account the convolution of leptonic and nuclear wave functions and induced currents", None, -1))
        self.cb_C.setText(QtWidgets.QApplication.translate("MainWindow", "Shape factor", None, -1))
        self.cb_coupled.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel.", None, -1))
        self.cb_coupled.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel.", None, -1))
        self.cb_coupled.setText(QtWidgets.QApplication.translate("MainWindow", "Coupled", None, -1))
        self.cb_C_deformation.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Take into account nuclear deformation in the convolution of lepton and nuclear wave functions", None, -1))
        self.cb_C_deformation.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Take into account nuclear deformation in the convolution of lepton and nuclear wave functions", None, -1))
        self.cb_C_deformation.setText(QtWidgets.QApplication.translate("MainWindow", "Deformation", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "Electrostatic", None, -1))
        self.cb_efs_deformation.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Additional correction factor to take into account nuclear deformation on the final state electric interaction", None, -1))
        self.cb_efs_deformation.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Additional correction factor to take into account nuclear deformation on the final state electric interaction", None, -1))
        self.cb_efs_deformation.setText(QtWidgets.QApplication.translate("MainWindow", "ES Deformation", None, -1))
        self.cb_efs.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Correction factor to the Fermi function to take into account the finite size of the nuclear charge distribution. Approximated as a uniformly charged sphere", None, -1))
        self.cb_efs.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Correction factor to the Fermi function to take into account the finite size of the nuclear charge distribution. Approximated as a uniformly charged sphere", None, -1))
        self.cb_efs.setText(QtWidgets.QApplication.translate("MainWindow", "ES Finite Size", None, -1))
        self.cb_shape.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Choose nuclear shape for higher-order correction", None, -1))
        self.cb_shape.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose nuclear shape for higher-order correction", None, -1))
        self.cb_ens.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Higher-order correction to the ES Finite size above, by going beyond a uniformly charged sphere to a Fermi or Modified Gaussian shape.", None, -1))
        self.cb_ens.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Higher-order correction to the ES Finite size above, by going beyond a uniformly charged sphere to a Fermi or Modified Gaussian shape.", None, -1))
        self.cb_ens.setText(QtWidgets.QApplication.translate("MainWindow", "ES Nuclear Shape", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "Basic", None, -1))
        self.cb_radiative.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Additional QED & Weak interaction radiative corrections, through (virtual) photon, gamma and W exchange", None, -1))
        self.cb_radiative.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Additional QED & Weak interaction radiative corrections, through (virtual) photon, gamma and W exchange", None, -1))
        self.cb_radiative.setText(QtWidgets.QApplication.translate("MainWindow", "Radiative corrections", None, -1))
        self.cb_fermi.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Final state interaction between outgoing lepton and final nuclear charge density, approximated as a point charge", None, -1))
        self.cb_fermi.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Final state interaction between outgoing lepton and final nuclear charge density, approximated as a point charge", None, -1))
        self.cb_fermi.setText(QtWidgets.QApplication.translate("MainWindow", "Fermi Function", None, -1))
        self.cb_phasespace.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The kinematical phase space factor, pW(W0-W)^2", None, -1))
        self.cb_phasespace.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "The kinematical phase space factor, pW(W0-W)^2", None, -1))
        self.cb_phasespace.setText(QtWidgets.QApplication.translate("MainWindow", "Phase Space", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("MainWindow", "Kinematic", None, -1))
        self.cb_Q.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Correction term due to the movement of the Coulomb potential in case the nucleus is not infinitely massive", None, -1))
        self.cb_Q.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Correction term due to the movement of the Coulomb potential in case the nucleus is not infinitely massive", None, -1))
        self.cb_Q.setText(QtWidgets.QApplication.translate("MainWindow", "Coulomb Recoil", None, -1))
        self.cb_recoil.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Kinematical correction factor to take into account the finite nuclear mass.", None, -1))
        self.cb_recoil.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Kinematical correction factor to take into account the finite nuclear mass.", None, -1))
        self.cb_recoil.setText(QtWidgets.QApplication.translate("MainWindow", "Nuclear Recoil", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("MainWindow", "Atomic", None, -1))
        self.cb_mismatch.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Average treatment of the decrease in phase space due to atomic excitations.", None, -1))
        self.cb_mismatch.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Average treatment of the decrease in phase space due to atomic excitations.", None, -1))
        self.cb_mismatch.setText(QtWidgets.QApplication.translate("MainWindow", "Mismatch", None, -1))
        self.cb_screening.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Screening of the nuclear charge by atomic electrons", None, -1))
        self.cb_screening.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Screening of the nuclear charge by atomic electrons", None, -1))
        self.cb_screening.setText(QtWidgets.QApplication.translate("MainWindow", "Screening", None, -1))
        self.cb_exchange.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Atomic exchange process, decay directly into bound state.", None, -1))
        self.cb_exchange.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Atomic exchange process, decay directly into bound state.", None, -1))
        self.cb_exchange.setText(QtWidgets.QApplication.translate("MainWindow", "Exchange", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("MainWindow", "Limits", None, -1))
        self.sb_steps.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Number of steps", None, -1))
        self.sb_steps.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Number of steps", None, -1))
        self.sb_steps.setSuffix(QtWidgets.QApplication.translate("MainWindow", " steps", None, -1))
        self.dsb_stepSize.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Step size in keV", None, -1))
        self.dsb_stepSize.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Step size in keV", None, -1))
        self.dsb_stepSize.setSuffix(QtWidgets.QApplication.translate("MainWindow", " keV", None, -1))
        self.label_40.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Step size or number of steps for which to calculate the spectrum", None, -1))
        self.label_40.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Step size or number of steps for which to calculate the spectrum", None, -1))
        self.label_40.setText(QtWidgets.QApplication.translate("MainWindow", "Step:", None, -1))
        self.label_39.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, -1))
        self.label_39.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, -1))
        self.label_39.setText(QtWidgets.QApplication.translate("MainWindow", "End:", None, -1))
        self.label_38.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Starting energy from where to calculate", None, -1))
        self.label_38.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Starting energy from where to calculate", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "Begin:", None, -1))
        self.dsb_end.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, -1))
        self.dsb_end.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint).", None, -1))
        self.dsb_end.setSuffix(QtWidgets.QApplication.translate("MainWindow", " keV", None, -1))
        self.dsb_begin.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Starting energy from where to calculate", "Starting energy from where to calculate", -1))
        self.dsb_begin.setSuffix(QtWidgets.QApplication.translate("MainWindow", " keV", None, -1))
        self.groupBox_12.setTitle(QtWidgets.QApplication.translate("MainWindow", "Matrix Elements", None, -1))
        self.label_36.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Related to induced pseudoscalar in Holstein\'s formalism", None, -1))
        self.label_36.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Related to induced pseudoscalar in Holstein\'s formalism", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Λ:", None, -1))
        self.label_34.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Weak magnetism, in Holstein\'s formalism", None, -1))
        self.label_34.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Weak magnetism, in Holstein\'s formalism", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "b/Ac:", None, -1))
        self.cb_enforceNME.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Choose whether to enforce the values for b/Ac, d/Ac and Lambda written here, or leave it to the NME library", None, -1))
        self.cb_enforceNME.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Choose whether to enforce the values for b/Ac, d/Ac and Lambda written here, or leave it to the NME library", None, -1))
        self.cb_enforceNME.setText(QtWidgets.QApplication.translate("MainWindow", "Enforce", None, -1))
        self.label_35.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Induced tensor, as in Holstein\'s formalism", None, -1))
        self.label_35.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Induced tensor, as in Holstein\'s formalism", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "d/Ac:", None, -1))
        self.b_resetSSO.setText(QtWidgets.QApplication.translate("MainWindow", "Reset to ...", None, -1))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgOptionsTab), QtWidgets.QApplication.translate("MainWindow", "Spectral Shape Options", None, -1))
        self.l_RMP.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.90.015008\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to Rev. Mod. Phys.</span></a></p></body></html>", None, -1))
        self.l_RMP_2.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://arxiv.org/abs/1803.00525\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to BSG paper</span></a></p></body></html>", None, -1))
        self.l_RMP_3.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/leenderthayen/BSG\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to Github</span></a></p></body></html>", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.menuOpen.setTitle(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.menuSave.setTitle(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.menuComponent_paths.setTitle(QtWidgets.QApplication.translate("MainWindow", "Component paths", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuPlotting.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Plotting", None, -1))
        self.menuDatabase.setTitle(QtWidgets.QApplication.translate("MainWindow", "&Database", None, -1))
        self.menuLinks.setTitle(QtWidgets.QApplication.translate("MainWindow", "Links", None, -1))
        self.a_exit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.a_exit.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.a_loadIni.setText(QtWidgets.QApplication.translate("MainWindow", "Ini file", None, -1))
        self.a_loadIni.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+I", None, -1))
        self.a_loadConfig.setText(QtWidgets.QApplication.translate("MainWindow", "Config file", None, -1))
        self.a_loadConfig.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+C", None, -1))
        self.a_about.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.a_feedback.setText(QtWidgets.QApplication.translate("MainWindow", "Submit feedback", None, -1))
        self.a_saveIni.setText(QtWidgets.QApplication.translate("MainWindow", "Ini file", None, -1))
        self.a_saveIni.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, -1))
        self.a_saveConfig.setText(QtWidgets.QApplication.translate("MainWindow", "Config file", None, -1))
        self.a_saveConfig.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, -1))
        self.a_new.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.a_new.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.a_bsgExec.setText(QtWidgets.QApplication.translate("MainWindow", "BSG executable", None, -1))
        self.a_bsgExec.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+B", None, -1))
        self.a_exchangeData.setText(QtWidgets.QApplication.translate("MainWindow", "Exchange data", None, -1))
        self.a_exchangeData.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.a_clearPlots.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.a_exportPlot.setText(QtWidgets.QApplication.translate("MainWindow", "Export", None, -1))
        self.a_plotColorSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Color settings", None, -1))
        self.a_loadDeformation.setText(QtWidgets.QApplication.translate("MainWindow", "Load deformation", None, -1))
        self.a_loadDeformation.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+D", None, -1))
        self.a_loadRadii.setText(QtWidgets.QApplication.translate("MainWindow", "Load radii", None, -1))
        self.a_loadRadii.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+R", None, -1))
        self.a_findTransition.setText(QtWidgets.QApplication.translate("MainWindow", "Find transition (ENSDF)", None, -1))
        self.a_findTransition.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+F", None, -1))
        self.actionNME_executable.setText(QtWidgets.QApplication.translate("MainWindow", "NME executable", None, -1))
        self.actionNME_executable.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+M", None, -1))
        self.actionENSDF.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><a href=\"https://www.nndc.bnl.gov/ensarchivals/\"><span style=\" text-decoration: underline; color:#ffffff;\">ENSDF</span></a></p></body></html>", None, -1))
        self.a_FRDM2012.setText(QtWidgets.QApplication.translate("MainWindow", "FRDM2012", None, -1))
        self.a_ChargeRadii.setText(QtWidgets.QApplication.translate("MainWindow", "ChargeRadii", None, -1))
        self.a_ENSDF.setText(QtWidgets.QApplication.translate("MainWindow", "ENSDF", None, -1))

from pyqtgraph import PlotWidget
