# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(550, 580, 381, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.txt_lastActions = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.txt_lastActions.setGeometry(QtCore.QRect(0, 0, 371, 151))
        self.txt_lastActions.setObjectName("txt_lastActions")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.optionsTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.optionsTabWidget.setGeometry(QtCore.QRect(550, 10, 381, 561))
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.iniTab = QtWidgets.QWidget()
        self.iniTab.setObjectName("iniTab")
        self.group_M = QtWidgets.QGroupBox(self.iniTab)
        self.group_M.setGeometry(QtCore.QRect(10, 230, 181, 301))
        self.group_M.setObjectName("group_M")
        self.lab_ZM = QtWidgets.QLabel(self.group_M)
        self.lab_ZM.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.lab_ZM.setObjectName("lab_ZM")
        self.lab_AM = QtWidgets.QLabel(self.group_M)
        self.lab_AM.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.lab_AM.setObjectName("lab_AM")
        self.lab_RM = QtWidgets.QLabel(self.group_M)
        self.lab_RM.setGeometry(QtCore.QRect(10, 90, 67, 31))
        self.lab_RM.setObjectName("lab_RM")
        self.lab_JM = QtWidgets.QLabel(self.group_M)
        self.lab_JM.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.lab_JM.setObjectName("lab_JM")
        self.lab_Beta2M = QtWidgets.QLabel(self.group_M)
        self.lab_Beta2M.setGeometry(QtCore.QRect(10, 180, 67, 31))
        self.lab_Beta2M.setObjectName("lab_Beta2M")
        self.lab_Beta4M = QtWidgets.QLabel(self.group_M)
        self.lab_Beta4M.setGeometry(QtCore.QRect(10, 210, 67, 31))
        self.lab_Beta4M.setObjectName("lab_Beta4M")
        self.lab_Beta6M = QtWidgets.QLabel(self.group_M)
        self.lab_Beta6M.setGeometry(QtCore.QRect(10, 236, 67, 31))
        self.lab_Beta6M.setObjectName("lab_Beta6M")
        self.lab_PiM = QtWidgets.QLabel(self.group_M)
        self.lab_PiM.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.lab_PiM.setObjectName("lab_PiM")
        self.sb_ZM = QtWidgets.QSpinBox(self.group_M)
        self.sb_ZM.setGeometry(QtCore.QRect(107, 30, 61, 27))
        self.sb_ZM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_ZM.setObjectName("sb_ZM")
        self.sb_AM = QtWidgets.QSpinBox(self.group_M)
        self.sb_AM.setGeometry(QtCore.QRect(107, 60, 61, 27))
        self.sb_AM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_AM.setMaximum(250)
        self.sb_AM.setObjectName("sb_AM")
        self.dsb_RM = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_RM.setGeometry(QtCore.QRect(90, 90, 81, 27))
        self.dsb_RM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_RM.setSingleStep(0.1)
        self.dsb_RM.setObjectName("dsb_RM")
        self.dsb_JM = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_JM.setGeometry(QtCore.QRect(100, 120, 71, 27))
        self.dsb_JM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_JM.setDecimals(1)
        self.dsb_JM.setSingleStep(0.5)
        self.dsb_JM.setObjectName("dsb_JM")
        self.cb_PiM = QtWidgets.QComboBox(self.group_M)
        self.cb_PiM.setGeometry(QtCore.QRect(110, 150, 61, 27))
        self.cb_PiM.setObjectName("cb_PiM")
        self.dsb_Beta2M = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_Beta2M.setGeometry(QtCore.QRect(100, 180, 69, 27))
        self.dsb_Beta2M.setDecimals(3)
        self.dsb_Beta2M.setMinimum(-1.0)
        self.dsb_Beta2M.setMaximum(1.0)
        self.dsb_Beta2M.setSingleStep(0.1)
        self.dsb_Beta2M.setObjectName("dsb_Beta2M")
        self.dsb_Beta4M = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_Beta4M.setGeometry(QtCore.QRect(100, 210, 69, 27))
        self.dsb_Beta4M.setDecimals(3)
        self.dsb_Beta4M.setMinimum(-1.0)
        self.dsb_Beta4M.setMaximum(1.0)
        self.dsb_Beta4M.setSingleStep(0.1)
        self.dsb_Beta4M.setObjectName("dsb_Beta4M")
        self.dsb_Beta6M = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_Beta6M.setGeometry(QtCore.QRect(100, 240, 69, 27))
        self.dsb_Beta6M.setDecimals(3)
        self.dsb_Beta6M.setMinimum(-1.0)
        self.dsb_Beta6M.setMaximum(1.0)
        self.dsb_Beta6M.setSingleStep(0.1)
        self.dsb_Beta6M.setObjectName("dsb_Beta6M")
        self.label_31 = QtWidgets.QLabel(self.group_M)
        self.label_31.setGeometry(QtCore.QRect(10, 270, 67, 21))
        self.label_31.setObjectName("label_31")
        self.dsb_motherEn = QtWidgets.QDoubleSpinBox(self.group_M)
        self.dsb_motherEn.setGeometry(QtCore.QRect(68, 270, 101, 27))
        self.dsb_motherEn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_motherEn.setMaximum(10000.0)
        self.dsb_motherEn.setSingleStep(1.0)
        self.dsb_motherEn.setProperty("value", 0.0)
        self.dsb_motherEn.setObjectName("dsb_motherEn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.iniTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 361, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 91, 31))
        self.label_11.setObjectName("label_11")
        self.l_iniFilename = QtWidgets.QLabel(self.groupBox_3)
        self.l_iniFilename.setGeometry(QtCore.QRect(100, 51, 261, 20))
        self.l_iniFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_iniFilename.setObjectName("l_iniFilename")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_6.setObjectName("label_6")
        self.l_transitionName = QtWidgets.QLabel(self.groupBox_3)
        self.l_transitionName.setGeometry(QtCore.QRect(90, 30, 271, 16))
        self.l_transitionName.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_transitionName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_transitionName.setObjectName("l_transitionName")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.label_16.setObjectName("label_16")
        self.b_chooseROBTDFile = QtWidgets.QPushButton(self.groupBox_3)
        self.b_chooseROBTDFile.setGeometry(QtCore.QRect(208, 80, 151, 27))
        self.b_chooseROBTDFile.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.b_chooseROBTDFile.setObjectName("b_chooseROBTDFile")
        self.group_M_2 = QtWidgets.QGroupBox(self.iniTab)
        self.group_M_2.setGeometry(QtCore.QRect(190, 230, 181, 301))
        self.group_M_2.setObjectName("group_M_2")
        self.lab_ZD = QtWidgets.QLabel(self.group_M_2)
        self.lab_ZD.setGeometry(QtCore.QRect(10, 30, 61, 31))
        self.lab_ZD.setObjectName("lab_ZD")
        self.lab_AD = QtWidgets.QLabel(self.group_M_2)
        self.lab_AD.setGeometry(QtCore.QRect(10, 60, 67, 31))
        self.lab_AD.setObjectName("lab_AD")
        self.lab_RD = QtWidgets.QLabel(self.group_M_2)
        self.lab_RD.setGeometry(QtCore.QRect(10, 90, 67, 31))
        self.lab_RD.setObjectName("lab_RD")
        self.lab_JD = QtWidgets.QLabel(self.group_M_2)
        self.lab_JD.setGeometry(QtCore.QRect(10, 120, 67, 31))
        self.lab_JD.setObjectName("lab_JD")
        self.lab_Beta2D = QtWidgets.QLabel(self.group_M_2)
        self.lab_Beta2D.setGeometry(QtCore.QRect(10, 180, 67, 31))
        self.lab_Beta2D.setObjectName("lab_Beta2D")
        self.lab_Beta4D = QtWidgets.QLabel(self.group_M_2)
        self.lab_Beta4D.setGeometry(QtCore.QRect(10, 210, 67, 31))
        self.lab_Beta4D.setObjectName("lab_Beta4D")
        self.lab_Beta6D = QtWidgets.QLabel(self.group_M_2)
        self.lab_Beta6D.setGeometry(QtCore.QRect(10, 236, 67, 31))
        self.lab_Beta6D.setObjectName("lab_Beta6D")
        self.lab_PiD = QtWidgets.QLabel(self.group_M_2)
        self.lab_PiD.setGeometry(QtCore.QRect(10, 150, 67, 31))
        self.lab_PiD.setObjectName("lab_PiD")
        self.sb_ZD = QtWidgets.QSpinBox(self.group_M_2)
        self.sb_ZD.setGeometry(QtCore.QRect(117, 30, 61, 27))
        self.sb_ZD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_ZD.setObjectName("sb_ZD")
        self.sb_AD = QtWidgets.QSpinBox(self.group_M_2)
        self.sb_AD.setGeometry(QtCore.QRect(117, 60, 61, 27))
        self.sb_AD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_AD.setMaximum(250)
        self.sb_AD.setObjectName("sb_AD")
        self.dsb_RD = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_RD.setGeometry(QtCore.QRect(100, 90, 81, 27))
        self.dsb_RD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_RD.setSingleStep(0.1)
        self.dsb_RD.setObjectName("dsb_RD")
        self.dsb_JD = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_JD.setGeometry(QtCore.QRect(110, 120, 71, 27))
        self.dsb_JD.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_JD.setDecimals(1)
        self.dsb_JD.setSingleStep(0.5)
        self.dsb_JD.setObjectName("dsb_JD")
        self.cb_PiD = QtWidgets.QComboBox(self.group_M_2)
        self.cb_PiD.setGeometry(QtCore.QRect(120, 150, 61, 27))
        self.cb_PiD.setObjectName("cb_PiD")
        self.dsb_Beta2D = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta2D.setGeometry(QtCore.QRect(110, 180, 69, 27))
        self.dsb_Beta2D.setDecimals(3)
        self.dsb_Beta2D.setMinimum(-1.0)
        self.dsb_Beta2D.setMaximum(1.0)
        self.dsb_Beta2D.setSingleStep(0.1)
        self.dsb_Beta2D.setObjectName("dsb_Beta2D")
        self.dsb_Beta4D = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta4D.setGeometry(QtCore.QRect(110, 210, 69, 27))
        self.dsb_Beta4D.setDecimals(3)
        self.dsb_Beta4D.setMinimum(-1.0)
        self.dsb_Beta4D.setMaximum(1.0)
        self.dsb_Beta4D.setSingleStep(0.1)
        self.dsb_Beta4D.setObjectName("dsb_Beta4D")
        self.dsb_Beta6D = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta6D.setGeometry(QtCore.QRect(110, 240, 69, 27))
        self.dsb_Beta6D.setDecimals(3)
        self.dsb_Beta6D.setMinimum(-1.0)
        self.dsb_Beta6D.setMaximum(1.0)
        self.dsb_Beta6D.setSingleStep(0.1)
        self.dsb_Beta6D.setObjectName("dsb_Beta6D")
        self.label_33 = QtWidgets.QLabel(self.group_M_2)
        self.label_33.setGeometry(QtCore.QRect(10, 270, 67, 21))
        self.label_33.setObjectName("label_33")
        self.dsb_daughterEn = QtWidgets.QDoubleSpinBox(self.group_M_2)
        self.dsb_daughterEn.setGeometry(QtCore.QRect(70, 270, 111, 27))
        self.dsb_daughterEn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_daughterEn.setMaximum(10000.0)
        self.dsb_daughterEn.setObjectName("dsb_daughterEn")
        self.groupBox = QtWidgets.QGroupBox(self.iniTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 371, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 21, 21))
        self.label_4.setObjectName("label_4")
        self.cb_type = QtWidgets.QComboBox(self.groupBox)
        self.cb_type.setGeometry(QtCore.QRect(60, 60, 111, 27))
        self.cb_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_type.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cb_type.setFrame(True)
        self.cb_type.setObjectName("cb_type")
        self.cb_process = QtWidgets.QComboBox(self.groupBox)
        self.cb_process.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_process.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cb_process.setObjectName("cb_process")
        self.dsb_MixingRatio = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_MixingRatio.setGeometry(QtCore.QRect(280, 30, 81, 27))
        self.dsb_MixingRatio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_MixingRatio.setMaximum(100.0)
        self.dsb_MixingRatio.setObjectName("dsb_MixingRatio")
        self.dsb_Q = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_Q.setGeometry(QtCore.QRect(30, 90, 141, 27))
        self.dsb_Q.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_Q.setDecimals(4)
        self.dsb_Q.setMaximum(20000.0)
        self.dsb_Q.setObjectName("dsb_Q")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(180, 60, 61, 31))
        self.label_30.setObjectName("label_30")
        self.dsb_halflife = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_halflife.setGeometry(QtCore.QRect(240, 64, 121, 27))
        self.dsb_halflife.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_halflife.setDecimals(4)
        self.dsb_halflife.setMaximum(1000000000.0)
        self.dsb_halflife.setObjectName("dsb_halflife")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(180, 90, 67, 31))
        self.label_25.setObjectName("label_25")
        self.dsb_logft = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.dsb_logft.setGeometry(QtCore.QRect(270, 100, 91, 27))
        self.dsb_logft.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_logft.setDecimals(4)
        self.dsb_logft.setMaximum(20.0)
        self.dsb_logft.setObjectName("dsb_logft")
        self.optionsTabWidget.addTab(self.iniTab, "")
        self.configTab = QtWidgets.QWidget()
        self.configTab.setObjectName("configTab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.configTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 351, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 67, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 67, 31))
        self.label_27.setObjectName("label_27")
        self.dsb_gA = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gA.setGeometry(QtCore.QRect(80, 30, 81, 27))
        self.dsb_gA.setDecimals(4)
        self.dsb_gA.setProperty("value", 1.2723)
        self.dsb_gA.setObjectName("dsb_gA")
        self.dsb_gAeff = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gAeff.setGeometry(QtCore.QRect(80, 70, 81, 27))
        self.dsb_gAeff.setProperty("value", 1.0)
        self.dsb_gAeff.setObjectName("dsb_gAeff")
        self.label_29 = QtWidgets.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(180, 30, 31, 31))
        self.label_29.setObjectName("label_29")
        self.dsb_gM = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gM.setGeometry(QtCore.QRect(220, 30, 71, 27))
        self.dsb_gM.setDecimals(3)
        self.dsb_gM.setProperty("value", 4.706)
        self.dsb_gM.setObjectName("dsb_gM")
        self.dsb_gP = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gP.setGeometry(QtCore.QRect(220, 70, 71, 27))
        self.dsb_gP.setMinimum(-1000.0)
        self.dsb_gP.setMaximum(1000.0)
        self.dsb_gP.setProperty("value", 0.0)
        self.dsb_gP.setObjectName("dsb_gP")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(180, 70, 31, 31))
        self.label_28.setObjectName("label_28")
        self.b_resetNSO = QtWidgets.QPushButton(self.configTab)
        self.b_resetNSO.setGeometry(QtCore.QRect(20, 480, 141, 31))
        self.b_resetNSO.setObjectName("b_resetNSO")
        self.gb_ESP = QtWidgets.QGroupBox(self.configTab)
        self.gb_ESP.setEnabled(False)
        self.gb_ESP.setGeometry(QtCore.QRect(10, 170, 361, 311))
        self.gb_ESP.setObjectName("gb_ESP")
        self.cb_potential = QtWidgets.QComboBox(self.gb_ESP)
        self.cb_potential.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_potential.setObjectName("cb_potential")
        self.dsb_Xp = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_Xp.setGeometry(QtCore.QRect(280, 260, 69, 27))
        self.dsb_Xp.setProperty("value", 0.86)
        self.dsb_Xp.setObjectName("dsb_Xp")
        self.label_32 = QtWidgets.QLabel(self.gb_ESP)
        self.label_32.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_32.setObjectName("label_32")
        self.cb_reverseGhallagher = QtWidgets.QCheckBox(self.gb_ESP)
        self.cb_reverseGhallagher.setGeometry(QtCore.QRect(190, 70, 181, 22))
        self.cb_reverseGhallagher.setObjectName("cb_reverseGhallagher")
        self.dsb_V0Sn = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0Sn.setGeometry(QtCore.QRect(280, 180, 69, 27))
        self.dsb_V0Sn.setProperty("value", 7.2)
        self.dsb_V0Sn.setObjectName("dsb_V0Sn")
        self.label_37 = QtWidgets.QLabel(self.gb_ESP)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label_37.setObjectName("label_37")
        self.label_41 = QtWidgets.QLabel(self.gb_ESP)
        self.label_41.setGeometry(QtCore.QRect(180, 210, 101, 41))
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.gb_ESP)
        self.label_42.setGeometry(QtCore.QRect(10, 210, 91, 41))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.gb_ESP)
        self.label_43.setGeometry(QtCore.QRect(10, 180, 91, 31))
        self.label_43.setObjectName("label_43")
        self.dsb_Xn = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_Xn.setGeometry(QtCore.QRect(100, 260, 69, 27))
        self.dsb_Xn.setProperty("value", 0.86)
        self.dsb_Xn.setObjectName("dsb_Xn")
        self.dsb_V0n = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0n.setGeometry(QtCore.QRect(100, 180, 69, 27))
        self.dsb_V0n.setProperty("value", 49.6)
        self.dsb_V0n.setObjectName("dsb_V0n")
        self.dsb_V0p = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0p.setGeometry(QtCore.QRect(100, 216, 69, 31))
        self.dsb_V0p.setProperty("value", 49.6)
        self.dsb_V0p.setObjectName("dsb_V0p")
        self.label_44 = QtWidgets.QLabel(self.gb_ESP)
        self.label_44.setGeometry(QtCore.QRect(10, 260, 81, 31))
        self.label_44.setObjectName("label_44")
        self.cb_overrideCoupling = QtWidgets.QCheckBox(self.gb_ESP)
        self.cb_overrideCoupling.setGeometry(QtCore.QRect(10, 70, 181, 22))
        self.cb_overrideCoupling.setObjectName("cb_overrideCoupling")
        self.dsb_V0Sp = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_V0Sp.setGeometry(QtCore.QRect(280, 220, 69, 27))
        self.dsb_V0Sp.setProperty("value", 7.2)
        self.dsb_V0Sp.setObjectName("dsb_V0Sp")
        self.cb_forceSpin = QtWidgets.QCheckBox(self.gb_ESP)
        self.cb_forceSpin.setGeometry(QtCore.QRect(10, 100, 121, 22))
        self.cb_forceSpin.setChecked(True)
        self.cb_forceSpin.setObjectName("cb_forceSpin")
        self.label_45 = QtWidgets.QLabel(self.gb_ESP)
        self.label_45.setGeometry(QtCore.QRect(180, 260, 71, 31))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.gb_ESP)
        self.label_46.setGeometry(QtCore.QRect(180, 180, 101, 31))
        self.label_46.setObjectName("label_46")
        self.dsb_energyMargin = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.dsb_energyMargin.setGeometry(QtCore.QRect(120, 130, 91, 27))
        self.dsb_energyMargin.setDecimals(1)
        self.dsb_energyMargin.setMaximum(20.0)
        self.dsb_energyMargin.setProperty("value", 1.0)
        self.dsb_energyMargin.setObjectName("dsb_energyMargin")
        self.label_8 = QtWidgets.QLabel(self.gb_ESP)
        self.label_8.setGeometry(QtCore.QRect(220, 130, 21, 21))
        self.label_8.setObjectName("label_8")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gb_ESP)
        self.doubleSpinBox.setGeometry(QtCore.QRect(248, 130, 101, 27))
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 0.65)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.label_7 = QtWidgets.QLabel(self.configTab)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 67, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cb_nmeMethod = QtWidgets.QComboBox(self.configTab)
        self.cb_nmeMethod.setGeometry(QtCore.QRect(90, 120, 101, 27))
        self.cb_nmeMethod.setObjectName("cb_nmeMethod")
        self.optionsTabWidget.addTab(self.configTab, "")
        self.lab_logo = QtWidgets.QLabel(self.centralwidget)
        self.lab_logo.setGeometry(QtCore.QRect(10, 10, 331, 111))
        self.lab_logo.setAutoFillBackground(False)
        self.lab_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lab_logo.setText("")
        self.lab_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.lab_logo.setObjectName("lab_logo")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 130, 531, 611))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.bsgMainTab = QtWidgets.QWidget()
        self.bsgMainTab.setObjectName("bsgMainTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bsgMainTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 511, 501))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gv_plotSpectrum = PlotWidget(self.horizontalLayoutWidget)
        self.gv_plotSpectrum.setObjectName("gv_plotSpectrum")
        self.horizontalLayout.addWidget(self.gv_plotSpectrum)
        self.b_runBSG = QtWidgets.QPushButton(self.bsgMainTab)
        self.b_runBSG.setGeometry(QtCore.QRect(420, 10, 101, 51))
        self.b_runBSG.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.b_runBSG.setCheckable(False)
        self.b_runBSG.setChecked(False)
        self.b_runBSG.setDefault(False)
        self.b_runBSG.setFlat(False)
        self.b_runBSG.setObjectName("b_runBSG")
        self.le_outputName = QtWidgets.QLineEdit(self.bsgMainTab)
        self.le_outputName.setGeometry(QtCore.QRect(10, 30, 101, 27))
        self.le_outputName.setObjectName("le_outputName")
        self.label_10 = QtWidgets.QLabel(self.bsgMainTab)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.rb_currentSettings = QtWidgets.QRadioButton(self.bsgMainTab)
        self.rb_currentSettings.setGeometry(QtCore.QRect(240, 0, 141, 22))
        self.rb_currentSettings.setChecked(True)
        self.rb_currentSettings.setObjectName("rb_currentSettings")
        self.rb_configFile = QtWidgets.QRadioButton(self.bsgMainTab)
        self.rb_configFile.setGeometry(QtCore.QRect(240, 30, 61, 22))
        self.rb_configFile.setObjectName("rb_configFile")
        self.label_5 = QtWidgets.QLabel(self.bsgMainTab)
        self.label_5.setGeometry(QtCore.QRect(130, 0, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.b_chooseConfigFile = QtWidgets.QPushButton(self.bsgMainTab)
        self.b_chooseConfigFile.setGeometry(QtCore.QRect(300, 30, 91, 27))
        self.b_chooseConfigFile.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.b_chooseConfigFile.setObjectName("b_chooseConfigFile")
        self.b_clearSpectra = QtWidgets.QPushButton(self.bsgMainTab)
        self.b_clearSpectra.setGeometry(QtCore.QRect(130, 30, 91, 31))
        self.b_clearSpectra.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.b_clearSpectra.setCheckable(False)
        self.b_clearSpectra.setChecked(False)
        self.b_clearSpectra.setDefault(False)
        self.b_clearSpectra.setFlat(False)
        self.b_clearSpectra.setObjectName("b_clearSpectra")
        self.mainTabWidget.addTab(self.bsgMainTab, "")
        self.bsgOptionsTab = QtWidgets.QWidget()
        self.bsgOptionsTab.setObjectName("bsgOptionsTab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.bsgOptionsTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 511, 551))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.b_enable_all = QtWidgets.QPushButton(self.groupBox_2)
        self.b_enable_all.setGeometry(QtCore.QRect(10, 520, 101, 31))
        self.b_enable_all.setObjectName("b_enable_all")
        self.b_disable_all = QtWidgets.QPushButton(self.groupBox_2)
        self.b_disable_all.setGeometry(QtCore.QRect(120, 520, 101, 31))
        self.b_disable_all.setObjectName("b_disable_all")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(290, 420, 151, 80))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 290, 191, 201))
        self.groupBox_6.setObjectName("groupBox_6")
        self.cb_relativistic = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_relativistic.setGeometry(QtCore.QRect(20, 170, 111, 22))
        self.cb_relativistic.setChecked(True)
        self.cb_relativistic.setObjectName("cb_relativistic")
        self.cb_isovector = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_isovector.setGeometry(QtCore.QRect(20, 90, 181, 22))
        self.cb_isovector.setChecked(True)
        self.cb_isovector.setObjectName("cb_isovector")
        self.cb_C_shape = QtWidgets.QComboBox(self.groupBox_6)
        self.cb_C_shape.setGeometry(QtCore.QRect(40, 60, 121, 27))
        self.cb_C_shape.setObjectName("cb_C_shape")
        self.cb_C = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_C.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.cb_C.setChecked(True)
        self.cb_C.setObjectName("cb_C")
        self.cb_coupled = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_coupled.setGeometry(QtCore.QRect(50, 110, 91, 31))
        self.cb_coupled.setObjectName("cb_coupled")
        self.cb_C_deformation = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_C_deformation.setGeometry(QtCore.QRect(20, 140, 121, 22))
        self.cb_C_deformation.setChecked(True)
        self.cb_C_deformation.setObjectName("cb_C_deformation")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 130, 191, 161))
        self.groupBox_7.setObjectName("groupBox_7")
        self.cb_efs_deformation = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_efs_deformation.setGeometry(QtCore.QRect(20, 120, 151, 31))
        self.cb_efs_deformation.setChecked(True)
        self.cb_efs_deformation.setObjectName("cb_efs_deformation")
        self.cb_efs = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_efs.setGeometry(QtCore.QRect(20, 30, 151, 22))
        self.cb_efs.setChecked(True)
        self.cb_efs.setObjectName("cb_efs")
        self.cb_shape = QtWidgets.QComboBox(self.groupBox_7)
        self.cb_shape.setGeometry(QtCore.QRect(40, 90, 121, 27))
        self.cb_shape.setObjectName("cb_shape")
        self.cb_ens = QtWidgets.QCheckBox(self.groupBox_7)
        self.cb_ens.setGeometry(QtCore.QRect(20, 60, 171, 22))
        self.cb_ens.setChecked(True)
        self.cb_ens.setObjectName("cb_ens")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 0, 191, 131))
        self.groupBox_8.setObjectName("groupBox_8")
        self.cb_radiative = QtWidgets.QCheckBox(self.groupBox_8)
        self.cb_radiative.setGeometry(QtCore.QRect(20, 100, 181, 22))
        self.cb_radiative.setChecked(True)
        self.cb_radiative.setObjectName("cb_radiative")
        self.cb_fermi = QtWidgets.QCheckBox(self.groupBox_8)
        self.cb_fermi.setGeometry(QtCore.QRect(20, 61, 151, 31))
        self.cb_fermi.setChecked(True)
        self.cb_fermi.setObjectName("cb_fermi")
        self.cb_phasespace = QtWidgets.QCheckBox(self.groupBox_8)
        self.cb_phasespace.setGeometry(QtCore.QRect(20, 30, 131, 22))
        self.cb_phasespace.setChecked(True)
        self.cb_phasespace.setObjectName("cb_phasespace")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_9.setGeometry(QtCore.QRect(240, 10, 201, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.cb_Q = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_Q.setGeometry(QtCore.QRect(20, 60, 141, 22))
        self.cb_Q.setChecked(True)
        self.cb_Q.setObjectName("cb_Q")
        self.cb_recoil = QtWidgets.QCheckBox(self.groupBox_9)
        self.cb_recoil.setGeometry(QtCore.QRect(20, 30, 141, 22))
        self.cb_recoil.setChecked(True)
        self.cb_recoil.setObjectName("cb_recoil")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_10.setGeometry(QtCore.QRect(240, 100, 231, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.cb_mismatch = QtWidgets.QCheckBox(self.groupBox_10)
        self.cb_mismatch.setGeometry(QtCore.QRect(20, 90, 101, 31))
        self.cb_mismatch.setChecked(True)
        self.cb_mismatch.setObjectName("cb_mismatch")
        self.cb_screening = QtWidgets.QCheckBox(self.groupBox_10)
        self.cb_screening.setGeometry(QtCore.QRect(20, 30, 111, 22))
        self.cb_screening.setChecked(True)
        self.cb_screening.setObjectName("cb_screening")
        self.cb_exchange = QtWidgets.QCheckBox(self.groupBox_10)
        self.cb_exchange.setGeometry(QtCore.QRect(20, 60, 101, 22))
        self.cb_exchange.setChecked(True)
        self.cb_exchange.setObjectName("cb_exchange")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_11.setGeometry(QtCore.QRect(240, 330, 231, 181))
        self.groupBox_11.setObjectName("groupBox_11")
        self.sb_steps = QtWidgets.QSpinBox(self.groupBox_11)
        self.sb_steps.setEnabled(False)
        self.sb_steps.setGeometry(QtCore.QRect(90, 150, 111, 27))
        self.sb_steps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sb_steps.setMaximum(100000)
        self.sb_steps.setProperty("value", 0)
        self.sb_steps.setObjectName("sb_steps")
        self.dsb_stepSize = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.dsb_stepSize.setEnabled(True)
        self.dsb_stepSize.setGeometry(QtCore.QRect(90, 110, 111, 27))
        self.dsb_stepSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_stepSize.setMaximum(10000.0)
        self.dsb_stepSize.setProperty("value", 0.1)
        self.dsb_stepSize.setObjectName("dsb_stepSize")
        self.label_40 = QtWidgets.QLabel(self.groupBox_11)
        self.label_40.setGeometry(QtCore.QRect(20, 100, 41, 41))
        self.label_40.setObjectName("label_40")
        self.rb_stepSize = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_stepSize.setGeometry(QtCore.QRect(60, 110, 31, 22))
        self.rb_stepSize.setText("")
        self.rb_stepSize.setChecked(True)
        self.rb_stepSize.setObjectName("rb_stepSize")
        self.rb_steps = QtWidgets.QRadioButton(self.groupBox_11)
        self.rb_steps.setEnabled(True)
        self.rb_steps.setGeometry(QtCore.QRect(60, 150, 31, 22))
        self.rb_steps.setText("")
        self.rb_steps.setObjectName("rb_steps")
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setGeometry(QtCore.QRect(20, 70, 41, 31))
        self.label_39.setObjectName("label_39")
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setGeometry(QtCore.QRect(20, 30, 51, 31))
        self.label_38.setObjectName("label_38")
        self.dsb_end = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.dsb_end.setGeometry(QtCore.QRect(80, 70, 121, 27))
        self.dsb_end.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_end.setMaximum(20000.0)
        self.dsb_end.setObjectName("dsb_end")
        self.dsb_begin = QtWidgets.QDoubleSpinBox(self.groupBox_11)
        self.dsb_begin.setGeometry(QtCore.QRect(80, 30, 121, 27))
        self.dsb_begin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_begin.setMaximum(20000.0)
        self.dsb_begin.setProperty("value", 0.0)
        self.dsb_begin.setObjectName("dsb_begin")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setGeometry(QtCore.QRect(240, 230, 281, 91))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_36 = QtWidgets.QLabel(self.groupBox_12)
        self.label_36.setGeometry(QtCore.QRect(20, 60, 41, 31))
        self.label_36.setObjectName("label_36")
        self.dsb_dAc = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.dsb_dAc.setGeometry(QtCore.QRect(200, 30, 69, 27))
        self.dsb_dAc.setDecimals(3)
        self.dsb_dAc.setMinimum(-100.0)
        self.dsb_dAc.setMaximum(100.0)
        self.dsb_dAc.setObjectName("dsb_dAc")
        self.dsb_lambda = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.dsb_lambda.setGeometry(QtCore.QRect(70, 60, 69, 27))
        self.dsb_lambda.setDecimals(3)
        self.dsb_lambda.setMinimum(-100.0)
        self.dsb_lambda.setMaximum(100.0)
        self.dsb_lambda.setObjectName("dsb_lambda")
        self.dsb_bAc = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.dsb_bAc.setGeometry(QtCore.QRect(70, 30, 69, 27))
        self.dsb_bAc.setDecimals(3)
        self.dsb_bAc.setMinimum(-100.0)
        self.dsb_bAc.setMaximum(100.0)
        self.dsb_bAc.setObjectName("dsb_bAc")
        self.label_34 = QtWidgets.QLabel(self.groupBox_12)
        self.label_34.setGeometry(QtCore.QRect(20, 30, 41, 21))
        self.label_34.setObjectName("label_34")
        self.cb_enforceNME = QtWidgets.QCheckBox(self.groupBox_12)
        self.cb_enforceNME.setGeometry(QtCore.QRect(150, 60, 121, 22))
        self.cb_enforceNME.setObjectName("cb_enforceNME")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setGeometry(QtCore.QRect(150, 20, 41, 41))
        self.label_35.setObjectName("label_35")
        self.b_resetSSO = QtWidgets.QPushButton(self.groupBox_2)
        self.b_resetSSO.setGeometry(QtCore.QRect(230, 520, 131, 31))
        self.b_resetSSO.setObjectName("b_resetSSO")
        self.mainTabWidget.addTab(self.bsgOptionsTab, "")
        self.l_RMP = QtWidgets.QLabel(self.centralwidget)
        self.l_RMP.setGeometry(QtCore.QRect(350, 10, 171, 31))
        self.l_RMP.setLineWidth(0)
        self.l_RMP.setOpenExternalLinks(True)
        self.l_RMP.setObjectName("l_RMP")
        self.l_RMP_2 = QtWidgets.QLabel(self.centralwidget)
        self.l_RMP_2.setGeometry(QtCore.QRect(350, 40, 171, 41))
        self.l_RMP_2.setOpenExternalLinks(True)
        self.l_RMP_2.setObjectName("l_RMP_2")
        self.l_RMP_3 = QtWidgets.QLabel(self.centralwidget)
        self.l_RMP_3.setGeometry(QtCore.QRect(350, 80, 171, 31))
        self.l_RMP_3.setOpenExternalLinks(True)
        self.l_RMP_3.setObjectName("l_RMP_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuOpen = QtWidgets.QMenu(self.menu_File)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menu_File)
        self.menuSave.setObjectName("menuSave")
        self.menuComponent_paths = QtWidgets.QMenu(self.menu_File)
        self.menuComponent_paths.setObjectName("menuComponent_paths")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlotting = QtWidgets.QMenu(self.menuBar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuDatabase = QtWidgets.QMenu(self.menuBar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuLinks = QtWidgets.QMenu(self.menuDatabase)
        self.menuLinks.setObjectName("menuLinks")
        MainWindow.setMenuBar(self.menuBar)
        self.a_exit = QtWidgets.QAction(MainWindow)
        self.a_exit.setObjectName("a_exit")
        self.a_loadIni = QtWidgets.QAction(MainWindow)
        self.a_loadIni.setObjectName("a_loadIni")
        self.a_loadConfig = QtWidgets.QAction(MainWindow)
        self.a_loadConfig.setObjectName("a_loadConfig")
        self.a_about = QtWidgets.QAction(MainWindow)
        self.a_about.setObjectName("a_about")
        self.a_feedback = QtWidgets.QAction(MainWindow)
        self.a_feedback.setObjectName("a_feedback")
        self.a_saveIni = QtWidgets.QAction(MainWindow)
        self.a_saveIni.setObjectName("a_saveIni")
        self.a_saveConfig = QtWidgets.QAction(MainWindow)
        self.a_saveConfig.setObjectName("a_saveConfig")
        self.a_new = QtWidgets.QAction(MainWindow)
        self.a_new.setObjectName("a_new")
        self.a_bsgExec = QtWidgets.QAction(MainWindow)
        self.a_bsgExec.setObjectName("a_bsgExec")
        self.a_exchangeData = QtWidgets.QAction(MainWindow)
        self.a_exchangeData.setObjectName("a_exchangeData")
        self.a_clearPlots = QtWidgets.QAction(MainWindow)
        self.a_clearPlots.setObjectName("a_clearPlots")
        self.a_exportPlot = QtWidgets.QAction(MainWindow)
        self.a_exportPlot.setObjectName("a_exportPlot")
        self.a_plotColorSettings = QtWidgets.QAction(MainWindow)
        self.a_plotColorSettings.setObjectName("a_plotColorSettings")
        self.a_loadDeformation = QtWidgets.QAction(MainWindow)
        self.a_loadDeformation.setObjectName("a_loadDeformation")
        self.a_loadRadii = QtWidgets.QAction(MainWindow)
        self.a_loadRadii.setObjectName("a_loadRadii")
        self.a_findTransition = QtWidgets.QAction(MainWindow)
        self.a_findTransition.setObjectName("a_findTransition")
        self.actionNME_executable = QtWidgets.QAction(MainWindow)
        self.actionNME_executable.setObjectName("actionNME_executable")
        self.actionENSDF = QtWidgets.QAction(MainWindow)
        self.actionENSDF.setObjectName("actionENSDF")
        self.a_FRDM2012 = QtWidgets.QAction(MainWindow)
        self.a_FRDM2012.setObjectName("a_FRDM2012")
        self.a_ChargeRadii = QtWidgets.QAction(MainWindow)
        self.a_ChargeRadii.setObjectName("a_ChargeRadii")
        self.a_ENSDF = QtWidgets.QAction(MainWindow)
        self.a_ENSDF.setObjectName("a_ENSDF")
        self.menuOpen.addAction(self.a_loadIni)
        self.menuOpen.addAction(self.a_loadConfig)
        self.menuSave.addAction(self.a_saveIni)
        self.menuSave.addAction(self.a_saveConfig)
        self.menuComponent_paths.addAction(self.a_bsgExec)
        self.menuComponent_paths.addAction(self.a_exchangeData)
        self.menu_File.addAction(self.a_new)
        self.menu_File.addAction(self.menuComponent_paths.menuAction())
        self.menu_File.addAction(self.menuOpen.menuAction())
        self.menu_File.addAction(self.menuSave.menuAction())
        self.menu_File.addAction(self.a_exit)
        self.menuHelp.addAction(self.a_feedback)
        self.menuHelp.addAction(self.a_about)
        self.menuPlotting.addAction(self.a_clearPlots)
        self.menuPlotting.addAction(self.a_exportPlot)
        self.menuLinks.addAction(self.a_ENSDF)
        self.menuLinks.addAction(self.a_FRDM2012)
        self.menuLinks.addAction(self.a_ChargeRadii)
        self.menuDatabase.addAction(self.a_loadDeformation)
        self.menuDatabase.addAction(self.a_loadRadii)
        self.menuDatabase.addAction(self.a_findTransition)
        self.menuDatabase.addAction(self.menuLinks.menuAction())
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())
        self.menuBar.addAction(self.menuPlotting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.optionsTabWidget.setCurrentIndex(0)
        self.mainTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beta Spectrum Shape Generator"))
        self.group_M.setTitle(_translate("MainWindow", "Mother"))
        self.lab_ZM.setToolTip(_translate("MainWindow", "Atomic number"))
        self.lab_ZM.setStatusTip(_translate("MainWindow", "Atomic number"))
        self.lab_ZM.setText(_translate("MainWindow", "Z:"))
        self.lab_AM.setToolTip(_translate("MainWindow", "Mass number"))
        self.lab_AM.setStatusTip(_translate("MainWindow", "Mass number"))
        self.lab_AM.setText(_translate("MainWindow", "A:"))
        self.lab_RM.setToolTip(_translate("MainWindow", "Charge radius"))
        self.lab_RM.setStatusTip(_translate("MainWindow", "Charge radius"))
        self.lab_RM.setText(_translate("MainWindow", "Radius:"))
        self.lab_JM.setToolTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.lab_JM.setText(_translate("MainWindow", "Spin:"))
        self.lab_Beta2M.setStatusTip(_translate("MainWindow", "Quadrupole deformation"))
        self.lab_Beta2M.setText(_translate("MainWindow", "Beta2:"))
        self.lab_Beta4M.setStatusTip(_translate("MainWindow", "Hexadecupole deformation"))
        self.lab_Beta4M.setText(_translate("MainWindow", "Beta4:"))
        self.lab_Beta6M.setStatusTip(_translate("MainWindow", "Beta6 deformation"))
        self.lab_Beta6M.setText(_translate("MainWindow", "Beta6:"))
        self.lab_PiM.setToolTip(_translate("MainWindow", "Parity of nuclear level"))
        self.lab_PiM.setStatusTip(_translate("MainWindow", "Parity of nuclear level"))
        self.lab_PiM.setText(_translate("MainWindow", "Parity:"))
        self.sb_ZM.setToolTip(_translate("MainWindow", "Atomic number"))
        self.sb_ZM.setStatusTip(_translate("MainWindow", "Atomic number"))
        self.sb_AM.setToolTip(_translate("MainWindow", "Mass number"))
        self.sb_AM.setStatusTip(_translate("MainWindow", "Mass number"))
        self.dsb_RM.setToolTip(_translate("MainWindow", "Charge radius"))
        self.dsb_RM.setStatusTip(_translate("MainWindow", "Charge radius"))
        self.dsb_RM.setSuffix(_translate("MainWindow", " fm"))
        self.dsb_JM.setToolTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.dsb_JM.setStatusTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.cb_PiM.setToolTip(_translate("MainWindow", "Parity of nuclear level"))
        self.cb_PiM.setStatusTip(_translate("MainWindow", "Parity of nuclear level"))
        self.dsb_Beta2M.setStatusTip(_translate("MainWindow", "Quadrupole deformation"))
        self.dsb_Beta4M.setStatusTip(_translate("MainWindow", "Hexadecupole deformation"))
        self.dsb_Beta6M.setStatusTip(_translate("MainWindow", "Beta6 deformation"))
        self.label_31.setStatusTip(_translate("MainWindow", "Excitation energy of the parent level"))
        self.label_31.setText(_translate("MainWindow", "Energy:"))
        self.dsb_motherEn.setStatusTip(_translate("MainWindow", "Excitation energy of the parent level"))
        self.dsb_motherEn.setSuffix(_translate("MainWindow", " keV"))
        self.groupBox_3.setTitle(_translate("MainWindow", "General"))
        self.label_11.setToolTip(_translate("MainWindow", "Current ini file used for the transition"))
        self.label_11.setStatusTip(_translate("MainWindow", "Current ini file used for the transition"))
        self.label_11.setText(_translate("MainWindow", "Current file:"))
        self.l_iniFilename.setToolTip(_translate("MainWindow", "Current ini file used for the transition"))
        self.l_iniFilename.setStatusTip(_translate("MainWindow", "Current ini file used for the transition"))
        self.l_iniFilename.setText(_translate("MainWindow", "(blank)"))
        self.label_6.setText(_translate("MainWindow", "Transition:"))
        self.l_transitionName.setText(_translate("MainWindow", "(blank)"))
        self.label_16.setToolTip(_translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space"))
        self.label_16.setStatusTip(_translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space"))
        self.label_16.setText(_translate("MainWindow", "ROBTD File:"))
        self.b_chooseROBTDFile.setToolTip(_translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space"))
        self.b_chooseROBTDFile.setStatusTip(_translate("MainWindow", "Choose the Reduced one body transition density file, defined as < f || [a+_alpha a~_beta]_L || i > reduced in spin space"))
        self.b_chooseROBTDFile.setText(_translate("MainWindow", "..."))
        self.group_M_2.setTitle(_translate("MainWindow", "Daughter"))
        self.lab_ZD.setToolTip(_translate("MainWindow", "Atomic number"))
        self.lab_ZD.setStatusTip(_translate("MainWindow", "Atomic number"))
        self.lab_ZD.setText(_translate("MainWindow", "Z:"))
        self.lab_AD.setToolTip(_translate("MainWindow", "Mass number"))
        self.lab_AD.setStatusTip(_translate("MainWindow", "Mass number"))
        self.lab_AD.setText(_translate("MainWindow", "A:"))
        self.lab_RD.setToolTip(_translate("MainWindow", "Charge radius"))
        self.lab_RD.setStatusTip(_translate("MainWindow", "Charge radius"))
        self.lab_RD.setText(_translate("MainWindow", "Radius:"))
        self.lab_JD.setToolTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.lab_JD.setStatusTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.lab_JD.setText(_translate("MainWindow", "Spin:"))
        self.lab_Beta2D.setStatusTip(_translate("MainWindow", "Quadrupole deformation"))
        self.lab_Beta2D.setText(_translate("MainWindow", "Beta2:"))
        self.lab_Beta4D.setStatusTip(_translate("MainWindow", "Hexadecupole deformation"))
        self.lab_Beta4D.setText(_translate("MainWindow", "Beta4:"))
        self.lab_Beta6D.setStatusTip(_translate("MainWindow", "Beta6 deformation"))
        self.lab_Beta6D.setText(_translate("MainWindow", "Beta6:"))
        self.lab_PiD.setToolTip(_translate("MainWindow", "Parity of nuclear level"))
        self.lab_PiD.setStatusTip(_translate("MainWindow", "Parity of nuclear level"))
        self.lab_PiD.setText(_translate("MainWindow", "Parity:"))
        self.sb_ZD.setToolTip(_translate("MainWindow", "Atomic number"))
        self.sb_ZD.setStatusTip(_translate("MainWindow", "Atomic number"))
        self.sb_AD.setToolTip(_translate("MainWindow", "Mass number"))
        self.sb_AD.setStatusTip(_translate("MainWindow", "Mass number"))
        self.dsb_RD.setToolTip(_translate("MainWindow", "Charge radius"))
        self.dsb_RD.setStatusTip(_translate("MainWindow", "Charge radius"))
        self.dsb_RD.setSuffix(_translate("MainWindow", " fm"))
        self.dsb_JD.setToolTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.dsb_JD.setStatusTip(_translate("MainWindow", "Spin in units of HBAR"))
        self.cb_PiD.setStatusTip(_translate("MainWindow", "Parity of nuclear level"))
        self.dsb_Beta2D.setStatusTip(_translate("MainWindow", "Quadrupole deformation"))
        self.dsb_Beta4D.setStatusTip(_translate("MainWindow", "Hexadecupole deformation"))
        self.dsb_Beta6D.setStatusTip(_translate("MainWindow", "Beta6 deformation"))
        self.label_33.setStatusTip(_translate("MainWindow", "Excitation energy of the child level"))
        self.label_33.setText(_translate("MainWindow", "Energy:"))
        self.dsb_daughterEn.setStatusTip(_translate("MainWindow", "Excitation energy of the child level"))
        self.dsb_daughterEn.setSuffix(_translate("MainWindow", " keV"))
        self.groupBox.setTitle(_translate("MainWindow", "Transition"))
        self.label.setToolTip(_translate("MainWindow", "Decay process"))
        self.label.setStatusTip(_translate("MainWindow", "Decay process"))
        self.label.setText(_translate("MainWindow", "Process:"))
        self.label_2.setToolTip(_translate("MainWindow", "Decay type"))
        self.label_2.setStatusTip(_translate("MainWindow", "Decay type"))
        self.label_2.setText(_translate("MainWindow", "Type:"))
        self.label_3.setToolTip(_translate("MainWindow", "Mixing ratio as gAM_GT/M_F"))
        self.label_3.setStatusTip(_translate("MainWindow", "Mixing ratio as gAM_GT/M_F"))
        self.label_3.setText(_translate("MainWindow", "Mixing Ratio:"))
        self.label_4.setToolTip(_translate("MainWindow", "Q Value in keV"))
        self.label_4.setStatusTip(_translate("MainWindow", "Q Value in keV"))
        self.label_4.setText(_translate("MainWindow", "Q: "))
        self.cb_type.setToolTip(_translate("MainWindow", "Decay type"))
        self.cb_type.setStatusTip(_translate("MainWindow", "Decay type"))
        self.cb_process.setToolTip(_translate("MainWindow", "Decay process"))
        self.cb_process.setStatusTip(_translate("MainWindow", "Decay process"))
        self.dsb_MixingRatio.setToolTip(_translate("MainWindow", "Mixing ratio as gAM_GT/M_F"))
        self.dsb_MixingRatio.setStatusTip(_translate("MainWindow", "Mixing ratio as gAM_GT/M_F"))
        self.dsb_Q.setToolTip(_translate("MainWindow", "Q Value in keV"))
        self.dsb_Q.setStatusTip(_translate("MainWindow", "Q Value in keV"))
        self.dsb_Q.setSuffix(_translate("MainWindow", " keV"))
        self.label_30.setToolTip(_translate("MainWindow", "Partial Halflife"))
        self.label_30.setStatusTip(_translate("MainWindow", "Partial Halflife"))
        self.label_30.setText(_translate("MainWindow", "Halflife:"))
        self.dsb_halflife.setToolTip(_translate("MainWindow", "Partial Halflife"))
        self.dsb_halflife.setStatusTip(_translate("MainWindow", "Partial Halflife"))
        self.dsb_halflife.setSuffix(_translate("MainWindow", " s"))
        self.label_25.setToolTip(_translate("MainWindow", "Log ft value"))
        self.label_25.setStatusTip(_translate("MainWindow", "Log ft value"))
        self.label_25.setText(_translate("MainWindow", "Log ft:"))
        self.dsb_logft.setToolTip(_translate("MainWindow", "Log ft value"))
        self.dsb_logft.setStatusTip(_translate("MainWindow", "Log ft value"))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.iniTab), _translate("MainWindow", "Transition Info"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Constants"))
        self.label_26.setToolTip(_translate("MainWindow", "Axial vector constant of the neutron"))
        self.label_26.setStatusTip(_translate("MainWindow", "Axial vector constant of the neutron"))
        self.label_26.setText(_translate("MainWindow", "gA:"))
        self.label_27.setToolTip(_translate("MainWindow", "Effective (quenched) value of gA"))
        self.label_27.setStatusTip(_translate("MainWindow", "Effective (quenched) value of gA"))
        self.label_27.setText(_translate("MainWindow", "gA_eff:"))
        self.dsb_gA.setToolTip(_translate("MainWindow", "Axial vector constant of the neutron"))
        self.dsb_gA.setStatusTip(_translate("MainWindow", "Axial vector constant of the neutron"))
        self.dsb_gAeff.setToolTip(_translate("MainWindow", "Effective (quenched) value of gA"))
        self.dsb_gAeff.setStatusTip(_translate("MainWindow", "Effective (quenched) value of gA"))
        self.label_29.setToolTip(_translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)"))
        self.label_29.setStatusTip(_translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)"))
        self.label_29.setText(_translate("MainWindow", "gM:"))
        self.dsb_gM.setToolTip(_translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)"))
        self.dsb_gM.setStatusTip(_translate("MainWindow", "Weak magnetism form factor (isovector magnetic moment + 1)"))
        self.dsb_gP.setToolTip(_translate("MainWindow", "Induced pseudoscalar coupling"))
        self.dsb_gP.setStatusTip(_translate("MainWindow", "Induced pseudoscalar coupling"))
        self.label_28.setToolTip(_translate("MainWindow", "Induced pseudoscalar coupling"))
        self.label_28.setStatusTip(_translate("MainWindow", "Induced pseudoscalar coupling"))
        self.label_28.setText(_translate("MainWindow", "gP:"))
        self.b_resetNSO.setText(_translate("MainWindow", "Reset to ..."))
        self.gb_ESP.setTitle(_translate("MainWindow", "Extreme Single Particle"))
        self.cb_potential.setToolTip(_translate("MainWindow", "Choose the mean-field potential"))
        self.cb_potential.setStatusTip(_translate("MainWindow", "Choose the mean-field potential"))
        self.label_32.setToolTip(_translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity"))
        self.label_32.setStatusTip(_translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity"))
        self.label_32.setText(_translate("MainWindow", "Energy Margin:"))
        self.cb_reverseGhallagher.setText(_translate("MainWindow", "Reversed Ghallagher"))
        self.dsb_V0Sn.setToolTip(_translate("MainWindow", "Spin-orbit strength"))
        self.dsb_V0Sn.setStatusTip(_translate("MainWindow", "Spin-orbit strength"))
        self.label_37.setToolTip(_translate("MainWindow", "Choose the mean-field potential"))
        self.label_37.setStatusTip(_translate("MainWindow", "Choose the mean-field potential"))
        self.label_37.setText(_translate("MainWindow", "Potential:"))
        self.label_41.setToolTip(_translate("MainWindow", "Spin-orbit strength"))
        self.label_41.setStatusTip(_translate("MainWindow", "Spin-orbit strength"))
        self.label_41.setText(_translate("MainWindow", "V0S protons:"))
        self.label_42.setToolTip(_translate("MainWindow", "Potential depth"))
        self.label_42.setStatusTip(_translate("MainWindow", "Potential depth"))
        self.label_42.setText(_translate("MainWindow", "V0 protons:"))
        self.label_43.setToolTip(_translate("MainWindow", "Potential depth"))
        self.label_43.setStatusTip(_translate("MainWindow", "Potential depth"))
        self.label_43.setText(_translate("MainWindow", "V0 neutrons:"))
        self.dsb_Xn.setToolTip(_translate("MainWindow", "Proton-neutron asymmetry"))
        self.dsb_Xn.setStatusTip(_translate("MainWindow", "Proton-neutron asymmetry"))
        self.dsb_V0n.setToolTip(_translate("MainWindow", "Potential depth"))
        self.dsb_V0n.setStatusTip(_translate("MainWindow", "Potential depth"))
        self.dsb_V0p.setToolTip(_translate("MainWindow", "Potential depth"))
        self.dsb_V0p.setStatusTip(_translate("MainWindow", "Potential depth"))
        self.label_44.setToolTip(_translate("MainWindow", "Proton-neutron asymmetry"))
        self.label_44.setStatusTip(_translate("MainWindow", "Proton-neutron asymmetry"))
        self.label_44.setText(_translate("MainWindow", "X neutron:"))
        self.cb_overrideCoupling.setText(_translate("MainWindow", "Override SP coupling"))
        self.dsb_V0Sp.setToolTip(_translate("MainWindow", "Spin-orbit strength"))
        self.dsb_V0Sp.setStatusTip(_translate("MainWindow", "Spin-orbit strength"))
        self.cb_forceSpin.setText(_translate("MainWindow", "Force Spin"))
        self.label_45.setToolTip(_translate("MainWindow", "Proton-neutron asymmetry"))
        self.label_45.setStatusTip(_translate("MainWindow", "Proton-neutron asymmetry"))
        self.label_45.setText(_translate("MainWindow", "X proton:"))
        self.label_46.setToolTip(_translate("MainWindow", "Spin-orbit strength"))
        self.label_46.setStatusTip(_translate("MainWindow", "Spin-orbit strength"))
        self.label_46.setText(_translate("MainWindow", "V0S neutrons:"))
        self.dsb_energyMargin.setToolTip(_translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity"))
        self.dsb_energyMargin.setStatusTip(_translate("MainWindow", "Maximum energy difference between proposed state and that of correct spin-parity"))
        self.dsb_energyMargin.setSuffix(_translate("MainWindow", " MeV"))
        self.label_8.setToolTip(_translate("MainWindow", "Surface thickness of the Woods-Saxon potential"))
        self.label_8.setStatusTip(_translate("MainWindow", "Surface thickness of the Woods-Saxon potential"))
        self.label_8.setText(_translate("MainWindow", "a:"))
        self.doubleSpinBox.setToolTip(_translate("MainWindow", "Surface thickness of the Woods-Saxon potential"))
        self.doubleSpinBox.setStatusTip(_translate("MainWindow", "Surface thickness of the Woods-Saxon potential"))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", " fm"))
        self.label_7.setText(_translate("MainWindow", "Method:"))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.configTab), _translate("MainWindow", "Nuclear Structure Options"))
        self.b_runBSG.setToolTip(_translate("MainWindow", "Run the spectrum shape generator"))
        self.b_runBSG.setStatusTip(_translate("MainWindow", "Run the spectrum shape generator"))
        self.b_runBSG.setText(_translate("MainWindow", "Run!"))
        self.le_outputName.setStatusTip(_translate("MainWindow", "Choose the output name of all files generated (omit extension)"))
        self.le_outputName.setText(_translate("MainWindow", "output"))
        self.label_10.setStatusTip(_translate("MainWindow", "Choose the output name of all files generated (omit extension)"))
        self.label_10.setText(_translate("MainWindow", "Output name:"))
        self.rb_currentSettings.setToolTip(_translate("MainWindow", "Use the Spectral Shape & Nuclear Structure options as currently specified in the GUI"))
        self.rb_currentSettings.setStatusTip(_translate("MainWindow", "Use the Spectral Shape & Nuclear Structure options as currently specified in the GUI"))
        self.rb_currentSettings.setText(_translate("MainWindow", "Current settings"))
        self.rb_configFile.setToolTip(_translate("MainWindow", "Use the Spectrum Shape and Nuclear Structure Options as specified in an external config file"))
        self.rb_configFile.setStatusTip(_translate("MainWindow", "Use the Spectrum Shape and Nuclear Structure Options as specified in an external config file"))
        self.rb_configFile.setText(_translate("MainWindow", "File:"))
        self.label_5.setText(_translate("MainWindow", "Configuration:"))
        self.b_chooseConfigFile.setText(_translate("MainWindow", "..."))
        self.b_clearSpectra.setToolTip(_translate("MainWindow", "Run the spectrum shape generator"))
        self.b_clearSpectra.setStatusTip(_translate("MainWindow", "Run the spectrum shape generator"))
        self.b_clearSpectra.setText(_translate("MainWindow", "Clear graphs"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgMainTab), _translate("MainWindow", "Beta Spectrum Shape Generator"))
        self.b_enable_all.setToolTip(_translate("MainWindow", "Enable all corrections"))
        self.b_enable_all.setStatusTip(_translate("MainWindow", "Enable all corrections"))
        self.b_enable_all.setText(_translate("MainWindow", "Enable All"))
        self.b_disable_all.setToolTip(_translate("MainWindow", "Disable all corrections"))
        self.b_disable_all.setStatusTip(_translate("MainWindow", "Disable all corrections"))
        self.b_disable_all.setText(_translate("MainWindow", "Disable All"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Nuclear Structure"))
        self.cb_relativistic.setToolTip(_translate("MainWindow", "Take into account relativistic (O(v/c) ~ 1/(MR)) terms in the Shape factor"))
        self.cb_relativistic.setStatusTip(_translate("MainWindow", "Take into account relativistic (O(v/c) ~ 1/(MR)) terms in the Shape factor"))
        self.cb_relativistic.setText(_translate("MainWindow", "Relativistic"))
        self.cb_isovector.setToolTip(_translate("MainWindow", "Correction due to CVC breakdown due to isospin symmetry breaking"))
        self.cb_isovector.setStatusTip(_translate("MainWindow", "Correction due to CVC breakdown due to isospin symmetry breaking"))
        self.cb_isovector.setText(_translate("MainWindow", "Isovector Correction"))
        self.cb_C_shape.setToolTip(_translate("MainWindow", "Shape of the nuclear charge distribution"))
        self.cb_C_shape.setStatusTip(_translate("MainWindow", "Shape of the nuclear charge distribution"))
        self.cb_C.setToolTip(_translate("MainWindow", "Nuclear shape factor, taking into account the convolution of leptonic and nuclear wave functions and induced currents"))
        self.cb_C.setStatusTip(_translate("MainWindow", "Nuclear shape factor, taking into account the convolution of leptonic and nuclear wave functions and induced currents"))
        self.cb_C.setText(_translate("MainWindow", "Shape factor"))
        self.cb_coupled.setToolTip(_translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel."))
        self.cb_coupled.setStatusTip(_translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel."))
        self.cb_coupled.setText(_translate("MainWindow", "Coupled"))
        self.cb_C_deformation.setToolTip(_translate("MainWindow", "Take into account nuclear deformation in the convolution of lepton and nuclear wave functions"))
        self.cb_C_deformation.setStatusTip(_translate("MainWindow", "Take into account nuclear deformation in the convolution of lepton and nuclear wave functions"))
        self.cb_C_deformation.setText(_translate("MainWindow", "Deformation"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Electrostatic"))
        self.cb_efs_deformation.setToolTip(_translate("MainWindow", "Additional correction factor to take into account nuclear deformation on the final state electric interaction"))
        self.cb_efs_deformation.setStatusTip(_translate("MainWindow", "Additional correction factor to take into account nuclear deformation on the final state electric interaction"))
        self.cb_efs_deformation.setText(_translate("MainWindow", "ES Deformation"))
        self.cb_efs.setToolTip(_translate("MainWindow", "Correction factor to the Fermi function to take into account the finite size of the nuclear charge distribution. Approximated as a uniformly charged sphere"))
        self.cb_efs.setStatusTip(_translate("MainWindow", "Correction factor to the Fermi function to take into account the finite size of the nuclear charge distribution. Approximated as a uniformly charged sphere"))
        self.cb_efs.setText(_translate("MainWindow", "ES Finite Size"))
        self.cb_shape.setToolTip(_translate("MainWindow", "Choose nuclear shape for higher-order correction"))
        self.cb_shape.setStatusTip(_translate("MainWindow", "Choose nuclear shape for higher-order correction"))
        self.cb_ens.setToolTip(_translate("MainWindow", "Higher-order correction to the ES Finite size above, by going beyond a uniformly charged sphere to a Fermi or Modified Gaussian shape."))
        self.cb_ens.setStatusTip(_translate("MainWindow", "Higher-order correction to the ES Finite size above, by going beyond a uniformly charged sphere to a Fermi or Modified Gaussian shape."))
        self.cb_ens.setText(_translate("MainWindow", "ES Nuclear Shape"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Basic"))
        self.cb_radiative.setToolTip(_translate("MainWindow", "Additional QED & Weak interaction radiative corrections, through (virtual) photon, gamma and W exchange"))
        self.cb_radiative.setStatusTip(_translate("MainWindow", "Additional QED & Weak interaction radiative corrections, through (virtual) photon, gamma and W exchange"))
        self.cb_radiative.setText(_translate("MainWindow", "Radiative corrections"))
        self.cb_fermi.setToolTip(_translate("MainWindow", "Final state interaction between outgoing lepton and final nuclear charge density, approximated as a point charge"))
        self.cb_fermi.setStatusTip(_translate("MainWindow", "Final state interaction between outgoing lepton and final nuclear charge density, approximated as a point charge"))
        self.cb_fermi.setText(_translate("MainWindow", "Fermi Function"))
        self.cb_phasespace.setToolTip(_translate("MainWindow", "The kinematical phase space factor, pW(W0-W)^2"))
        self.cb_phasespace.setStatusTip(_translate("MainWindow", "The kinematical phase space factor, pW(W0-W)^2"))
        self.cb_phasespace.setText(_translate("MainWindow", "Phase Space"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Kinematic"))
        self.cb_Q.setToolTip(_translate("MainWindow", "Correction term due to the movement of the Coulomb potential in case the nucleus is not infinitely massive"))
        self.cb_Q.setStatusTip(_translate("MainWindow", "Correction term due to the movement of the Coulomb potential in case the nucleus is not infinitely massive"))
        self.cb_Q.setText(_translate("MainWindow", "Coulomb Recoil"))
        self.cb_recoil.setToolTip(_translate("MainWindow", "Kinematical correction factor to take into account the finite nuclear mass."))
        self.cb_recoil.setStatusTip(_translate("MainWindow", "Kinematical correction factor to take into account the finite nuclear mass."))
        self.cb_recoil.setText(_translate("MainWindow", "Nuclear Recoil"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Atomic"))
        self.cb_mismatch.setToolTip(_translate("MainWindow", "Average treatment of the decrease in phase space due to atomic excitations."))
        self.cb_mismatch.setStatusTip(_translate("MainWindow", "Average treatment of the decrease in phase space due to atomic excitations."))
        self.cb_mismatch.setText(_translate("MainWindow", "Mismatch"))
        self.cb_screening.setToolTip(_translate("MainWindow", "Screening of the nuclear charge by atomic electrons"))
        self.cb_screening.setStatusTip(_translate("MainWindow", "Screening of the nuclear charge by atomic electrons"))
        self.cb_screening.setText(_translate("MainWindow", "Screening"))
        self.cb_exchange.setToolTip(_translate("MainWindow", "Atomic exchange process, decay directly into bound state."))
        self.cb_exchange.setStatusTip(_translate("MainWindow", "Atomic exchange process, decay directly into bound state."))
        self.cb_exchange.setText(_translate("MainWindow", "Exchange"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Limits"))
        self.sb_steps.setToolTip(_translate("MainWindow", "Number of steps"))
        self.sb_steps.setStatusTip(_translate("MainWindow", "Number of steps"))
        self.sb_steps.setSuffix(_translate("MainWindow", " steps"))
        self.dsb_stepSize.setToolTip(_translate("MainWindow", "Step size in keV"))
        self.dsb_stepSize.setStatusTip(_translate("MainWindow", "Step size in keV"))
        self.dsb_stepSize.setSuffix(_translate("MainWindow", " keV"))
        self.label_40.setToolTip(_translate("MainWindow", "Step size or number of steps for which to calculate the spectrum"))
        self.label_40.setStatusTip(_translate("MainWindow", "Step size or number of steps for which to calculate the spectrum"))
        self.label_40.setText(_translate("MainWindow", "Step:"))
        self.label_39.setToolTip(_translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint)."))
        self.label_39.setStatusTip(_translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint)."))
        self.label_39.setText(_translate("MainWindow", "End:"))
        self.label_38.setToolTip(_translate("MainWindow", "Starting energy from where to calculate"))
        self.label_38.setStatusTip(_translate("MainWindow", "Starting energy from where to calculate"))
        self.label_38.setText(_translate("MainWindow", "Begin:"))
        self.dsb_end.setToolTip(_translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint)."))
        self.dsb_end.setStatusTip(_translate("MainWindow", "Final energy up to which to calculate (0 means until the endpoint)."))
        self.dsb_end.setSuffix(_translate("MainWindow", " keV"))
        self.dsb_begin.setStatusTip(_translate("MainWindow", "Starting energy from where to calculate", "Starting energy from where to calculate"))
        self.dsb_begin.setSuffix(_translate("MainWindow", " keV"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Matrix Elements"))
        self.label_36.setToolTip(_translate("MainWindow", "Related to induced pseudoscalar in Holstein\'s formalism"))
        self.label_36.setStatusTip(_translate("MainWindow", "Related to induced pseudoscalar in Holstein\'s formalism"))
        self.label_36.setText(_translate("MainWindow", "Λ:"))
        self.label_34.setToolTip(_translate("MainWindow", "Weak magnetism, in Holstein\'s formalism"))
        self.label_34.setStatusTip(_translate("MainWindow", "Weak magnetism, in Holstein\'s formalism"))
        self.label_34.setText(_translate("MainWindow", "b/Ac:"))
        self.cb_enforceNME.setToolTip(_translate("MainWindow", "Choose whether to enforce the values for b/Ac, d/Ac and Lambda written here, or leave it to the NME library"))
        self.cb_enforceNME.setStatusTip(_translate("MainWindow", "Choose whether to enforce the values for b/Ac, d/Ac and Lambda written here, or leave it to the NME library"))
        self.cb_enforceNME.setText(_translate("MainWindow", "Enforce"))
        self.label_35.setToolTip(_translate("MainWindow", "Induced tensor, as in Holstein\'s formalism"))
        self.label_35.setStatusTip(_translate("MainWindow", "Induced tensor, as in Holstein\'s formalism"))
        self.label_35.setText(_translate("MainWindow", "d/Ac:"))
        self.b_resetSSO.setText(_translate("MainWindow", "Reset to ..."))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgOptionsTab), _translate("MainWindow", "Spectral Shape Options"))
        self.l_RMP.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.90.015008\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to Rev. Mod. Phys.</span></a></p></body></html>"))
        self.l_RMP_2.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://arxiv.org/abs/1803.00525\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to BSG paper</span></a></p></body></html>"))
        self.l_RMP_3.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/leenderthayen/BSG\"><span style=\" text-decoration: underline; color:#ffffff;\">Link to Github</span></a></p></body></html>"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuComponent_paths.setTitle(_translate("MainWindow", "Component paths"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPlotting.setTitle(_translate("MainWindow", "&Plotting"))
        self.menuDatabase.setTitle(_translate("MainWindow", "&Database"))
        self.menuLinks.setTitle(_translate("MainWindow", "Links"))
        self.a_exit.setText(_translate("MainWindow", "Exit"))
        self.a_exit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.a_loadIni.setText(_translate("MainWindow", "Ini file"))
        self.a_loadIni.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.a_loadConfig.setText(_translate("MainWindow", "Config file"))
        self.a_loadConfig.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.a_about.setText(_translate("MainWindow", "About"))
        self.a_feedback.setText(_translate("MainWindow", "Submit feedback"))
        self.a_saveIni.setText(_translate("MainWindow", "Ini file"))
        self.a_saveIni.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.a_saveConfig.setText(_translate("MainWindow", "Config file"))
        self.a_saveConfig.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.a_new.setText(_translate("MainWindow", "New"))
        self.a_new.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.a_bsgExec.setText(_translate("MainWindow", "BSG executable"))
        self.a_bsgExec.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.a_exchangeData.setText(_translate("MainWindow", "Exchange data"))
        self.a_exchangeData.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.a_clearPlots.setText(_translate("MainWindow", "Clear"))
        self.a_exportPlot.setText(_translate("MainWindow", "Export"))
        self.a_plotColorSettings.setText(_translate("MainWindow", "Color settings"))
        self.a_loadDeformation.setText(_translate("MainWindow", "Load deformation"))
        self.a_loadDeformation.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.a_loadRadii.setText(_translate("MainWindow", "Load radii"))
        self.a_loadRadii.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.a_findTransition.setText(_translate("MainWindow", "Find transition (ENSDF)"))
        self.a_findTransition.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionNME_executable.setText(_translate("MainWindow", "NME executable"))
        self.actionNME_executable.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionENSDF.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.nndc.bnl.gov/ensarchivals/\"><span style=\" text-decoration: underline; color:#ffffff;\">ENSDF</span></a></p></body></html>"))
        self.a_FRDM2012.setText(_translate("MainWindow", "FRDM2012"))
        self.a_ChargeRadii.setText(_translate("MainWindow", "ChargeRadii"))
        self.a_ENSDF.setText(_translate("MainWindow", "ENSDF"))

from pyqtgraph import PlotWidget
