# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Dec  8 18:21:03 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 678)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(520, 510, 361, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.txt_lastActions = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.txt_lastActions.setGeometry(QtCore.QRect(0, 0, 361, 161))
        self.txt_lastActions.setObjectName("txt_lastActions")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.optionsTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.optionsTabWidget.setGeometry(QtCore.QRect(510, 20, 381, 451))
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.iniTab = QtGui.QWidget()
        self.iniTab.setObjectName("iniTab")
        self.groupBox = QtGui.QGroupBox(self.iniTab)
        self.groupBox.setGeometry(QtCore.QRect(180, 0, 191, 151))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 30, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 67, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 120, 67, 21))
        self.label_4.setObjectName("label_4")
        self.cb_type = QtGui.QComboBox(self.groupBox)
        self.cb_type.setGeometry(QtCore.QRect(80, 60, 111, 27))
        self.cb_type.setObjectName("cb_type")
        self.cb_process = QtGui.QComboBox(self.groupBox)
        self.cb_process.setGeometry(QtCore.QRect(110, 30, 81, 27))
        self.cb_process.setObjectName("cb_process")
        self.dsb_MixingRatio = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_MixingRatio.setGeometry(QtCore.QRect(100, 90, 91, 27))
        self.dsb_MixingRatio.setObjectName("dsb_MixingRatio")
        self.dsb_Q = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_Q.setGeometry(QtCore.QRect(70, 120, 121, 27))
        self.dsb_Q.setMaximum(20000.0)
        self.dsb_Q.setObjectName("dsb_Q")
        self.group_M = QtGui.QGroupBox(self.iniTab)
        self.group_M.setGeometry(QtCore.QRect(10, 150, 171, 261))
        self.group_M.setObjectName("group_M")
        self.lab_ZM = QtGui.QLabel(self.group_M)
        self.lab_ZM.setGeometry(QtCore.QRect(0, 20, 61, 31))
        self.lab_ZM.setObjectName("lab_ZM")
        self.lab_AM = QtGui.QLabel(self.group_M)
        self.lab_AM.setGeometry(QtCore.QRect(0, 50, 67, 31))
        self.lab_AM.setObjectName("lab_AM")
        self.lab_RM = QtGui.QLabel(self.group_M)
        self.lab_RM.setGeometry(QtCore.QRect(0, 80, 67, 31))
        self.lab_RM.setObjectName("lab_RM")
        self.lab_JM = QtGui.QLabel(self.group_M)
        self.lab_JM.setGeometry(QtCore.QRect(0, 110, 67, 31))
        self.lab_JM.setObjectName("lab_JM")
        self.lab_Beta2M = QtGui.QLabel(self.group_M)
        self.lab_Beta2M.setGeometry(QtCore.QRect(0, 170, 67, 31))
        self.lab_Beta2M.setObjectName("lab_Beta2M")
        self.lab_Beta4M = QtGui.QLabel(self.group_M)
        self.lab_Beta4M.setGeometry(QtCore.QRect(0, 200, 67, 31))
        self.lab_Beta4M.setObjectName("lab_Beta4M")
        self.lab_Beta6M = QtGui.QLabel(self.group_M)
        self.lab_Beta6M.setGeometry(QtCore.QRect(0, 226, 67, 31))
        self.lab_Beta6M.setObjectName("lab_Beta6M")
        self.lab_PiM = QtGui.QLabel(self.group_M)
        self.lab_PiM.setGeometry(QtCore.QRect(0, 140, 67, 31))
        self.lab_PiM.setObjectName("lab_PiM")
        self.sb_ZM = QtGui.QSpinBox(self.group_M)
        self.sb_ZM.setGeometry(QtCore.QRect(110, 20, 48, 27))
        self.sb_ZM.setObjectName("sb_ZM")
        self.sb_AM = QtGui.QSpinBox(self.group_M)
        self.sb_AM.setGeometry(QtCore.QRect(110, 50, 48, 27))
        self.sb_AM.setObjectName("sb_AM")
        self.dsb_RM = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_RM.setGeometry(QtCore.QRect(80, 80, 81, 27))
        self.dsb_RM.setSingleStep(0.1)
        self.dsb_RM.setObjectName("dsb_RM")
        self.dsb_JM = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_JM.setGeometry(QtCore.QRect(90, 110, 71, 27))
        self.dsb_JM.setDecimals(1)
        self.dsb_JM.setSingleStep(0.5)
        self.dsb_JM.setObjectName("dsb_JM")
        self.cb_PiM = QtGui.QComboBox(self.group_M)
        self.cb_PiM.setGeometry(QtCore.QRect(100, 140, 61, 27))
        self.cb_PiM.setObjectName("cb_PiM")
        self.dsb_Beta2M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta2M.setGeometry(QtCore.QRect(90, 170, 69, 27))
        self.dsb_Beta2M.setDecimals(3)
        self.dsb_Beta2M.setMinimum(-1.0)
        self.dsb_Beta2M.setMaximum(1.0)
        self.dsb_Beta2M.setSingleStep(0.1)
        self.dsb_Beta2M.setObjectName("dsb_Beta2M")
        self.dsb_Beta4M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta4M.setGeometry(QtCore.QRect(90, 200, 69, 27))
        self.dsb_Beta4M.setDecimals(3)
        self.dsb_Beta4M.setMinimum(-1.0)
        self.dsb_Beta4M.setMaximum(1.0)
        self.dsb_Beta4M.setSingleStep(0.1)
        self.dsb_Beta4M.setObjectName("dsb_Beta4M")
        self.dsb_Beta6M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta6M.setGeometry(QtCore.QRect(90, 230, 69, 27))
        self.dsb_Beta6M.setDecimals(3)
        self.dsb_Beta6M.setMinimum(-1.0)
        self.dsb_Beta6M.setMaximum(1.0)
        self.dsb_Beta6M.setSingleStep(0.1)
        self.dsb_Beta6M.setObjectName("dsb_Beta6M")
        self.groupBox_3 = QtGui.QGroupBox(self.iniTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 161, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(0, 20, 91, 21))
        self.label_11.setObjectName("label_11")
        self.l_iniFilename = QtGui.QLabel(self.groupBox_3)
        self.l_iniFilename.setGeometry(QtCore.QRect(0, 50, 161, 17))
        self.l_iniFilename.setObjectName("l_iniFilename")
        self.b_load_ini = QtGui.QPushButton(self.groupBox_3)
        self.b_load_ini.setGeometry(QtCore.QRect(10, 80, 131, 27))
        self.b_load_ini.setObjectName("b_load_ini")
        self.b_save_ini = QtGui.QPushButton(self.groupBox_3)
        self.b_save_ini.setGeometry(QtCore.QRect(10, 110, 131, 27))
        self.b_save_ini.setObjectName("b_save_ini")
        self.group_M_2 = QtGui.QGroupBox(self.iniTab)
        self.group_M_2.setGeometry(QtCore.QRect(180, 150, 191, 261))
        self.group_M_2.setObjectName("group_M_2")
        self.lab_ZD = QtGui.QLabel(self.group_M_2)
        self.lab_ZD.setGeometry(QtCore.QRect(0, 20, 61, 31))
        self.lab_ZD.setObjectName("lab_ZD")
        self.lab_AD = QtGui.QLabel(self.group_M_2)
        self.lab_AD.setGeometry(QtCore.QRect(0, 50, 67, 31))
        self.lab_AD.setObjectName("lab_AD")
        self.lab_RD = QtGui.QLabel(self.group_M_2)
        self.lab_RD.setGeometry(QtCore.QRect(0, 80, 67, 31))
        self.lab_RD.setObjectName("lab_RD")
        self.lab_JD = QtGui.QLabel(self.group_M_2)
        self.lab_JD.setGeometry(QtCore.QRect(0, 110, 67, 31))
        self.lab_JD.setObjectName("lab_JD")
        self.lab_Beta2D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta2D.setGeometry(QtCore.QRect(0, 170, 67, 31))
        self.lab_Beta2D.setObjectName("lab_Beta2D")
        self.lab_Beta4D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta4D.setGeometry(QtCore.QRect(0, 200, 67, 31))
        self.lab_Beta4D.setObjectName("lab_Beta4D")
        self.lab_Beta6D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta6D.setGeometry(QtCore.QRect(0, 226, 67, 31))
        self.lab_Beta6D.setObjectName("lab_Beta6D")
        self.lab_PiD = QtGui.QLabel(self.group_M_2)
        self.lab_PiD.setGeometry(QtCore.QRect(0, 140, 67, 31))
        self.lab_PiD.setObjectName("lab_PiD")
        self.sb_ZD = QtGui.QSpinBox(self.group_M_2)
        self.sb_ZD.setGeometry(QtCore.QRect(140, 20, 48, 27))
        self.sb_ZD.setObjectName("sb_ZD")
        self.sb_AD = QtGui.QSpinBox(self.group_M_2)
        self.sb_AD.setGeometry(QtCore.QRect(140, 50, 48, 27))
        self.sb_AD.setObjectName("sb_AD")
        self.dsb_RD = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_RD.setGeometry(QtCore.QRect(110, 80, 81, 27))
        self.dsb_RD.setSingleStep(0.1)
        self.dsb_RD.setObjectName("dsb_RD")
        self.dsb_JD = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_JD.setGeometry(QtCore.QRect(120, 110, 71, 27))
        self.dsb_JD.setDecimals(1)
        self.dsb_JD.setSingleStep(0.5)
        self.dsb_JD.setObjectName("dsb_JD")
        self.cb_PiD = QtGui.QComboBox(self.group_M_2)
        self.cb_PiD.setGeometry(QtCore.QRect(130, 140, 61, 27))
        self.cb_PiD.setObjectName("cb_PiD")
        self.dsb_Beta2D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta2D.setGeometry(QtCore.QRect(120, 170, 69, 27))
        self.dsb_Beta2D.setDecimals(3)
        self.dsb_Beta2D.setMinimum(-1.0)
        self.dsb_Beta2D.setMaximum(1.0)
        self.dsb_Beta2D.setSingleStep(0.1)
        self.dsb_Beta2D.setObjectName("dsb_Beta2D")
        self.dsb_Beta4D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta4D.setGeometry(QtCore.QRect(120, 200, 69, 27))
        self.dsb_Beta4D.setDecimals(3)
        self.dsb_Beta4D.setMinimum(-1.0)
        self.dsb_Beta4D.setMaximum(1.0)
        self.dsb_Beta4D.setSingleStep(0.1)
        self.dsb_Beta4D.setObjectName("dsb_Beta4D")
        self.dsb_Beta6D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta6D.setGeometry(QtCore.QRect(120, 230, 69, 27))
        self.dsb_Beta6D.setDecimals(3)
        self.dsb_Beta6D.setMinimum(-1.0)
        self.dsb_Beta6D.setMaximum(1.0)
        self.dsb_Beta6D.setSingleStep(0.1)
        self.dsb_Beta6D.setObjectName("dsb_Beta6D")
        self.optionsTabWidget.addTab(self.iniTab, "")
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName("configTab")
        self.label_12 = QtGui.QLabel(self.configTab)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 67, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.configTab)
        self.label_13.setGeometry(QtCore.QRect(20, 30, 81, 31))
        self.label_13.setObjectName("label_13")
        self.b_chooseConfigFolder = QtGui.QPushButton(self.configTab)
        self.b_chooseConfigFolder.setGeometry(QtCore.QRect(90, 30, 99, 27))
        self.b_chooseConfigFolder.setObjectName("b_chooseConfigFolder")
        self.label_14 = QtGui.QLabel(self.configTab)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 131, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.configTab)
        self.label_15.setGeometry(QtCore.QRect(200, 26, 51, 31))
        self.label_15.setObjectName("label_15")
        self.le_configPrefix = QtGui.QLineEdit(self.configTab)
        self.le_configPrefix.setGeometry(QtCore.QRect(250, 30, 113, 27))
        self.le_configPrefix.setObjectName("le_configPrefix")
        self.label_16 = QtGui.QLabel(self.configTab)
        self.label_16.setGeometry(QtCore.QRect(20, 90, 67, 31))
        self.label_16.setObjectName("label_16")
        self.dsb_energyMargin = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_energyMargin.setGeometry(QtCore.QRect(280, 90, 91, 27))
        self.dsb_energyMargin.setDecimals(1)
        self.dsb_energyMargin.setProperty("value", 1.0)
        self.dsb_energyMargin.setObjectName("dsb_energyMargin")
        self.label_17 = QtGui.QLabel(self.configTab)
        self.label_17.setGeometry(QtCore.QRect(170, 90, 111, 31))
        self.label_17.setObjectName("label_17")
        self.cb_forceSpin = QtGui.QCheckBox(self.configTab)
        self.cb_forceSpin.setGeometry(QtCore.QRect(20, 120, 121, 22))
        self.cb_forceSpin.setChecked(True)
        self.cb_forceSpin.setObjectName("cb_forceSpin")
        self.cb_nmeMethod = QtGui.QComboBox(self.configTab)
        self.cb_nmeMethod.setGeometry(QtCore.QRect(90, 90, 71, 27))
        self.cb_nmeMethod.setObjectName("cb_nmeMethod")
        self.cb_reverseGhallagher = QtGui.QCheckBox(self.configTab)
        self.cb_reverseGhallagher.setGeometry(QtCore.QRect(190, 120, 181, 22))
        self.cb_reverseGhallagher.setObjectName("cb_reverseGhallagher")
        self.cb_overrideCoupling = QtGui.QCheckBox(self.configTab)
        self.cb_overrideCoupling.setGeometry(QtCore.QRect(20, 150, 181, 22))
        self.cb_overrideCoupling.setObjectName("cb_overrideCoupling")
        self.label_18 = QtGui.QLabel(self.configTab)
        self.label_18.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.label_18.setObjectName("label_18")
        self.cb_potential = QtGui.QComboBox(self.configTab)
        self.cb_potential.setGeometry(QtCore.QRect(110, 180, 85, 27))
        self.cb_potential.setObjectName("cb_potential")
        self.label_19 = QtGui.QLabel(self.configTab)
        self.label_19.setGeometry(QtCore.QRect(20, 210, 91, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.configTab)
        self.label_20.setGeometry(QtCore.QRect(20, 240, 91, 31))
        self.label_20.setObjectName("label_20")
        self.dsb_V0n = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0n.setGeometry(QtCore.QRect(110, 210, 69, 27))
        self.dsb_V0n.setProperty("value", 49.6)
        self.dsb_V0n.setObjectName("dsb_V0n")
        self.dsb_V0p = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0p.setGeometry(QtCore.QRect(110, 240, 69, 27))
        self.dsb_V0p.setProperty("value", 49.6)
        self.dsb_V0p.setObjectName("dsb_V0p")
        self.label_21 = QtGui.QLabel(self.configTab)
        self.label_21.setGeometry(QtCore.QRect(20, 270, 81, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.configTab)
        self.label_22.setGeometry(QtCore.QRect(190, 270, 71, 31))
        self.label_22.setObjectName("label_22")
        self.dsb_Xn = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_Xn.setGeometry(QtCore.QRect(110, 270, 69, 27))
        self.dsb_Xn.setProperty("value", 0.86)
        self.dsb_Xn.setObjectName("dsb_Xn")
        self.dsb_Xp = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_Xp.setGeometry(QtCore.QRect(300, 270, 69, 27))
        self.dsb_Xp.setProperty("value", 0.86)
        self.dsb_Xp.setObjectName("dsb_Xp")
        self.label_23 = QtGui.QLabel(self.configTab)
        self.label_23.setGeometry(QtCore.QRect(190, 210, 111, 31))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.configTab)
        self.label_24.setGeometry(QtCore.QRect(190, 240, 101, 31))
        self.label_24.setObjectName("label_24")
        self.dsb_V0Sn = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0Sn.setGeometry(QtCore.QRect(300, 210, 69, 27))
        self.dsb_V0Sn.setProperty("value", 7.2)
        self.dsb_V0Sn.setObjectName("dsb_V0Sn")
        self.dsb_V0Sp = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0Sp.setGeometry(QtCore.QRect(300, 240, 69, 27))
        self.dsb_V0Sp.setProperty("value", 7.2)
        self.dsb_V0Sp.setObjectName("dsb_V0Sp")
        self.label_25 = QtGui.QLabel(self.configTab)
        self.label_25.setGeometry(QtCore.QRect(10, 300, 81, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.configTab)
        self.label_26.setGeometry(QtCore.QRect(20, 320, 67, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.configTab)
        self.label_27.setGeometry(QtCore.QRect(20, 350, 67, 17))
        self.label_27.setObjectName("label_27")
        self.dsb_gA = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_gA.setGeometry(QtCore.QRect(88, 320, 81, 27))
        self.dsb_gA.setDecimals(4)
        self.dsb_gA.setProperty("value", 1.2723)
        self.dsb_gA.setObjectName("dsb_gA")
        self.dsb_gAeff = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_gAeff.setGeometry(QtCore.QRect(88, 350, 81, 27))
        self.dsb_gAeff.setProperty("value", 1.0)
        self.dsb_gAeff.setObjectName("dsb_gAeff")
        self.label_28 = QtGui.QLabel(self.configTab)
        self.label_28.setGeometry(QtCore.QRect(20, 380, 67, 17))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtGui.QLabel(self.configTab)
        self.label_29.setGeometry(QtCore.QRect(190, 316, 67, 31))
        self.label_29.setObjectName("label_29")
        self.dsb_gM = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_gM.setGeometry(QtCore.QRect(230, 320, 81, 27))
        self.dsb_gM.setDecimals(3)
        self.dsb_gM.setProperty("value", 4.706)
        self.dsb_gM.setObjectName("dsb_gM")
        self.dsb_gP = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_gP.setGeometry(QtCore.QRect(90, 380, 81, 27))
        self.dsb_gP.setProperty("value", 1.0)
        self.dsb_gP.setObjectName("dsb_gP")
        self.b_saveConfigFile = QtGui.QPushButton(self.configTab)
        self.b_saveConfigFile.setGeometry(QtCore.QRect(180, 360, 99, 51))
        self.b_saveConfigFile.setObjectName("b_saveConfigFile")
        self.b_loadConfigFile = QtGui.QPushButton(self.configTab)
        self.b_loadConfigFile.setGeometry(QtCore.QRect(280, 360, 91, 51))
        self.b_loadConfigFile.setObjectName("b_loadConfigFile")
        self.optionsTabWidget.addTab(self.configTab, "")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(520, 480, 361, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lab_logo = QtGui.QLabel(self.centralwidget)
        self.lab_logo.setGeometry(QtCore.QRect(-10, 10, 481, 101))
        self.lab_logo.setText("")
        self.lab_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.lab_logo.setObjectName("lab_logo")
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 120, 491, 551))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.bsgMainTab = QtGui.QWidget()
        self.bsgMainTab.setObjectName("bsgMainTab")
        self.horizontalLayoutWidget = QtGui.QWidget(self.bsgMainTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 471, 351))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gv_plotSpectrum = PlotWidget(self.horizontalLayoutWidget)
        self.gv_plotSpectrum.setObjectName("gv_plotSpectrum")
        self.horizontalLayout.addWidget(self.gv_plotSpectrum)
        self.b_runBSG = QtGui.QPushButton(self.bsgMainTab)
        self.b_runBSG.setGeometry(QtCore.QRect(350, 90, 111, 61))
        self.b_runBSG.setObjectName("b_runBSG")
        self.le_outputName = QtGui.QLineEdit(self.bsgMainTab)
        self.le_outputName.setGeometry(QtCore.QRect(350, 40, 113, 27))
        self.le_outputName.setObjectName("le_outputName")
        self.label_10 = QtGui.QLabel(self.bsgMainTab)
        self.label_10.setGeometry(QtCore.QRect(350, 10, 121, 21))
        self.label_10.setObjectName("label_10")
        self.label_30 = QtGui.QLabel(self.bsgMainTab)
        self.label_30.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.label_30.setObjectName("label_30")
        self.b_changeIni = QtGui.QPushButton(self.bsgMainTab)
        self.b_changeIni.setGeometry(QtCore.QRect(240, 40, 81, 27))
        self.b_changeIni.setObjectName("b_changeIni")
        self.label_31 = QtGui.QLabel(self.bsgMainTab)
        self.label_31.setGeometry(QtCore.QRect(10, 70, 121, 31))
        self.label_31.setObjectName("label_31")
        self.b_changeConfig = QtGui.QPushButton(self.bsgMainTab)
        self.b_changeConfig.setGeometry(QtCore.QRect(240, 70, 81, 27))
        self.b_changeConfig.setObjectName("b_changeConfig")
        self.l_bsgIni = QtGui.QLabel(self.bsgMainTab)
        self.l_bsgIni.setGeometry(QtCore.QRect(70, 40, 161, 31))
        self.l_bsgIni.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_bsgIni.setObjectName("l_bsgIni")
        self.label_33 = QtGui.QLabel(self.bsgMainTab)
        self.label_33.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.label_33.setObjectName("label_33")
        self.b_changeProfile = QtGui.QPushButton(self.bsgMainTab)
        self.b_changeProfile.setGeometry(QtCore.QRect(240, 100, 81, 27))
        self.b_changeProfile.setObjectName("b_changeProfile")
        self.l_bsgConfig = QtGui.QLabel(self.bsgMainTab)
        self.l_bsgConfig.setGeometry(QtCore.QRect(90, 70, 141, 31))
        self.l_bsgConfig.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_bsgConfig.setObjectName("l_bsgConfig")
        self.l_bsgProfile = QtGui.QLabel(self.bsgMainTab)
        self.l_bsgProfile.setGeometry(QtCore.QRect(90, 100, 141, 31))
        self.l_bsgProfile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_bsgProfile.setObjectName("l_bsgProfile")
        self.label_41 = QtGui.QLabel(self.bsgMainTab)
        self.label_41.setGeometry(QtCore.QRect(10, 16, 121, 21))
        self.label_41.setObjectName("label_41")
        self.l_bsgExec = QtGui.QLabel(self.bsgMainTab)
        self.l_bsgExec.setGeometry(QtCore.QRect(126, 10, 101, 31))
        self.l_bsgExec.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_bsgExec.setObjectName("l_bsgExec")
        self.b_changeBSGExec = QtGui.QPushButton(self.bsgMainTab)
        self.b_changeBSGExec.setGeometry(QtCore.QRect(240, 10, 81, 27))
        self.b_changeBSGExec.setObjectName("b_changeBSGExec")
        self.label_42 = QtGui.QLabel(self.bsgMainTab)
        self.label_42.setGeometry(QtCore.QRect(10, 130, 111, 31))
        self.label_42.setObjectName("label_42")
        self.l_bsgExchange = QtGui.QLabel(self.bsgMainTab)
        self.l_bsgExchange.setGeometry(QtCore.QRect(120, 130, 111, 31))
        self.l_bsgExchange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_bsgExchange.setObjectName("l_bsgExchange")
        self.b_bsgExchange = QtGui.QPushButton(self.bsgMainTab)
        self.b_bsgExchange.setGeometry(QtCore.QRect(240, 130, 81, 27))
        self.b_bsgExchange.setObjectName("b_bsgExchange")
        self.mainTabWidget.addTab(self.bsgMainTab, "")
        self.bsgOptionsTab = QtGui.QWidget()
        self.bsgOptionsTab.setObjectName("bsgOptionsTab")
        self.groupBox_2 = QtGui.QGroupBox(self.bsgOptionsTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 471, 511))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.cb_phasespace = QtGui.QCheckBox(self.groupBox_2)
        self.cb_phasespace.setGeometry(QtCore.QRect(10, 30, 131, 22))
        self.cb_phasespace.setChecked(True)
        self.cb_phasespace.setObjectName("cb_phasespace")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 67, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cb_fermi = QtGui.QCheckBox(self.groupBox_2)
        self.cb_fermi.setGeometry(QtCore.QRect(10, 60, 151, 22))
        self.cb_fermi.setChecked(True)
        self.cb_fermi.setObjectName("cb_fermi")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 141, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cb_radiative = QtGui.QCheckBox(self.groupBox_2)
        self.cb_radiative.setGeometry(QtCore.QRect(10, 90, 181, 22))
        self.cb_radiative.setChecked(True)
        self.cb_radiative.setObjectName("cb_radiative")
        self.cb_efs = QtGui.QCheckBox(self.groupBox_2)
        self.cb_efs.setGeometry(QtCore.QRect(10, 150, 151, 22))
        self.cb_efs.setChecked(True)
        self.cb_efs.setObjectName("cb_efs")
        self.cb_ens = QtGui.QCheckBox(self.groupBox_2)
        self.cb_ens.setGeometry(QtCore.QRect(10, 180, 171, 22))
        self.cb_ens.setChecked(True)
        self.cb_ens.setObjectName("cb_ens")
        self.cb_efs_deformation = QtGui.QCheckBox(self.groupBox_2)
        self.cb_efs_deformation.setGeometry(QtCore.QRect(10, 240, 151, 31))
        self.cb_efs_deformation.setChecked(True)
        self.cb_efs_deformation.setObjectName("cb_efs_deformation")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(230, 0, 111, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cb_recoil = QtGui.QCheckBox(self.groupBox_2)
        self.cb_recoil.setGeometry(QtCore.QRect(230, 30, 141, 22))
        self.cb_recoil.setChecked(True)
        self.cb_recoil.setObjectName("cb_recoil")
        self.cb_Q = QtGui.QCheckBox(self.groupBox_2)
        self.cb_Q.setGeometry(QtCore.QRect(230, 60, 141, 22))
        self.cb_Q.setChecked(True)
        self.cb_Q.setObjectName("cb_Q")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(230, 90, 67, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cb_screening = QtGui.QCheckBox(self.groupBox_2)
        self.cb_screening.setGeometry(QtCore.QRect(230, 120, 171, 22))
        self.cb_screening.setChecked(True)
        self.cb_screening.setObjectName("cb_screening")
        self.cb_exchange = QtGui.QCheckBox(self.groupBox_2)
        self.cb_exchange.setGeometry(QtCore.QRect(230, 150, 171, 22))
        self.cb_exchange.setChecked(True)
        self.cb_exchange.setObjectName("cb_exchange")
        self.cb_shape = QtGui.QComboBox(self.groupBox_2)
        self.cb_shape.setGeometry(QtCore.QRect(30, 210, 121, 27))
        self.cb_shape.setObjectName("cb_shape")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 280, 141, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cb_C = QtGui.QCheckBox(self.groupBox_2)
        self.cb_C.setGeometry(QtCore.QRect(10, 300, 121, 31))
        self.cb_C.setChecked(True)
        self.cb_C.setObjectName("cb_C")
        self.cb_isovector = QtGui.QCheckBox(self.groupBox_2)
        self.cb_isovector.setGeometry(QtCore.QRect(10, 360, 181, 22))
        self.cb_isovector.setChecked(True)
        self.cb_isovector.setObjectName("cb_isovector")
        self.cb_coupled = QtGui.QCheckBox(self.groupBox_2)
        self.cb_coupled.setGeometry(QtCore.QRect(40, 380, 91, 31))
        self.cb_coupled.setObjectName("cb_coupled")
        self.cb_C_deformation = QtGui.QCheckBox(self.groupBox_2)
        self.cb_C_deformation.setGeometry(QtCore.QRect(10, 410, 121, 22))
        self.cb_C_deformation.setChecked(True)
        self.cb_C_deformation.setObjectName("cb_C_deformation")
        self.cb_C_shape = QtGui.QComboBox(self.groupBox_2)
        self.cb_C_shape.setGeometry(QtCore.QRect(30, 330, 121, 27))
        self.cb_C_shape.setObjectName("cb_C_shape")
        self.cb_relativistic = QtGui.QCheckBox(self.groupBox_2)
        self.cb_relativistic.setGeometry(QtCore.QRect(10, 440, 111, 22))
        self.cb_relativistic.setChecked(True)
        self.cb_relativistic.setObjectName("cb_relativistic")
        self.b_enable_all = QtGui.QPushButton(self.groupBox_2)
        self.b_enable_all.setGeometry(QtCore.QRect(260, 470, 101, 31))
        self.b_enable_all.setObjectName("b_enable_all")
        self.b_disable_all = QtGui.QPushButton(self.groupBox_2)
        self.b_disable_all.setGeometry(QtCore.QRect(370, 470, 101, 31))
        self.b_disable_all.setObjectName("b_disable_all")
        self.b_load_profile = QtGui.QPushButton(self.groupBox_2)
        self.b_load_profile.setGeometry(QtCore.QRect(10, 470, 111, 31))
        self.b_load_profile.setObjectName("b_load_profile")
        self.b_save_profile = QtGui.QPushButton(self.groupBox_2)
        self.b_save_profile.setGeometry(QtCore.QRect(130, 470, 121, 31))
        self.b_save_profile.setObjectName("b_save_profile")
        self.cb_mismatch = QtGui.QCheckBox(self.groupBox_2)
        self.cb_mismatch.setGeometry(QtCore.QRect(230, 180, 181, 31))
        self.cb_mismatch.setChecked(True)
        self.cb_mismatch.setObjectName("cb_mismatch")
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(230, 220, 131, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(230, 250, 41, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(360, 240, 41, 41))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(230, 280, 61, 31))
        self.label_36.setObjectName("label_36")
        self.dsb_bAc = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_bAc.setGeometry(QtCore.QRect(280, 250, 69, 27))
        self.dsb_bAc.setObjectName("dsb_bAc")
        self.dsb_dAc = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_dAc.setGeometry(QtCore.QRect(400, 250, 69, 27))
        self.dsb_dAc.setObjectName("dsb_dAc")
        self.dsb_lambda = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_lambda.setGeometry(QtCore.QRect(280, 280, 69, 27))
        self.dsb_lambda.setObjectName("dsb_lambda")
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(230, 320, 81, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(240, 340, 67, 41))
        self.label_38.setObjectName("label_38")
        self.dsb_begin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_begin.setGeometry(QtCore.QRect(290, 350, 121, 27))
        self.dsb_begin.setMaximum(10000.0)
        self.dsb_begin.setProperty("value", 0.1)
        self.dsb_begin.setObjectName("dsb_begin")
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(240, 376, 41, 31))
        self.label_39.setObjectName("label_39")
        self.dsb_end = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_end.setGeometry(QtCore.QRect(290, 380, 121, 27))
        self.dsb_end.setObjectName("dsb_end")
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(240, 406, 41, 31))
        self.label_40.setObjectName("label_40")
        self.dsb_step = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_step.setGeometry(QtCore.QRect(290, 410, 121, 27))
        self.dsb_step.setObjectName("dsb_step")
        self.mainTabWidget.addTab(self.bsgOptionsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.optionsTabWidget.setCurrentIndex(0)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Transition", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Mixing Ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Q value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Q.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.group_M.setTitle(QtGui.QApplication.translate("MainWindow", "Mother", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZM.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AM.setText(QtGui.QApplication.translate("MainWindow", "A:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RM.setText(QtGui.QApplication.translate("MainWindow", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JM.setText(QtGui.QApplication.translate("MainWindow", "Spin:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2M.setText(QtGui.QApplication.translate("MainWindow", "Beta2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4M.setText(QtGui.QApplication.translate("MainWindow", "Beta4:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6M.setText(QtGui.QApplication.translate("MainWindow", "Beta6:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiM.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setSuffix(QtGui.QApplication.translate("MainWindow", " fm", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "File info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current file:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_iniFilename.setText(QtGui.QApplication.translate("MainWindow", "Filename placeholder", None, QtGui.QApplication.UnicodeUTF8))
        self.b_load_ini.setText(QtGui.QApplication.translate("MainWindow", "Load .ini file", None, QtGui.QApplication.UnicodeUTF8))
        self.b_save_ini.setText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.group_M_2.setTitle(QtGui.QApplication.translate("MainWindow", "Daughter", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZD.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AD.setText(QtGui.QApplication.translate("MainWindow", "A:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RD.setText(QtGui.QApplication.translate("MainWindow", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JD.setText(QtGui.QApplication.translate("MainWindow", "Spin:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2D.setText(QtGui.QApplication.translate("MainWindow", "Beta2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4D.setText(QtGui.QApplication.translate("MainWindow", "Beta4:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6D.setText(QtGui.QApplication.translate("MainWindow", "Beta6:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiD.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setSuffix(QtGui.QApplication.translate("MainWindow", " fm", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.iniTab), QtGui.QApplication.translate("MainWindow", "Transition Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "General:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chooseConfigFolder.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Computational:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_energyMargin.setSuffix(QtGui.QApplication.translate("MainWindow", " MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Energy Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_forceSpin.setText(QtGui.QApplication.translate("MainWindow", "Force Spin", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_reverseGhallagher.setText(QtGui.QApplication.translate("MainWindow", "Reversed Ghallagher", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_overrideCoupling.setText(QtGui.QApplication.translate("MainWindow", "Override SP coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Potential:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "V0 neutrons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "V0 protons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "X neutron:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "X proton:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "V0S neutrons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "V0S protons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Constants:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "gA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "gA_eff:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "gP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "gM:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_saveConfigFile.setText(QtGui.QApplication.translate("MainWindow", "Save config\n"
"file", None, QtGui.QApplication.UnicodeUTF8))
        self.b_loadConfigFile.setText(QtGui.QApplication.translate("MainWindow", "Load config\n"
"file", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Configuration Options", None, QtGui.QApplication.UnicodeUTF8))
        self.b_runBSG.setText(QtGui.QApplication.translate("MainWindow", "Run!", None, QtGui.QApplication.UnicodeUTF8))
        self.le_outputName.setText(QtGui.QApplication.translate("MainWindow", "output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Output name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Ini file:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_changeIni.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Config file:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_changeConfig.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.l_bsgIni.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Profile file:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_changeProfile.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.l_bsgConfig.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.l_bsgProfile.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "BSG executable:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_bsgExec.setText(QtGui.QApplication.translate("MainWindow", "BSG", None, QtGui.QApplication.UnicodeUTF8))
        self.b_changeBSGExec.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Exchange data:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_bsgExchange.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.b_bsgExchange.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgMainTab), QtGui.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_phasespace.setText(QtGui.QApplication.translate("MainWindow", "Phase Space", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Basic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fermi.setText(QtGui.QApplication.translate("MainWindow", "Fermi Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Electrostatic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_radiative.setText(QtGui.QApplication.translate("MainWindow", "Radiative corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs.setText(QtGui.QApplication.translate("MainWindow", "ES Finite Size", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ens.setText(QtGui.QApplication.translate("MainWindow", "ES Nuclear Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs_deformation.setText(QtGui.QApplication.translate("MainWindow", "ES Deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Kinematic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_recoil.setText(QtGui.QApplication.translate("MainWindow", "Nuclear Recoil", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Q.setText(QtGui.QApplication.translate("MainWindow", "Coulomb Recoil", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Atomic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_screening.setText(QtGui.QApplication.translate("MainWindow", "Screening", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_exchange.setText(QtGui.QApplication.translate("MainWindow", "Exchange", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Nuclear Structure:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C.setText(QtGui.QApplication.translate("MainWindow", "Shape factor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isovector.setText(QtGui.QApplication.translate("MainWindow", "Isovector Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setToolTip(QtGui.QApplication.translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setText(QtGui.QApplication.translate("MainWindow", "Coupled", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_deformation.setText(QtGui.QApplication.translate("MainWindow", "Deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_relativistic.setText(QtGui.QApplication.translate("MainWindow", "Relativistic", None, QtGui.QApplication.UnicodeUTF8))
        self.b_enable_all.setText(QtGui.QApplication.translate("MainWindow", "Enable All", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disable_all.setText(QtGui.QApplication.translate("MainWindow", "Disable All", None, QtGui.QApplication.UnicodeUTF8))
        self.b_load_profile.setText(QtGui.QApplication.translate("MainWindow", "Load Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.b_save_profile.setText(QtGui.QApplication.translate("MainWindow", "Save Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_mismatch.setText(QtGui.QApplication.translate("MainWindow", "Mismatch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Matrix Elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "b/Ac:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "d/Ac:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Λ:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Limits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Begin:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_begin.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_end.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_step.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgOptionsTab), QtGui.QApplication.translate("MainWindow", "Spectral Shape Options", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
