# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Tue Dec 12 12:11:23 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 779)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(550, 550, 381, 171))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 169))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.txt_lastActions = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.txt_lastActions.setGeometry(QtCore.QRect(0, 0, 381, 171))
        self.txt_lastActions.setObjectName("txt_lastActions")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.optionsTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.optionsTabWidget.setGeometry(QtCore.QRect(550, 20, 381, 511))
        self.optionsTabWidget.setObjectName("optionsTabWidget")
        self.iniTab = QtGui.QWidget()
        self.iniTab.setObjectName("iniTab")
        self.group_M = QtGui.QGroupBox(self.iniTab)
        self.group_M.setGeometry(QtCore.QRect(10, 190, 181, 291))
        self.group_M.setObjectName("group_M")
        self.lab_ZM = QtGui.QLabel(self.group_M)
        self.lab_ZM.setGeometry(QtCore.QRect(10, 20, 61, 31))
        self.lab_ZM.setObjectName("lab_ZM")
        self.lab_AM = QtGui.QLabel(self.group_M)
        self.lab_AM.setGeometry(QtCore.QRect(10, 50, 67, 31))
        self.lab_AM.setObjectName("lab_AM")
        self.lab_RM = QtGui.QLabel(self.group_M)
        self.lab_RM.setGeometry(QtCore.QRect(10, 80, 67, 31))
        self.lab_RM.setObjectName("lab_RM")
        self.lab_JM = QtGui.QLabel(self.group_M)
        self.lab_JM.setGeometry(QtCore.QRect(10, 110, 67, 31))
        self.lab_JM.setObjectName("lab_JM")
        self.lab_Beta2M = QtGui.QLabel(self.group_M)
        self.lab_Beta2M.setGeometry(QtCore.QRect(10, 170, 67, 31))
        self.lab_Beta2M.setObjectName("lab_Beta2M")
        self.lab_Beta4M = QtGui.QLabel(self.group_M)
        self.lab_Beta4M.setGeometry(QtCore.QRect(10, 200, 67, 31))
        self.lab_Beta4M.setObjectName("lab_Beta4M")
        self.lab_Beta6M = QtGui.QLabel(self.group_M)
        self.lab_Beta6M.setGeometry(QtCore.QRect(10, 226, 67, 31))
        self.lab_Beta6M.setObjectName("lab_Beta6M")
        self.lab_PiM = QtGui.QLabel(self.group_M)
        self.lab_PiM.setGeometry(QtCore.QRect(10, 140, 67, 31))
        self.lab_PiM.setObjectName("lab_PiM")
        self.sb_ZM = QtGui.QSpinBox(self.group_M)
        self.sb_ZM.setGeometry(QtCore.QRect(120, 20, 48, 27))
        self.sb_ZM.setObjectName("sb_ZM")
        self.sb_AM = QtGui.QSpinBox(self.group_M)
        self.sb_AM.setGeometry(QtCore.QRect(120, 50, 48, 27))
        self.sb_AM.setMaximum(250)
        self.sb_AM.setObjectName("sb_AM")
        self.dsb_RM = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_RM.setGeometry(QtCore.QRect(90, 80, 81, 27))
        self.dsb_RM.setSingleStep(0.1)
        self.dsb_RM.setObjectName("dsb_RM")
        self.dsb_JM = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_JM.setGeometry(QtCore.QRect(100, 110, 71, 27))
        self.dsb_JM.setDecimals(1)
        self.dsb_JM.setSingleStep(0.5)
        self.dsb_JM.setObjectName("dsb_JM")
        self.cb_PiM = QtGui.QComboBox(self.group_M)
        self.cb_PiM.setGeometry(QtCore.QRect(110, 140, 61, 27))
        self.cb_PiM.setObjectName("cb_PiM")
        self.dsb_Beta2M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta2M.setGeometry(QtCore.QRect(100, 170, 69, 27))
        self.dsb_Beta2M.setDecimals(3)
        self.dsb_Beta2M.setMinimum(-1.0)
        self.dsb_Beta2M.setMaximum(1.0)
        self.dsb_Beta2M.setSingleStep(0.1)
        self.dsb_Beta2M.setObjectName("dsb_Beta2M")
        self.dsb_Beta4M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta4M.setGeometry(QtCore.QRect(100, 200, 69, 27))
        self.dsb_Beta4M.setDecimals(3)
        self.dsb_Beta4M.setMinimum(-1.0)
        self.dsb_Beta4M.setMaximum(1.0)
        self.dsb_Beta4M.setSingleStep(0.1)
        self.dsb_Beta4M.setObjectName("dsb_Beta4M")
        self.dsb_Beta6M = QtGui.QDoubleSpinBox(self.group_M)
        self.dsb_Beta6M.setGeometry(QtCore.QRect(100, 230, 69, 27))
        self.dsb_Beta6M.setDecimals(3)
        self.dsb_Beta6M.setMinimum(-1.0)
        self.dsb_Beta6M.setMaximum(1.0)
        self.dsb_Beta6M.setSingleStep(0.1)
        self.dsb_Beta6M.setObjectName("dsb_Beta6M")
        self.label_31 = QtGui.QLabel(self.group_M)
        self.label_31.setGeometry(QtCore.QRect(10, 260, 67, 21))
        self.label_31.setObjectName("label_31")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.group_M)
        self.doubleSpinBox.setGeometry(QtCore.QRect(68, 260, 101, 27))
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setSingleStep(1.0)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.groupBox_3 = QtGui.QGroupBox(self.iniTab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 351, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(0, 30, 91, 21))
        self.label_11.setObjectName("label_11")
        self.l_iniFilename = QtGui.QLabel(self.groupBox_3)
        self.l_iniFilename.setGeometry(QtCore.QRect(190, 36, 161, 21))
        self.l_iniFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l_iniFilename.setObjectName("l_iniFilename")
        self.group_M_2 = QtGui.QGroupBox(self.iniTab)
        self.group_M_2.setGeometry(QtCore.QRect(190, 190, 181, 291))
        self.group_M_2.setObjectName("group_M_2")
        self.lab_ZD = QtGui.QLabel(self.group_M_2)
        self.lab_ZD.setGeometry(QtCore.QRect(10, 20, 61, 31))
        self.lab_ZD.setObjectName("lab_ZD")
        self.lab_AD = QtGui.QLabel(self.group_M_2)
        self.lab_AD.setGeometry(QtCore.QRect(10, 50, 67, 31))
        self.lab_AD.setObjectName("lab_AD")
        self.lab_RD = QtGui.QLabel(self.group_M_2)
        self.lab_RD.setGeometry(QtCore.QRect(10, 80, 67, 31))
        self.lab_RD.setObjectName("lab_RD")
        self.lab_JD = QtGui.QLabel(self.group_M_2)
        self.lab_JD.setGeometry(QtCore.QRect(10, 110, 67, 31))
        self.lab_JD.setObjectName("lab_JD")
        self.lab_Beta2D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta2D.setGeometry(QtCore.QRect(10, 170, 67, 31))
        self.lab_Beta2D.setObjectName("lab_Beta2D")
        self.lab_Beta4D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta4D.setGeometry(QtCore.QRect(10, 200, 67, 31))
        self.lab_Beta4D.setObjectName("lab_Beta4D")
        self.lab_Beta6D = QtGui.QLabel(self.group_M_2)
        self.lab_Beta6D.setGeometry(QtCore.QRect(10, 226, 67, 31))
        self.lab_Beta6D.setObjectName("lab_Beta6D")
        self.lab_PiD = QtGui.QLabel(self.group_M_2)
        self.lab_PiD.setGeometry(QtCore.QRect(10, 140, 67, 31))
        self.lab_PiD.setObjectName("lab_PiD")
        self.sb_ZD = QtGui.QSpinBox(self.group_M_2)
        self.sb_ZD.setGeometry(QtCore.QRect(130, 20, 48, 27))
        self.sb_ZD.setObjectName("sb_ZD")
        self.sb_AD = QtGui.QSpinBox(self.group_M_2)
        self.sb_AD.setGeometry(QtCore.QRect(130, 50, 48, 27))
        self.sb_AD.setMaximum(250)
        self.sb_AD.setObjectName("sb_AD")
        self.dsb_RD = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_RD.setGeometry(QtCore.QRect(100, 80, 81, 27))
        self.dsb_RD.setSingleStep(0.1)
        self.dsb_RD.setObjectName("dsb_RD")
        self.dsb_JD = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_JD.setGeometry(QtCore.QRect(110, 110, 71, 27))
        self.dsb_JD.setDecimals(1)
        self.dsb_JD.setSingleStep(0.5)
        self.dsb_JD.setObjectName("dsb_JD")
        self.cb_PiD = QtGui.QComboBox(self.group_M_2)
        self.cb_PiD.setGeometry(QtCore.QRect(120, 140, 61, 27))
        self.cb_PiD.setObjectName("cb_PiD")
        self.dsb_Beta2D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta2D.setGeometry(QtCore.QRect(110, 170, 69, 27))
        self.dsb_Beta2D.setDecimals(3)
        self.dsb_Beta2D.setMinimum(-1.0)
        self.dsb_Beta2D.setMaximum(1.0)
        self.dsb_Beta2D.setSingleStep(0.1)
        self.dsb_Beta2D.setObjectName("dsb_Beta2D")
        self.dsb_Beta4D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta4D.setGeometry(QtCore.QRect(110, 200, 69, 27))
        self.dsb_Beta4D.setDecimals(3)
        self.dsb_Beta4D.setMinimum(-1.0)
        self.dsb_Beta4D.setMaximum(1.0)
        self.dsb_Beta4D.setSingleStep(0.1)
        self.dsb_Beta4D.setObjectName("dsb_Beta4D")
        self.dsb_Beta6D = QtGui.QDoubleSpinBox(self.group_M_2)
        self.dsb_Beta6D.setGeometry(QtCore.QRect(110, 230, 69, 27))
        self.dsb_Beta6D.setDecimals(3)
        self.dsb_Beta6D.setMinimum(-1.0)
        self.dsb_Beta6D.setMaximum(1.0)
        self.dsb_Beta6D.setSingleStep(0.1)
        self.dsb_Beta6D.setObjectName("dsb_Beta6D")
        self.label_33 = QtGui.QLabel(self.group_M_2)
        self.label_33.setGeometry(QtCore.QRect(10, 260, 67, 21))
        self.label_33.setObjectName("label_33")
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.group_M_2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(70, 260, 111, 27))
        self.doubleSpinBox_2.setMaximum(10000.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.groupBox = QtGui.QGroupBox(self.iniTab)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 371, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 21))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 67, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(180, 60, 67, 21))
        self.label_4.setObjectName("label_4")
        self.cb_type = QtGui.QComboBox(self.groupBox)
        self.cb_type.setGeometry(QtCore.QRect(60, 60, 111, 27))
        self.cb_type.setObjectName("cb_type")
        self.cb_process = QtGui.QComboBox(self.groupBox)
        self.cb_process.setGeometry(QtCore.QRect(90, 30, 81, 27))
        self.cb_process.setObjectName("cb_process")
        self.dsb_MixingRatio = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_MixingRatio.setGeometry(QtCore.QRect(270, 30, 91, 27))
        self.dsb_MixingRatio.setMaximum(100.0)
        self.dsb_MixingRatio.setObjectName("dsb_MixingRatio")
        self.dsb_Q = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_Q.setGeometry(QtCore.QRect(240, 60, 121, 27))
        self.dsb_Q.setMaximum(20000.0)
        self.dsb_Q.setObjectName("dsb_Q")
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(10, 86, 67, 31))
        self.label_30.setObjectName("label_30")
        self.dsb_halflife = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_halflife.setGeometry(QtCore.QRect(70, 90, 101, 27))
        self.dsb_halflife.setMaximum(1000000000.0)
        self.dsb_halflife.setObjectName("dsb_halflife")
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(180, 90, 67, 21))
        self.label_25.setObjectName("label_25")
        self.dsb_logft = QtGui.QDoubleSpinBox(self.groupBox)
        self.dsb_logft.setGeometry(QtCore.QRect(270, 90, 91, 27))
        self.dsb_logft.setMaximum(20.0)
        self.dsb_logft.setObjectName("dsb_logft")
        self.optionsTabWidget.addTab(self.iniTab, "")
        self.configTab = QtGui.QWidget()
        self.configTab.setObjectName("configTab")
        self.label_12 = QtGui.QLabel(self.configTab)
        self.label_12.setGeometry(QtCore.QRect(10, 0, 67, 31))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.configTab)
        self.label_13.setGeometry(QtCore.QRect(190, 20, 81, 31))
        self.label_13.setObjectName("label_13")
        self.b_chooseConfigFolder = QtGui.QPushButton(self.configTab)
        self.b_chooseConfigFolder.setGeometry(QtCore.QRect(270, 20, 99, 27))
        self.b_chooseConfigFolder.setObjectName("b_chooseConfigFolder")
        self.label_14 = QtGui.QLabel(self.configTab)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 131, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtGui.QLabel(self.configTab)
        self.label_16.setGeometry(QtCore.QRect(20, 90, 67, 31))
        self.label_16.setObjectName("label_16")
        self.dsb_energyMargin = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_energyMargin.setGeometry(QtCore.QRect(280, 90, 91, 27))
        self.dsb_energyMargin.setDecimals(1)
        self.dsb_energyMargin.setMaximum(20.0)
        self.dsb_energyMargin.setProperty("value", 1.0)
        self.dsb_energyMargin.setObjectName("dsb_energyMargin")
        self.label_17 = QtGui.QLabel(self.configTab)
        self.label_17.setGeometry(QtCore.QRect(170, 90, 111, 31))
        self.label_17.setObjectName("label_17")
        self.cb_forceSpin = QtGui.QCheckBox(self.configTab)
        self.cb_forceSpin.setGeometry(QtCore.QRect(20, 120, 121, 22))
        self.cb_forceSpin.setChecked(True)
        self.cb_forceSpin.setObjectName("cb_forceSpin")
        self.cb_nmeMethod = QtGui.QComboBox(self.configTab)
        self.cb_nmeMethod.setGeometry(QtCore.QRect(90, 90, 71, 27))
        self.cb_nmeMethod.setObjectName("cb_nmeMethod")
        self.cb_reverseGhallagher = QtGui.QCheckBox(self.configTab)
        self.cb_reverseGhallagher.setGeometry(QtCore.QRect(190, 120, 181, 22))
        self.cb_reverseGhallagher.setObjectName("cb_reverseGhallagher")
        self.cb_overrideCoupling = QtGui.QCheckBox(self.configTab)
        self.cb_overrideCoupling.setGeometry(QtCore.QRect(20, 150, 181, 22))
        self.cb_overrideCoupling.setObjectName("cb_overrideCoupling")
        self.label_18 = QtGui.QLabel(self.configTab)
        self.label_18.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.label_18.setObjectName("label_18")
        self.cb_potential = QtGui.QComboBox(self.configTab)
        self.cb_potential.setGeometry(QtCore.QRect(110, 180, 85, 27))
        self.cb_potential.setObjectName("cb_potential")
        self.label_19 = QtGui.QLabel(self.configTab)
        self.label_19.setGeometry(QtCore.QRect(20, 220, 91, 31))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.configTab)
        self.label_20.setGeometry(QtCore.QRect(20, 260, 91, 31))
        self.label_20.setObjectName("label_20")
        self.dsb_V0n = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0n.setGeometry(QtCore.QRect(110, 220, 69, 27))
        self.dsb_V0n.setProperty("value", 49.6)
        self.dsb_V0n.setObjectName("dsb_V0n")
        self.dsb_V0p = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0p.setGeometry(QtCore.QRect(110, 260, 69, 27))
        self.dsb_V0p.setProperty("value", 49.6)
        self.dsb_V0p.setObjectName("dsb_V0p")
        self.label_21 = QtGui.QLabel(self.configTab)
        self.label_21.setGeometry(QtCore.QRect(20, 300, 81, 31))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.configTab)
        self.label_22.setGeometry(QtCore.QRect(190, 300, 71, 31))
        self.label_22.setObjectName("label_22")
        self.dsb_Xn = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_Xn.setGeometry(QtCore.QRect(110, 300, 69, 27))
        self.dsb_Xn.setProperty("value", 0.86)
        self.dsb_Xn.setObjectName("dsb_Xn")
        self.dsb_Xp = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_Xp.setGeometry(QtCore.QRect(300, 300, 69, 27))
        self.dsb_Xp.setProperty("value", 0.86)
        self.dsb_Xp.setObjectName("dsb_Xp")
        self.label_23 = QtGui.QLabel(self.configTab)
        self.label_23.setGeometry(QtCore.QRect(190, 220, 111, 31))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.configTab)
        self.label_24.setGeometry(QtCore.QRect(190, 260, 101, 31))
        self.label_24.setObjectName("label_24")
        self.dsb_V0Sn = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0Sn.setGeometry(QtCore.QRect(300, 220, 69, 27))
        self.dsb_V0Sn.setProperty("value", 7.2)
        self.dsb_V0Sn.setObjectName("dsb_V0Sn")
        self.dsb_V0Sp = QtGui.QDoubleSpinBox(self.configTab)
        self.dsb_V0Sp.setGeometry(QtCore.QRect(300, 260, 69, 27))
        self.dsb_V0Sp.setProperty("value", 7.2)
        self.dsb_V0Sp.setObjectName("dsb_V0Sp")
        self.label_15 = QtGui.QLabel(self.configTab)
        self.label_15.setGeometry(QtCore.QRect(20, 26, 91, 21))
        self.label_15.setObjectName("label_15")
        self.l_currentConfigFile = QtGui.QLabel(self.configTab)
        self.l_currentConfigFile.setGeometry(QtCore.QRect(20, 50, 171, 21))
        self.l_currentConfigFile.setObjectName("l_currentConfigFile")
        self.groupBox_4 = QtGui.QGroupBox(self.configTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 340, 351, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 67, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 70, 67, 31))
        self.label_27.setObjectName("label_27")
        self.dsb_gA = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gA.setGeometry(QtCore.QRect(80, 30, 81, 27))
        self.dsb_gA.setDecimals(4)
        self.dsb_gA.setProperty("value", 1.2723)
        self.dsb_gA.setObjectName("dsb_gA")
        self.dsb_gAeff = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gAeff.setGeometry(QtCore.QRect(80, 70, 81, 27))
        self.dsb_gAeff.setProperty("value", 1.0)
        self.dsb_gAeff.setObjectName("dsb_gAeff")
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setGeometry(QtCore.QRect(190, 30, 67, 31))
        self.label_29.setObjectName("label_29")
        self.dsb_gM = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gM.setGeometry(QtCore.QRect(260, 30, 81, 27))
        self.dsb_gM.setDecimals(3)
        self.dsb_gM.setProperty("value", 4.706)
        self.dsb_gM.setObjectName("dsb_gM")
        self.dsb_gP = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.dsb_gP.setGeometry(QtCore.QRect(260, 70, 81, 27))
        self.dsb_gP.setMinimum(-1000.0)
        self.dsb_gP.setMaximum(1000.0)
        self.dsb_gP.setProperty("value", 0.0)
        self.dsb_gP.setObjectName("dsb_gP")
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(190, 60, 41, 31))
        self.label_28.setObjectName("label_28")
        self.optionsTabWidget.addTab(self.configTab, "")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(560, 530, 361, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lab_logo = QtGui.QLabel(self.centralwidget)
        self.lab_logo.setGeometry(QtCore.QRect(-10, 10, 481, 101))
        self.lab_logo.setAutoFillBackground(False)
        self.lab_logo.setFrameShadow(QtGui.QFrame.Raised)
        self.lab_logo.setText("")
        self.lab_logo.setPixmap(QtGui.QPixmap("logo.png"))
        self.lab_logo.setObjectName("lab_logo")
        self.mainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 120, 531, 601))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.bsgMainTab = QtGui.QWidget()
        self.bsgMainTab.setObjectName("bsgMainTab")
        self.horizontalLayoutWidget = QtGui.QWidget(self.bsgMainTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 511, 511))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gv_plotSpectrum = PlotWidget(self.horizontalLayoutWidget)
        self.gv_plotSpectrum.setObjectName("gv_plotSpectrum")
        self.horizontalLayout.addWidget(self.gv_plotSpectrum)
        self.b_runBSG = QtGui.QPushButton(self.bsgMainTab)
        self.b_runBSG.setGeometry(QtCore.QRect(260, 10, 101, 31))
        self.b_runBSG.setCursor(QtCore.Qt.OpenHandCursor)
        self.b_runBSG.setCheckable(False)
        self.b_runBSG.setChecked(False)
        self.b_runBSG.setDefault(False)
        self.b_runBSG.setFlat(False)
        self.b_runBSG.setObjectName("b_runBSG")
        self.le_outputName = QtGui.QLineEdit(self.bsgMainTab)
        self.le_outputName.setGeometry(QtCore.QRect(120, 10, 113, 27))
        self.le_outputName.setObjectName("le_outputName")
        self.label_10 = QtGui.QLabel(self.bsgMainTab)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 121, 41))
        self.label_10.setObjectName("label_10")
        self.mainTabWidget.addTab(self.bsgMainTab, "")
        self.bsgOptionsTab = QtGui.QWidget()
        self.bsgOptionsTab.setObjectName("bsgOptionsTab")
        self.groupBox_2 = QtGui.QGroupBox(self.bsgOptionsTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 511, 511))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.cb_phasespace = QtGui.QCheckBox(self.groupBox_2)
        self.cb_phasespace.setGeometry(QtCore.QRect(10, 20, 131, 22))
        self.cb_phasespace.setChecked(True)
        self.cb_phasespace.setObjectName("cb_phasespace")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 67, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cb_fermi = QtGui.QCheckBox(self.groupBox_2)
        self.cb_fermi.setGeometry(QtCore.QRect(10, 50, 151, 22))
        self.cb_fermi.setChecked(True)
        self.cb_fermi.setObjectName("cb_fermi")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 141, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cb_radiative = QtGui.QCheckBox(self.groupBox_2)
        self.cb_radiative.setGeometry(QtCore.QRect(10, 80, 181, 22))
        self.cb_radiative.setChecked(True)
        self.cb_radiative.setObjectName("cb_radiative")
        self.cb_efs = QtGui.QCheckBox(self.groupBox_2)
        self.cb_efs.setGeometry(QtCore.QRect(10, 140, 151, 22))
        self.cb_efs.setChecked(True)
        self.cb_efs.setObjectName("cb_efs")
        self.cb_ens = QtGui.QCheckBox(self.groupBox_2)
        self.cb_ens.setGeometry(QtCore.QRect(10, 170, 171, 22))
        self.cb_ens.setChecked(True)
        self.cb_ens.setObjectName("cb_ens")
        self.cb_efs_deformation = QtGui.QCheckBox(self.groupBox_2)
        self.cb_efs_deformation.setGeometry(QtCore.QRect(10, 230, 151, 31))
        self.cb_efs_deformation.setChecked(True)
        self.cb_efs_deformation.setObjectName("cb_efs_deformation")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(230, 0, 111, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cb_recoil = QtGui.QCheckBox(self.groupBox_2)
        self.cb_recoil.setGeometry(QtCore.QRect(240, 30, 141, 22))
        self.cb_recoil.setChecked(True)
        self.cb_recoil.setObjectName("cb_recoil")
        self.cb_Q = QtGui.QCheckBox(self.groupBox_2)
        self.cb_Q.setGeometry(QtCore.QRect(240, 60, 141, 22))
        self.cb_Q.setChecked(True)
        self.cb_Q.setObjectName("cb_Q")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(230, 90, 67, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cb_screening = QtGui.QCheckBox(self.groupBox_2)
        self.cb_screening.setGeometry(QtCore.QRect(240, 120, 171, 22))
        self.cb_screening.setChecked(True)
        self.cb_screening.setObjectName("cb_screening")
        self.cb_exchange = QtGui.QCheckBox(self.groupBox_2)
        self.cb_exchange.setGeometry(QtCore.QRect(240, 150, 171, 22))
        self.cb_exchange.setChecked(True)
        self.cb_exchange.setObjectName("cb_exchange")
        self.cb_shape = QtGui.QComboBox(self.groupBox_2)
        self.cb_shape.setGeometry(QtCore.QRect(30, 200, 121, 27))
        self.cb_shape.setObjectName("cb_shape")
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 270, 141, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cb_C = QtGui.QCheckBox(self.groupBox_2)
        self.cb_C.setGeometry(QtCore.QRect(10, 300, 121, 31))
        self.cb_C.setChecked(True)
        self.cb_C.setObjectName("cb_C")
        self.cb_isovector = QtGui.QCheckBox(self.groupBox_2)
        self.cb_isovector.setGeometry(QtCore.QRect(10, 360, 181, 22))
        self.cb_isovector.setChecked(True)
        self.cb_isovector.setObjectName("cb_isovector")
        self.cb_coupled = QtGui.QCheckBox(self.groupBox_2)
        self.cb_coupled.setGeometry(QtCore.QRect(40, 380, 91, 31))
        self.cb_coupled.setObjectName("cb_coupled")
        self.cb_C_deformation = QtGui.QCheckBox(self.groupBox_2)
        self.cb_C_deformation.setGeometry(QtCore.QRect(10, 410, 121, 22))
        self.cb_C_deformation.setChecked(True)
        self.cb_C_deformation.setObjectName("cb_C_deformation")
        self.cb_C_shape = QtGui.QComboBox(self.groupBox_2)
        self.cb_C_shape.setGeometry(QtCore.QRect(30, 330, 121, 27))
        self.cb_C_shape.setObjectName("cb_C_shape")
        self.cb_relativistic = QtGui.QCheckBox(self.groupBox_2)
        self.cb_relativistic.setGeometry(QtCore.QRect(10, 440, 111, 22))
        self.cb_relativistic.setChecked(True)
        self.cb_relativistic.setObjectName("cb_relativistic")
        self.b_enable_all = QtGui.QPushButton(self.groupBox_2)
        self.b_enable_all.setGeometry(QtCore.QRect(10, 470, 101, 31))
        self.b_enable_all.setObjectName("b_enable_all")
        self.b_disable_all = QtGui.QPushButton(self.groupBox_2)
        self.b_disable_all.setGeometry(QtCore.QRect(120, 470, 101, 31))
        self.b_disable_all.setObjectName("b_disable_all")
        self.cb_mismatch = QtGui.QCheckBox(self.groupBox_2)
        self.cb_mismatch.setGeometry(QtCore.QRect(240, 180, 181, 31))
        self.cb_mismatch.setChecked(True)
        self.cb_mismatch.setObjectName("cb_mismatch")
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(230, 220, 131, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(240, 250, 41, 21))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(370, 240, 41, 41))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(240, 280, 61, 31))
        self.label_36.setObjectName("label_36")
        self.dsb_bAc = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_bAc.setGeometry(QtCore.QRect(290, 250, 69, 27))
        self.dsb_bAc.setMinimum(-100.0)
        self.dsb_bAc.setMaximum(100.0)
        self.dsb_bAc.setObjectName("dsb_bAc")
        self.dsb_dAc = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_dAc.setGeometry(QtCore.QRect(420, 250, 69, 27))
        self.dsb_dAc.setMinimum(-100.0)
        self.dsb_dAc.setMaximum(100.0)
        self.dsb_dAc.setObjectName("dsb_dAc")
        self.dsb_lambda = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_lambda.setGeometry(QtCore.QRect(290, 280, 69, 27))
        self.dsb_lambda.setMinimum(-100.0)
        self.dsb_lambda.setMaximum(100.0)
        self.dsb_lambda.setObjectName("dsb_lambda")
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(230, 320, 81, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(240, 340, 67, 41))
        self.label_38.setObjectName("label_38")
        self.dsb_begin = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_begin.setGeometry(QtCore.QRect(300, 350, 121, 27))
        self.dsb_begin.setMaximum(20000.0)
        self.dsb_begin.setProperty("value", 0.0)
        self.dsb_begin.setObjectName("dsb_begin")
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(240, 380, 41, 41))
        self.label_39.setObjectName("label_39")
        self.dsb_end = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_end.setGeometry(QtCore.QRect(300, 390, 121, 27))
        self.dsb_end.setMaximum(20000.0)
        self.dsb_end.setObjectName("dsb_end")
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(240, 430, 41, 31))
        self.label_40.setObjectName("label_40")
        self.dsb_step = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.dsb_step.setGeometry(QtCore.QRect(300, 430, 121, 27))
        self.dsb_step.setMaximum(10000.0)
        self.dsb_step.setProperty("value", 0.1)
        self.dsb_step.setObjectName("dsb_step")
        self.cb_enforceNME = QtGui.QCheckBox(self.groupBox_2)
        self.cb_enforceNME.setGeometry(QtCore.QRect(370, 280, 121, 22))
        self.cb_enforceNME.setObjectName("cb_enforceNME")
        self.mainTabWidget.addTab(self.bsgOptionsTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 944, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtGui.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuOpen = QtGui.QMenu(self.menu_File)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtGui.QMenu(self.menu_File)
        self.menuSave.setObjectName("menuSave")
        self.menuComponent_paths = QtGui.QMenu(self.menu_File)
        self.menuComponent_paths.setObjectName("menuComponent_paths")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPlotting = QtGui.QMenu(self.menuBar)
        self.menuPlotting.setObjectName("menuPlotting")
        self.menuDatabase = QtGui.QMenu(self.menuBar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menuBar)
        self.a_exit = QtGui.QAction(MainWindow)
        self.a_exit.setObjectName("a_exit")
        self.a_loadIni = QtGui.QAction(MainWindow)
        self.a_loadIni.setObjectName("a_loadIni")
        self.a_loadConfig = QtGui.QAction(MainWindow)
        self.a_loadConfig.setObjectName("a_loadConfig")
        self.a_about = QtGui.QAction(MainWindow)
        self.a_about.setObjectName("a_about")
        self.a_feedback = QtGui.QAction(MainWindow)
        self.a_feedback.setObjectName("a_feedback")
        self.a_saveIni = QtGui.QAction(MainWindow)
        self.a_saveIni.setObjectName("a_saveIni")
        self.a_saveConfig = QtGui.QAction(MainWindow)
        self.a_saveConfig.setObjectName("a_saveConfig")
        self.a_new = QtGui.QAction(MainWindow)
        self.a_new.setObjectName("a_new")
        self.a_bsgExec = QtGui.QAction(MainWindow)
        self.a_bsgExec.setObjectName("a_bsgExec")
        self.a_exchangeData = QtGui.QAction(MainWindow)
        self.a_exchangeData.setObjectName("a_exchangeData")
        self.a_clearPlots = QtGui.QAction(MainWindow)
        self.a_clearPlots.setObjectName("a_clearPlots")
        self.a_exportPlot = QtGui.QAction(MainWindow)
        self.a_exportPlot.setObjectName("a_exportPlot")
        self.a_plotColorSettings = QtGui.QAction(MainWindow)
        self.a_plotColorSettings.setObjectName("a_plotColorSettings")
        self.a_loadDeformation = QtGui.QAction(MainWindow)
        self.a_loadDeformation.setObjectName("a_loadDeformation")
        self.a_loadRadii = QtGui.QAction(MainWindow)
        self.a_loadRadii.setObjectName("a_loadRadii")
        self.a_findTransition = QtGui.QAction(MainWindow)
        self.a_findTransition.setObjectName("a_findTransition")
        self.menuOpen.addAction(self.a_loadIni)
        self.menuOpen.addAction(self.a_loadConfig)
        self.menuSave.addAction(self.a_saveIni)
        self.menuSave.addAction(self.a_saveConfig)
        self.menuComponent_paths.addAction(self.a_bsgExec)
        self.menuComponent_paths.addAction(self.a_exchangeData)
        self.menu_File.addAction(self.a_new)
        self.menu_File.addAction(self.menuComponent_paths.menuAction())
        self.menu_File.addAction(self.menuOpen.menuAction())
        self.menu_File.addAction(self.menuSave.menuAction())
        self.menu_File.addAction(self.a_exit)
        self.menuHelp.addAction(self.a_feedback)
        self.menuHelp.addAction(self.a_about)
        self.menuPlotting.addAction(self.a_clearPlots)
        self.menuPlotting.addAction(self.a_exportPlot)
        self.menuPlotting.addAction(self.a_plotColorSettings)
        self.menuDatabase.addAction(self.a_loadDeformation)
        self.menuDatabase.addAction(self.a_loadRadii)
        self.menuDatabase.addAction(self.a_findTransition)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())
        self.menuBar.addAction(self.menuPlotting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.optionsTabWidget.setCurrentIndex(0)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.group_M.setTitle(QtGui.QApplication.translate("MainWindow", "Mother", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZM.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AM.setText(QtGui.QApplication.translate("MainWindow", "A:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RM.setText(QtGui.QApplication.translate("MainWindow", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JM.setText(QtGui.QApplication.translate("MainWindow", "Spin:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2M.setText(QtGui.QApplication.translate("MainWindow", "Beta2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4M.setText(QtGui.QApplication.translate("MainWindow", "Beta4:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6M.setText(QtGui.QApplication.translate("MainWindow", "Beta6:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiM.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RM.setSuffix(QtGui.QApplication.translate("MainWindow", " fm", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PiM.setStatusTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta2M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta4M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta6M.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the parent level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the parent level", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "File info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Current file:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_iniFilename.setStatusTip(QtGui.QApplication.translate("MainWindow", "Current file used for the transition", None, QtGui.QApplication.UnicodeUTF8))
        self.l_iniFilename.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.group_M_2.setTitle(QtGui.QApplication.translate("MainWindow", "Daughter", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_ZD.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_AD.setText(QtGui.QApplication.translate("MainWindow", "A:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_RD.setText(QtGui.QApplication.translate("MainWindow", "Radius:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_JD.setText(QtGui.QApplication.translate("MainWindow", "Spin:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta2D.setText(QtGui.QApplication.translate("MainWindow", "Beta2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta4D.setText(QtGui.QApplication.translate("MainWindow", "Beta4:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_Beta6D.setText(QtGui.QApplication.translate("MainWindow", "Beta6:", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_PiD.setText(QtGui.QApplication.translate("MainWindow", "Parity:", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_ZD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_AD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mass number", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Charge radius", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_RD.setSuffix(QtGui.QApplication.translate("MainWindow", " fm", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_JD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Spin in units of HBAR", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_PiD.setStatusTip(QtGui.QApplication.translate("MainWindow", "Parity of nuclear level", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta2D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quadrupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta4D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hexadecupole deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Beta6D.setStatusTip(QtGui.QApplication.translate("MainWindow", "Beta6 deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the child level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Excitation energy of the child level", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_2.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Transition", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Process:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Mixing Ratio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Q value: ", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_type.setStatusTip(QtGui.QApplication.translate("MainWindow", "Decay type", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_process.setStatusTip(QtGui.QApplication.translate("MainWindow", "Decay process", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_MixingRatio.setStatusTip(QtGui.QApplication.translate("MainWindow", "Mixing ratio as M_F/M_GT", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Q.setStatusTip(QtGui.QApplication.translate("MainWindow", "Q Value in keV", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_Q.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Halflife:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_halflife.setSuffix(QtGui.QApplication.translate("MainWindow", " s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Log ft:", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.iniTab), QtGui.QApplication.translate("MainWindow", "Transition Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_chooseConfigFolder.setText(QtGui.QApplication.translate("MainWindow", "Choose...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Computational", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_energyMargin.setSuffix(QtGui.QApplication.translate("MainWindow", " MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Energy Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_forceSpin.setText(QtGui.QApplication.translate("MainWindow", "Force Spin", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_reverseGhallagher.setText(QtGui.QApplication.translate("MainWindow", "Reversed Ghallagher", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_overrideCoupling.setText(QtGui.QApplication.translate("MainWindow", "Override SP coupling", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Potential:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "V0 neutrons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "V0 protons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "X neutron:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "X proton:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "V0S neutrons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "V0S protons", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Current file:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_currentConfigFile.setText(QtGui.QApplication.translate("MainWindow", "(blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Constants", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "gA:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "gA_eff:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "gM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "gP:", None, QtGui.QApplication.UnicodeUTF8))
        self.optionsTabWidget.setTabText(self.optionsTabWidget.indexOf(self.configTab), QtGui.QApplication.translate("MainWindow", "Nuclear Structure Options", None, QtGui.QApplication.UnicodeUTF8))
        self.b_runBSG.setStatusTip(QtGui.QApplication.translate("MainWindow", "Run the spectrum shape generator", None, QtGui.QApplication.UnicodeUTF8))
        self.b_runBSG.setText(QtGui.QApplication.translate("MainWindow", "Run!", None, QtGui.QApplication.UnicodeUTF8))
        self.le_outputName.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the output name of all files generated (omit extension)", None, QtGui.QApplication.UnicodeUTF8))
        self.le_outputName.setText(QtGui.QApplication.translate("MainWindow", "output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the output name of all files generated (omit extension)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Output name:", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgMainTab), QtGui.QApplication.translate("MainWindow", "Beta Spectrum Shape Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_phasespace.setText(QtGui.QApplication.translate("MainWindow", "Phase Space", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Basic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fermi.setText(QtGui.QApplication.translate("MainWindow", "Fermi Function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Electrostatic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_radiative.setText(QtGui.QApplication.translate("MainWindow", "Radiative corrections", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs.setText(QtGui.QApplication.translate("MainWindow", "ES Finite Size", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_ens.setText(QtGui.QApplication.translate("MainWindow", "ES Nuclear Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_efs_deformation.setText(QtGui.QApplication.translate("MainWindow", "ES Deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Kinematic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_recoil.setText(QtGui.QApplication.translate("MainWindow", "Nuclear Recoil", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Q.setText(QtGui.QApplication.translate("MainWindow", "Coulomb Recoil", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Atomic:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_screening.setText(QtGui.QApplication.translate("MainWindow", "Screening", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_exchange.setText(QtGui.QApplication.translate("MainWindow", "Exchange", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Nuclear Structure:", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C.setText(QtGui.QApplication.translate("MainWindow", "Shape factor", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_isovector.setText(QtGui.QApplication.translate("MainWindow", "Isovector Correction", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setToolTip(QtGui.QApplication.translate("MainWindow", "Use actual wave functions calculated using the options specified in the Config file options panel.", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_coupled.setText(QtGui.QApplication.translate("MainWindow", "Coupled", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_C_deformation.setText(QtGui.QApplication.translate("MainWindow", "Deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_relativistic.setText(QtGui.QApplication.translate("MainWindow", "Relativistic", None, QtGui.QApplication.UnicodeUTF8))
        self.b_enable_all.setText(QtGui.QApplication.translate("MainWindow", "Enable All", None, QtGui.QApplication.UnicodeUTF8))
        self.b_disable_all.setText(QtGui.QApplication.translate("MainWindow", "Disable All", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_mismatch.setText(QtGui.QApplication.translate("MainWindow", "Mismatch", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Matrix Elements:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "b/Ac:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "d/Ac:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Λ:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "Limits:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Begin:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_begin.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "End:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_end.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.dsb_step.setSuffix(QtGui.QApplication.translate("MainWindow", " keV", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_enforceNME.setText(QtGui.QApplication.translate("MainWindow", "Enforce", None, QtGui.QApplication.UnicodeUTF8))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.bsgOptionsTab), QtGui.QApplication.translate("MainWindow", "Spectral Shape Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen.setTitle(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSave.setTitle(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComponent_paths.setTitle(QtGui.QApplication.translate("MainWindow", "Component paths", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlotting.setTitle(QtGui.QApplication.translate("MainWindow", "&Plotting", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("MainWindow", "&Database", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadIni.setText(QtGui.QApplication.translate("MainWindow", "Ini file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadIni.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadConfig.setText(QtGui.QApplication.translate("MainWindow", "Config file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.a_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.a_feedback.setText(QtGui.QApplication.translate("MainWindow", "Submit feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveIni.setText(QtGui.QApplication.translate("MainWindow", "Ini file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveIni.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+I", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveConfig.setText(QtGui.QApplication.translate("MainWindow", "Config file", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveConfig.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+C", None, QtGui.QApplication.UnicodeUTF8))
        self.a_new.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.a_new.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.a_bsgExec.setText(QtGui.QApplication.translate("MainWindow", "BSG executable", None, QtGui.QApplication.UnicodeUTF8))
        self.a_bsgExec.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exchangeData.setText(QtGui.QApplication.translate("MainWindow", "Exchange data", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exchangeData.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.a_clearPlots.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.a_exportPlot.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.a_plotColorSettings.setText(QtGui.QApplication.translate("MainWindow", "Color settings", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadDeformation.setText(QtGui.QApplication.translate("MainWindow", "Load deformation", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadDeformation.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadRadii.setText(QtGui.QApplication.translate("MainWindow", "Load radii", None, QtGui.QApplication.UnicodeUTF8))
        self.a_loadRadii.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.a_findTransition.setText(QtGui.QApplication.translate("MainWindow", "Find transition (ENSDF)", None, QtGui.QApplication.UnicodeUTF8))
        self.a_findTransition.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
